### ISSUE TITLE
'Method eth_sendTransaction not allowed' error on sending transaction

### ISSUE THREAD

**Issue by seong627** [ethereum/mist#1013]
Node type: eth
OS: windows
Network type: test
Mist version: 0.8.1

Everytime I try to send any transaction on ethereum-wallet, I get following error messages
"METHOD_NOT_FOUND: The method being requested is not available on this server"
"Method eth_sendTransaction not allowed"

Blocks are alreay fully sync'd. I can mine ethers from testnet.

![cap](https://cloud.githubusercontent.com/assets/14135938/17054368/befce396-5041-11e6-9922-3ec5173d2f7b.PNG)
![cap2](https://cloud.githubusercontent.com/assets/14135938/17054369/bf277ec6-5041-11e6-9572-599c38ea619f.PNG)

**Comment by luclu** [comment]
Your setup seems to run on legacy versions. Make sure to update geth. Also are you sure this is `0.8.1`?

**Comment by seong627** [comment]
I'm using latest 1.2.9 eth with 0.8.1 mist client.

Here's how i did:

I did run eth 
`eth.exe --mining on --json-rpc-port 8545 --morden`

and then run ethereum-wallet.exe by double clicking on it.

![ver](https://cloud.githubusercontent.com/assets/14135938/17075979/e29db8b2-50e0-11e6-8d9a-64dc605c8fbd.PNG)
![console_ver](https://cloud.githubusercontent.com/assets/14135938/17075980/e3e64f90-50e0-11e6-9ef6-154241c04f95.png)

**Comment by luclu** [comment]
Unfortunately **eth** `1.2.9` still has these three bugs:
 - not HF compatible
 - old master-passwords (created before version `1.2.9`) will stall the communication to the node
 - and your case `eth_sendTransaction` was depreciated and removed due to an vulnerability and replaced by `eth_unlockAccountAndSendTransaction` which is not implemented in `1.2.9` - which prevents using the send function

Please use eth `1.3.0` downloadable from bob's [repo](https://github.com/bobsummerwill/cpp-ethereum/releases/tag/v1.3.0), wait some more days for the official release of `1.3.1` or use geth.

**Comment by seong627** [comment]
Ok. Thanks a lot.
