### ISSUE TITLE
Password to initial Etherbase account?

### ISSUE THREAD

**Issue by Ethereum2** [ethereum/mist#111]
Hi, I loaded this up on the main net using Geth 1.3.3 as the selected node and it had an Etherbase account already on it.  I funded that account with a small amount of Ether so that I could then create a wallet and now it says I need a password to do anything with those funds.  What is the password that the Etherbase account starts with?  I never set one and yet it keeps saying wrong password.  I can not send funds back out from that Etherbase account or create a wallet from it because of the password it keeps asking for that I never even set.  What is the deal??

**Comment by frozeman** [comment]
if it had an account, the you had an ether node once installed and created that account.

Try an empty password?

**Comment by keepdoing2** [comment]
I just wanted to comment on this issue from a slightly different perspective, but specific to the password issue.

After sending 3 Ether into my "Account/Etherbase", I began the process of trying to create a "Wallet".  The 1st 3 times I tried to do this I thought it wierd that it said no gas would be needed etc.  But then it gave me a "Wrong Password" message after trying to configure.  I closed out of Ethereum Wallet a couple of times.  Finally on my 4th try it showed a totally different "Gas" configuration - showing that Gas would actually be expended and a small ether deduction needed to do the transfer.  This time the transaction went through.  My password isn't exceptionally complicated, and I was very very slow and methodical in typing/retyping the 1st few times.  So just an FYI.... this is some sort of buggy situation.  Don't mind telling you that if I had actually had any Ether of value in their I would have been frieking by the 2nd time retyping PW and getting the "Wrong PW" message.

I will address this next thing in a dif post/topic, but I want to briefly comment that the whole "Account/Etherbase" vs "Wallet/Contract Wallet??" terminology AND THE SUPPORTING GUIDANCE VERBAGE is really confusing.  It gives the impression that ONLY Wallets are for storing/holding Ether - but direct send into those "Wallet/Contract Wallet??" accounts do NOT work (Show up?) if you don't do it from the Etherbase Acct.  I'm sending Ether out of Kryptokit's EtereumWallet, so to get Ether into Wallet you must go KryptokitEW -> Etherbase Acct -> Wallet/ContractWallet(?).

I can't help but believe that either something is royally F'd up - or you need someone to rewrite your instructions.

I think SHort Version Question surrounding the confusion is..... Are the Etherbase Accounts actually "wallets" in which it is a good idea to store Ether?  Because it is appearing that the "Etherbase Account" is actually the "Wallet", and the "Wallet" is actually a "Contract Wallet"???

Damn - this is confusing.  It shouldn't be this messed up and complicated.  Clarity dudes!

**Comment by frozeman** [comment]
Im sorry for the confusion, yes ether accounts are for storing ether, but wallet contracts give you extra security by protecting your funds with multisig. At the same time they are quite complicated for exchanges, as they normally don't track incoming funds from contracts...

So its a bit of a weird situation where the tech is faster than the surrounding ecosystem.
Don't forget you are here in a very early stage of a project, with a complete new way of doing things.

We are discussing to renaming the wallet contracts to make it more clear: https://github.com/ethereum/meteor-dapp-wallet/issues/95

@alexvandesande we should definitely make it more clear that accounts are valid "wallets" too

**Comment by frozeman** [comment]
Concerning your kryptokit money movement, i guess what happens is that kryptokit only adds 21000 gas, which is not enough if youre sending money to a contract, as the contract may use up a bit more (like 32000 gas). Therefore the transaction gets reversed and the money never leaves your wallet...

**Comment by elanperach** [comment]
+1

**Comment by luclu** [comment]
I will close this for now. Feel free to reopen or just continue the discussion.
