### ISSUE TITLE
Unable to find/run Ethereum Wallet 0.8.3

### ISSUE THREAD

**Issue by lowlanda** [ethereum/mist#1205]
#### System information
``````
Version: `0.8.3`
OS & Version: Windows 7 64bit
``````
Where is the .exe for Ethereum Wallet 0.8.3 ?

I read it was stored in:
  -   windows: `%APPDATA%/Roaming/Mist/app-0.8.3/

Couldn't find it here either:
  -   windows: `%APPDATA%/Roaming/Ethereum Wallet/

...but there's nothing in that folder. I waited all night for 0.8.3 to sync (which it did eventually), and I sent some ETH out. Then I restarted my PC, and I can't restart it!

I've never used MIST (I don't think...), should I do something with that program too, is it all the same thing, Ethereum Wallet, MIST, GETH?

All a bit frustrating and confusing, if I'm honest..

Any ideas/help/suggestions?

Cheers

**Comment by luclu** [comment]
@lowlanda try `%LOCALAPPDATA%` instead of `%APPDATA%`.

> I've never used MIST (I don't think...), should I do something with that program too, is it all the same thing, Ethereum Wallet, MIST, GETH?

geth is an ethereum node, which is used to synchronize and actually access the network. Other nodes are for example eth and parity.
Ethereum Wallet is an frontend. It actually IS Mist with only one DApp available - the Wallet. Mist will become something like a browser or appstore - a unified easy interface to many DApps.
Although it is still early, so stick to Ethereum Wallet for now! ;)

**Comment by lowlanda** [comment]
Thank you so much luclu, that was very helpful and informative. I remember hearing about MIST browser, now I see how it fits together with Wallet.

I managed to get Ethereum Wallet running again, by running the installer fyi.
