### ISSUE TITLE
Could you integrate parity?

### ISSUE THREAD

**Issue by molitar** [ethereum/mist#1219]
Geth is gotten so unstable and slow anymore I would like to see the faster parity integrated.  I currently do not use Parity as I have to go run a separate program that takes up more usage on top of the wallet.

**Comment by obscuren** [comment]
This sounds like a trivial thing to do, right? Well it isn't,
unfortunately :-(. As appealing as the idea might sound, it isn't. The EF
has a standard to up-keep and maintain. It also has a duty to make sure
that the software that's released is stable, secure and performant.

I'm not saying that Parity isn't any of that, I'm fairly sure that is,
however, we, as the EF can not guarantee it. We can't because it isn't
our software, we don't maintain it. You might say "well Geth
isn't any of that at the moment", you might be right but at least we
can guarantee that the software we deliver **will** and that we will
do anything in our power to make sure that it will stay that way. We
can because we maintain it :-)

We can only make integration easy and while Ethcore does currently not
release their own binaries of Mist, I'm pretty sure that if their
intention is to make it Mist compatible they'll release their own
binaries in the future.

**Comment by alexvandesande** [comment]
We are working on making all node binaries swappable. As Jeff stated we can't guarantee that any particular implementation will work but we are working to make it easy for them to set all the required parameters so the user can decide do download a new node on the fly.
