### ISSUE TITLE
"Decimal Places" when creating a contract is not descriptive enough

### ISSUE THREAD

**Issue by gcmartinelli** [ethereum/mist#122]
I first thought it would determine the maximum fungibility of my tokens (ex: 2 decimal places would limit the minimum share of 0.01 and not allow values such as 0.001 or below), when in reality it determines the position of the separator on the total number of tokens chosen. 

Also, I initially understood the number of tokens as the total number of "shares" in my contract. 

Ex: 10000 tokens with 2 decimal places results in 100.00 shares.

What I thought this would result in would be 10,000 tokens with a minimum token "size" of 0.01

**Comment by frozeman** [comment]
I agree this could be more clear, but as a creator of a contract you should be aware that contracts currently can't do float, so you need to set the units as uint's. And therefore the decimal places will divide this smallest units.
@alexvandesande any idea on how we can improve the text or the interface?

**Comment by alexvandesande** [comment]
This isn't an issue with the wallet but with the particular contract implementation of the constructor function. You can change your contract to behave like you are expecting by changing the constructor to multiply the total supply by the decimal places.

The issue is that the constructor function has limited space, so if you have a suggestion on how to improve it, I'd appreciate it. Click on 'improve this page' on http://ethereum.org/token

**Comment by Ekallywoodcoin** [comment]
What is Ethereum decimal?

**Comment by Ekallywoodcoin** [comment]
What is Ethereum decimal?

**Comment by alexvandesande** [comment]
@Ekallywoodcoin  you're creating a coin and have to select the amount of decimal places it can be divisible by
