### ISSUE TITLE
HI i have made transection and its gone to wrong address

### ISSUE THREAD

**Issue by Narek008** [ethereum/mist#1264]
HI i have made transiaction 5 etherium to address 0xed06dbc90e28784a329601aa9473e364292710b0
but its didnt conformd . Then i chack it with www.myetherwallet.com its shows that my transection go to another address 
0x4e61bec0eF753cC00f3c81cf5aC3F7F87838Fd35 please help

**Comment by luclu** [comment]
@Narek008 you are right, as the following links show `0x4e61bec0eF753cC00f3c81cf5aC3F7F87838Fd35` was the recipient of the 5 Ether:
- https://etherscan.io/address/0xed06dbc90e28784a329601aa9473e364292710b0
- https://etherscan.io/address/0x4e61bec0eF753cC00f3c81cf5aC3F7F87838Fd35

Unfortunately a reversion is not possible due to Ethereum's immutable nature.

**Comment by Narek008** [comment]
0x4e61bec0eF753cC00f3c81cf5aC3F7F87838Fd35 i know that problem is not in that problem was i send it to 0xed06dbc90e28784a329601aa9473e364292710b0 but its gone  to another how can its be 
![default](https://cloud.githubusercontent.com/assets/22664043/19169087/e93b6312-8c23-11e6-9334-9a6c9ef283f6.jpg)

**Comment by Narek008** [comment]
@luclu

**Comment by luclu** [comment]
The transaction-ID on your screenshot refers to a transaction that didn't get relayed. This means it didn't happen to take place on the main-net blockchain (https://etherscan.io/tx/0xaeddc2a60ef5cab0f5c93a03653fa99eeb6ab8f17161885c478de2de3a633c54).

The 5 Ether transaction seems to have happened 4 minutes later (if you are on UTC+7).

**Comment by Narek008** [comment]
its ok and way its gone to another address i made only this transaction

**Comment by Narek008** [comment]
im in GMT+4 @luclu
