### ISSUE TITLE
Missing coins (money)!!!

### ISSUE THREAD

**Issue by kosoizayc** [ethereum/mist#1313]
It has been over 14 hours,why is the wallet, no coins!?
I reinstalled the wallet on another computer moved the account C:\Users\1\AppData\Roaming\Ethereum\keystore and 0 coins,what to do, where did my money?
![new mashine](https://cloud.githubusercontent.com/assets/22880144/19444036/10a568f6-94b9-11e6-93e8-6680a7c5f7a0.PNG)
what to do?

**Comment by kosoizayc** [comment]
![14 hour](https://cloud.githubusercontent.com/assets/22880144/19444084/33e22458-94b9-11e6-9bc2-5421b9d5f9f5.PNG)

**Comment by evertonfraga** [comment]
Hi @kosoizayc, I can see that [your account has the intended balance](https://etherscan.io/address/0xbe1b654c5efac5d09f6ea71b666ee9cdaa0ebe50) (~1.002 ETH).

Please check if you Ethereum Wallet needs to be synced. That's probably the issue. You need to sync past block 2,453,223 in order to catch this transaction you sent on 2nd message.

**Comment by kosoizayc** [comment]
What to do, I completely reinstalled the wallet on another computer and transferred the account! What to do I can write?

**Comment by kosoizayc** [comment]
![rji](https://cloud.githubusercontent.com/assets/22880144/19444567/1fed34ea-94bb-11e6-8002-1f2f16b5cd72.PNG)

**Comment by evertonfraga** [comment]
Hi @kosoizayc, sorry that this has caused some panic/confusion.

On the way that currently our ethereum clients work, the Wallet has to download all the blocks (up to 2,453,223)  in order to update to your account latest state. 

I can see from your screenshot that there are 1.5M blocks left to download. If you wait until it's completely synced, you'll be glad that your balance will appear again.

So: no worries, it'll be fine :)

**Comment by kosoizayc** [comment]
For the 13 dollars I wanted today to order a baby gift for a birthday, but still they never showed, I waited a long time! Now the poor kid will get a gift in time for the birthday, because I very much was upset, when I saw that my previous post closed!

**Comment by evertonfraga** [comment]
@kosoizayc if you are in a hurry to send Ether out, you can use a third-party wallet (meaning it's not mantained by ethereum foundation), such as [My Ether Wallet](https://www.myetherwallet.com/#send-transaction).

You'll have to select _Keystore file_ option, select your account file, insert your password and go on.

**Comment by kosoizayc** [comment]
I recently learned about ether ! A friend recommended this purse, I decided to use it and having this problem! Thanks for the help! How to improve, write!

**Comment by luclu** [comment]
Duplicate of https://github.com/ethereum/mist/issues/1309.

**Comment by kosoizayc** [comment]
Never came the coins!
![pic](https://cloud.githubusercontent.com/assets/22880144/19460883/21c0ae88-950a-11e6-9d13-6d9a7a5d2bb2.PNG)
