### ISSUE TITLE
"Exceeds Gas Limit" - Cannot Create Multisig Wallet Contract

### ISSUE THREAD

**Issue by SingularDTV** [ethereum/mist#1335]
#### System information
``````
Version: `0.8.6`
OS X El Capitan Version 10.11.4
Node type: `eth/geth(default)`
``````

<img width="586" alt="screen shot 2016-10-21 at 5 54 22 pm" src="https://cloud.githubusercontent.com/assets/19651841/19612969/a704ab12-97b7-11e6-9aee-1cddda0d09d6.png">

**Comment by luclu** [comment]
This is caused by the currently lowered [gas limit](https://ethstats.net/) (1.000.000/block).
Although miners are advised to vote for a limit of 2.000.000 the deployment of contract wallets won't be possible until this limit is reached. Please be patient during the on-going DDoS attacks. You can follow on the progress on reddit and the EIP proposals if interested.

**Comment by luclu** [comment]
Gas limit is back at 2e6.
