### ISSUE TITLE
msg.sender.send() not working for contract -> contract-based wallets transactions

### ISSUE THREAD

**Issue by emosto** [ethereum/mist#135]
When a contract tries to send ether using msg.sender.send() to a contract-based wallet it fails (without error). However, msg.sender.send() works if the sender is the etherbase account. A workaround I found was to use tx.origin.send() but this then sends the amount to the etherbase account and not to the calling wallet.

Shouldn't msg.sender.send() do its job no matter where the address points (contract or account)?

**Comment by emosto** [comment]
I'm sorry, this issue should have been attached to the dapp-meteor-wallet project I guess..

**Comment by frozeman** [comment]
Thats more of a question for solidly: @chriseth

**Comment by simondlr** [comment]
Could this be related to the inherent limitation in contract to contract send()? It only has the gas stipend it can use. No other gas is forwarded. http://solidity.readthedocs.org/en/latest/frequently-asked-questions.html#what-is-the-deal-with-function-inside-solidity-contracts-how-can-a-function-not-have-a-name. It seems the contract wallet would have enough gas to do that fallback function (check if msg.value and do a log). But it might be just too much (not sure if the if statement could be screwing this up). Did anyone check/test on this?

(A work-around is to use ```address.call.value(_value)(_data)``` instead as this forward gas).

**Comment by frozeman** [comment]
I think the problem comes from us, using stub contracts when generating wallets. These use call code to "access" the code of the "original" wallet.
This wallet code then uses `tx.origin` instead of `msg.sender`, as `msg.sender` would refer to the contract calling the code and not the (before) last contract or transaction sender.

**Comment by emosto** [comment]
Thanks for picking it up, guys.There is another reported issue related to this behavior, I have the feeling - #76

**Comment by chriseth** [comment]
I think @simondlr's analysis is correct. The stub correctly receives the transfer and forwards it using CALLCODE to the actual code but also has to send the ether again. This could cost more ether than the stipend allows.
If this is correct, then this will be fixed in homestead, where we have better contract stubs.

**Comment by kieranelby** [comment]
For what it's worth, I got bitten by this surprising interaction between address.send() and wallet contracts here: http://www.kingoftheether.com/postmortem.html

**Comment by EthGambler** [comment]
This is a horrible bug it makes contract to contract  interaction with pre-deployed contracts pretty much impossible in many cases.

The work around doesn't work for me am I doing it wrong? The following code compiles fine but no transaction is ever sent. 

  owner.call.value(houseFee);

**Comment by chfast** [comment]
I'm not sure where the Wallet code is, but it looks to be fixed in https://github.com/ethereum/meteor-dapp-wallet/blob/develop/Wallet.sol#L334-L338.
