### ISSUE TITLE
Modify default contract template

### ISSUE THREAD

**Issue by chevdor** [ethereum/mist#1352]
#### System information

```
Version: `0.8.6`

```

Please change the default template from:

```
contract MyContract {
    /* Constructor */
    function MyContract() {

    }
}
```

```
pragma solidity ^0.4.2;

contract MyContract {
    /* Constructor */
    function MyContract() {

    }
}
```

to get it a chance to compile without first complaining about the pragma missing.

**Comment by luclu** [comment]
@chevdor thank you! 
This issue occurs because the old contract template is cached in the *localstorage* (to prevent data-loss on crashes).

@frozeman we might want to add a check for the old template or simply add a *version number* to the template as the pragma-line will continue to change in the future.
