### ISSUE TITLE
Password Wrong All the Time

### ISSUE THREAD

**Issue by moamin77** [ethereum/mist#141]
Hi,

I've installed the wallet properly on my Windows 7 Laptop....& even sent to it some Ether to test the functionality, the amount was received perfectly in the EtherBase....the issue is when I try to send out Ether from the wallet & then got asked about the password.....I'm sure I'm writing it correctly all the time but it always gave me the wrong password message....restart of the Wallet as well as the Laptop gave the same result....
Any help?
Thanks

**Comment by frozeman** [comment]
I had this issue with others as well and it turned out they used the wrong password...
You can try to unlock your account using the command line, you can find your geth.exe under `wallet/resources/node/geth`

There are many tutorials out there to help: https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

**Comment by frozeman** [comment]
Please re-open if you find it to be an error in mist
