### ISSUE TITLE
How do I make this use the version of Geth installed in program files instead of the older 1.5.3 version?

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [ethereum/mist#1490]

**Comment by luclu** [comment]
1. When starting up Ethereum Wallet/Mist will check [this file on github](https://github.com/ethereum/mist/blob/develop/clientBinaries.json) for the latest version.
2a. If this version is globally installed (in $PATH) (see [this guide](https://stackoverflow.com/questions/4822400/register-an-exe-so-you-can-run-it-from-any-command-line-in-windows) on how to do it) and its version match the one from github it will use that version.
2b. Otherwise it will download that version to the config folder.

Starting with release 0.8.8 you will be able to skip the download and thus stick with any globally installed version (matching the latest version from the github file).

**Comment by Laurentiu-Andronache** [comment]
I see. So basically I can't use a newer version of geth then. Well the wallet is stuck... again...

**Comment by luclu** [comment]
Yes, this will be possible with the next release.
> Starting with release 0.8.8 you will be able to skip the download and thus stick with any globally installed version (matching the latest version from the github file).
