### ISSUE TITLE
Dependencies missing for .deb packages

### ISSUE THREAD

**Issue by safinaskar** [ethereum/mist#1529]
#### System information
``````
Version: 0.8.8
OS & Version: linux, debian gnu/linux jessie amd64
Node type: geth(default)
``````

Not all dependencies for .deb are specified.
I just created fresh debian jessie container using debootstrap.
Yes, the resulting system doesn't contain X, but i am going to connect mist to external X, i. e. to X, which is outside container.
Then I tried to install mist via .deb package. dpkg said to me that I need packages libappindicator1 libnotify-bin. Okey, I installed them.
Then I tried to run mist and I got:
```
# DISPLAY=:0 /opt/Mist/mist
/opt/Mist/mist: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory
```
So I had to install missing dependency. Then I tried again and got same message about another lib.
So, please add really all dependencies to .deb package

**Comment by safinaskar** [comment]
Here is list of additional dependencies you forgot. List is composed using try-and-error method. List is for debian jessie. But, of course, I could be not right.

libxtst6
libxss1
libgconf-2-4
libnss3
libasound2

**Comment by luclu** [comment]
Thank you @safinaskar to bringing awareness to this issue. Eventually those packages are not bundled by default by electron-builder: https://github.com/electron-userland/electron-builder/issues/509#issuecomment-278673656 as they are assumed to be shipped by the desktop window manager and omitted to keep the file size low.

Altough according to the [electron-builder wiki](https://github.com/electron-userland/electron-builder/wiki/Options) these packages are shipped by default for debs:
```
"libnotify4",
"libappindicator1",
"libxtst6",
"libnss3",
"libxss1",
"fontconfig-config",
"gconf2",
"libasound2",
"pulseaudio"
```

I would like to pinpoint the missing libs and add them to our packages and would be glad if you could help out by testing fixed deb packages. Just give me a ping should you find some time otherwise I would like to wait for this being fixed upstream for now.

**Comment by luclu** [comment]
electron-builder added `libnss3` as default (https://github.com/electron-userland/electron-builder/releases/tag/v16.7.1).
Please test again after we updated and created a new release!
