### ISSUE TITLE
wallet-contract stuck in creation indefinitely

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#1573]
Eventually trying to create a wallet contract can result in a indefinite creation process, i.e. the creation animation persisting over application life-cycles.

Didn't find a way to reproduce it, yet.

<img width="629" alt="bildschirmfoto 2017-01-11 um 14 23 38" src="https://cloud.githubusercontent.com/assets/10135872/21850180/947a0d92-d809-11e6-8fce-a8c5afbdd85d.png">

**Comment by Kyniska** [comment]
Same problem

**Comment by lukecti** [comment]
I am also having this problem

**Comment by Kyniska** [comment]
I switched over to ethereum from a lengthy hyperledger setup process due to a perception of easier access and rising popularity.  From what I've seen so far I'm leaning towards the conclusion that the "rush to market" effect, has, once again, produced sub-par software with a nice look that doesn't actually pass the cut.  Neither the Ethereum wallet or Mist is in a state where I'm prepared to recommend either to anyone, based on functionality.
