### ISSUE TITLE
OSX Mist 0.3.9 (0.36.4) can't deposit ether to wallet's owner account

### ISSUE THREAD

**Issue by glesaint** [ethereum/mist#159]
Hello,

I'm trying to deposit 10 ether from a wallet contract to an owner account.
The owner account has a balance of 0.01 ether. 
The wallet contract has more than 10 ether.
The transaction fee is 0.0032172.
The total is 10.0032172.

I'm getting "Insufficient funds for gas * price + value".
Am I doing something wrong here?
Thanks and congratulations on mist overall it's really great!

**Comment by frozeman** [comment]
@obscuren any idea? Maybe the gas + funds calculation is wrong in geth?

**Comment by klmoney** [comment]
The problem here could be due to rounding. The ether balance rounds up to 2 decimal places in the Accounts Overview screen. So the 0.01 ether can be 5 to 10 finney. (Change the unit to finney at the top right of the screen to check.)

The gas limit for the tx would be about 165,000 due to the extra 100,000 that is added. So anything less than about 8.25 finney will give an insufficient funds error

**Comment by frozeman** [comment]
the numbers are not stored rounded, they are stored as full wei. They only get rounded when displayed.

**Comment by klmoney** [comment]
What I mean is that the user sees 0.01 ether and reports the balance as such, which should be enough for 200,000 gas -- enough for this tx. But the stored balance, the actual balance, for that account may be less than 10 finney?

**Comment by frozeman** [comment]
thats possible. But don't you think its an edge case that people count so tide?

i might increase the decimal places though

**Comment by klmoney** [comment]
Agree, edge case.

**Comment by alexvandesande** [comment]
Decimal places were increased in the last wallet. @glesaint does that solve your issue? Will close it otherwise

**Comment by glesaint** [comment]
@alexvandesande it does thanks!
Didn't know we couldn't change units, thanks @klmoney
