### ISSUE TITLE
Ethereum-wallet not working with Parity

### ISSUE THREAD

**Issue by Nogreedy** [ethereum/mist#1659]
#### System information
``````
Version: 0.8.9
OS & Version: windows10
Node type: parity
``````
________________________________________________________
Hello,
I can't use Ethereum wallet with Parity.
I start Parity (1.5.2)  with parity.exe --geth --force-ui  it works well  (browser UI) but when I try to use Ethereum-wallet to connect to Parity node, it doesn't work... 
In fact, Ethereum-wallet starts ... synchro is OK but I can't create new account... when I try to create account, I indicate the password I want to protct this account... but I can't view my new account in "account overview".
Depite this, **I can** view this new account in Parity. 
Logfile : 
```
[2017-02-13 01:34:43.974] [DEBUG] Windows/requestAccount - Close
[2017-02-13 01:34:43.985] [DEBUG] Windows/requestAccount - Closed
[2017-02-13 01:34:43.986] [DEBUG] Windows - Removing window from list: requestAccount
```

In fact, I haven't exactly the same accounts in Parity and Ethereum-wallet !
Inside Ethereum-wallet, when I try to send Ethers from one account to an other account I receive message : "Method not found" and "sometimes",   "Method eth_sendTransaction not allowed".
Logfile : 
```
[2017-02-13 01:31:34.627] [INFO] (ui: popupWindow) - Choosen Gas:  0x1d8a8 0x1d8a8
[2017-02-13 01:31:34.628] [ERROR] ipcProviderBackend - Send request failed { code: -32601, message: 'Method not found', data: null }
[2017-02-13 01:31:38.530] [DEBUG] method/eth_sendTransaction - Confirmation error Transaction not confirmed
[2017-02-13 01:31:38.530] [DEBUG] Windows/sendTransactionConfirmation - Close
[2017-02-13 01:31:38.530] [DEBUG] Windows/sendTransactionConfirmation - Close
[2017-02-13 01:31:38.531] [ERROR] ipcProviderBackend - Send request failed Transaction not confirmed
[2017-02-13 01:31:38.539] [DEBUG] Windows/sendTransactionConfirmation - Closed
[2017-02-13 01:31:38.539] [DEBUG] Windows - Removing window from list: sendTransactionConfirmation
[2017-02-13 01:31:38.540] [INFO] (ui: browser) - {} null
```
I specify I'm not the only one with this issue because an other person have talked about it on reddit (I'm notsogreedy on reddit)...
https://www.reddit.com/r/ethereum/comments/5tm610/parity_152_not_working_with_ethereum_wallet/

Thanks in advance for your answer.

[logETHwallet.txt](https://github.com/ethereum/mist/files/769837/logETHwallet.txt)

**Comment by frozeman** [comment]
@gavofyork @debris we use `personal_sendTransaction` here, to send the tx with password to unlock the account. Is that not available in parity?

**Comment by Nogreedy** [comment]
I must indicate I have **NOT** this issue when I use Mist 0.8.9 with Parity 1.5.2 on Linux Ubuntu 16.04 (Mint 18.1-Serena).

**Comment by kasper1223** [comment]
I (noob) have a similar problem (on Linux Mint):

I normally run "parity --geth" first, in order to sync, and then start Mist.
Everything was fine with parity 1.4.9 and Mist 0.8.8, but then I did an update to Parity 1.5.2 and Mist 0.8.9 and now, when I open Mist, I can no longer send any ether from any of my accounts. If I try, I get "Method not found". Some of the accounts also got "shuffled": for instance: what used to be account 1, is now account 3 etc.  

I also tried Parity GUI and that does work without a problem.

Possible reason maybe: the difference between Mist browser and Ethereum Wallet is not very clear to me. Maybe I had been using Ethereum Wallet 0.8.8 before (I downloaded: Ethereum-Wallet linux64-0-8-8), and downloaded I Mist browser 0.8.9 after that (Mist-linux64-0-8-9.deb), with the two now both on my computer and interfering??? When I first started Mist 0.8.9 after the update, I got a message "detecting new node" (if I remember correctly)

**Comment by sandman33** [comment]
Hi everyone!
My parity 1.8 wallet installed on linux xubuntu does not perform transfer to any adress.
The transaction are started and stay forever on status "transaction sent to network with hash......", 'confirmation from nodes' phase is never reached. The wallet is synchronized, software is updated.
Help please!

**Comment by evertonfraga** [comment]
We haven't had any response from Parity devs. Closing this for now as we're not providing support for other nodes at this moment. We will reassess this subject later in the future. 

Thanks.
