### ISSUE TITLE
Not receiving Ethers in TestNet

### ISSUE THREAD

**Issue by Jagansundaramoorthy** [ethereum/mist#1672]
#### System information
``````
Version: `0.8.9` Ethereum Wallet
OS & Version: windows10
Node type: `geth 1.5.8

I am not getting any Ethers when I mine on Test Net. I mined for more than 3 hours and still I did not get any Ethers. Also when an Ether is transferred from other Ether wallet I don't receive any Ether in my account

Ethereum Node: Geth 1.5.8
Network: Testnet

[node.log.zip](https://github.com/ethereum/mist/files/782418/node.log.zip)

**Comment by luclu** [comment]
@Jagansundaramoorthy unfortunately some user did use a GPU mining rig on the testnet which made it nearly impossible to mine any Testnet Ether using a CPU. The problem seems to be resolved now, but you can also ping https://www.reddit.com/user/Souptacular to get a nice amount of the premined Testnet Ether.
