### ISSUE TITLE
Ether never arrived all 241 of them!! 

### ISSUE THREAD

**Issue by bitmidas888** [ethereum/mist#1793]
For a Newbie, this is rather worrying.. I bought Eth through the SHapeShift button on the wallet, I bought 8 times over the hour and 6 arrived, 2 have not arrived...

What happens now? how do I get this resolved?

thanks in advance,

BitMidas888

**Comment by AmesEla** [comment]
I am having the same issue. VERY stressful

**Comment by evertonfraga** [comment]
Are your local blockchain synced? 
In order to confirm your balance, before it has finished to sync, you can hop into a blockchain explorer like this, and search for your address:

e.g.: https://etherscan.io/address/0x33be28a46b6dc3211350a747d821eb6a2ba089de

![image](https://cloud.githubusercontent.com/assets/47108/24358212/cb7d5e04-12d6-11e7-86f3-822f1bcb2d8f.png)

**Comment by AmesEla** [comment]
Yes it finally synched after 3 days 

___________________________
The only constant is change.
