### ISSUE TITLE
Refund DAO-ETH problem

### ISSUE THREAD

**Issue by kornholio** [ethereum/mist#1798]
Hi,
I want to refund my DAOs to ETH after the hard fork... If I click "watch contract" and enter the DAO-Adress and click ok there comes a message "Couldn´t parse to JSON interface"

What´s to do...?

Thanks.

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by GriffGreen** [comment]
If you really want to go through the exercise of using the contracts directly (with the basic Mist UI) more power to you, but there is an easier way...If you need any help with anything join the Giveth Slack and send me (@griff) some screen shots and your address! Sign up for the Slack at http://slack.giveth.io

@bokkypoobah made an incredible wiki for Ethereum and it has an excellent entry for how to recover your DAO funds: https://theethereum.wiki/w/index.php/The_DAO_Refunds#How_Do_I_Withdraw_The_DAO_Refunds.3F 
To summarize:

The easiest way to collect the funds is to run an old version of the MyEtherWallet.com site locally so you can still use their user interface. Running their user interface locally allows you to have all the functionality of normal contracts like sending tokens and interacting with contracts, while signing everything offline.

1. Download [v3.3.7 of MyEtherWallet](https://github.com/kvhnuke/etherwallet/releases/tag/v3.3.7).
2. Click on dist-v3.3.7.zip.
3. Unzip it.
4. Double-click index.html (works best in Chrome).

In case you are not familiar with this, you need to keep the entire folder in order to run the website, not just index.html. Don’t touch or move anything around in the folder.
Once you have it open…

1. Go to The DAO page ([~]/dist-v3.3.7/index.html#the-dao in the toolbar).
2. Click all the big red buttons.

As an alternative, you can use the etherscan hosted version of MyEtherWallet v3.3.7: https://etherscan.io/myetherwallet/

Feel free to review: https://medium.com/curator-multisig-phf-official-channel/dao-token-holders-come-claim-your-money-b428f186572a#.9ur5tfm26

**Comment by tomcoss** [comment]
This is insufferable. I can see my DAO, but for the life of me I'm unable to capture them into Ether.
Any ideas?  I've tried MyEtherWallet and Mist.  Is there any hope?

**Comment by GriffGreen** [comment]
@tomcoss Please come to my slack and DM me (@griff) you can send me your address and screen shots and I can offer support
