### ISSUE TITLE
Ethereum Issue

### ISSUE THREAD

**Issue by szesch84** [ethereum/mist#2111]
I wanted to buy my first ETH yesterday using BTC.
After sending the BTC the ETH appeared in my wallet.
But today there isn't any ETH in my account and there is no transaction visible!
What happened?
What can I do next?

**Comment by szesch84** [comment]
I got an email with all details and blockchain also shows the transaction. But there is no ETH in my wallet.

**Comment by szesch84** [comment]
Well, it's the good old sync problem.
But... after synchronizing 20h I only had 67%
Therefore it is not possible to reach 100%, because after 24h the router reconnects.
How can I get my money out of this stupid ethereum wallet?

**Comment by evertonfraga** [comment]
Hi. Some recommendations:

- check your account's balance using http://etherscan.io
- make a backup of all account's keystore files via menu -> accounts -> backup -> accounts
- please check this troubleshooting guide on our wiki: https://github.com/ethereum/mist/wiki
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com if you need to make transactions in a hurry

If this didn't solve your issue, please follow these instructions and upload the node.log files:
- go to menu -> accounts -> backup -> application data
- zip and upload node.log and all other node.log.X files

In order to keep duplicated issues at minimum, let's keep this conversation at a single place, which will always be updated with latest syncing status: https://github.com/ethereum/mist/issues/3097
