### ISSUE TITLE
Is there a mist-portable mode now?

### ISSUE THREAD

**Issue by Onkovat** [ethereum/mist#2120]
It's more a questions than an issue. I know there is a flag -datadir but I read on here that it doesn't mean ethereum being fully portable. Is there a portable mode implemented by now?

Which options are there at the moment? Ethereum takes 20.4GB of my C: drive, mostly because of chaindata so I would have to move that at least. Though I prefer a clean solution with everything in one place.

Thank you!

**Comment by luclu** [comment]
Hi @Onkovat,

we don't plan a portable mode (only one executable internally storing settings+data) in the near future as storing the full chaindata will bloat beyond portability. That said it should still be possible to do yourself using tools like https://www.vmware.com/products/thinapp.html.

Concerning the chaindata folder, one features we will tackle in the `0.9` line will be GUI settings, where you will be able to specify a `datadir` without flags. Furthermore with [LES](https://github.com/ethereum/wiki/wiki/Light-client-protocol) maturing, an light-client mode will shring the chaindata size to some hundret MBs. Finally we are looking into the integration of https://infura.io, which is a remote node (cluster) hosted by consensys. Note, that this will never be the default as it will shift the trust to the node operator.

**Comment by Onkovat** [comment]
Hello luclu,

thanks for answering, well portability doesn't necessarily mean wanting it on an usb stick. Portable harddiscs would be a solution also. But more important for myself is the clean and enclosed install. Everything in one place. No search in different locations in hidden system directories or registry about settings. Also different wallets would be possible which is not possible when every wallet accesses the same dir.

Thanks!

**Comment by tastyratz** [comment]
Hi, I just wanted to add to this one. Portable has a value in the respect that MIST installs executables and executes IOPS on drives different from the install dir. 

Example use case would be the ability to put a cheap scratch SSD to be flogged with mining duty without wearing an expensive primary M.2 storage drive.
Portable to me means Install folder should be self-contained without utilizing %appdata% or otherwise.

I am running into this exact issue today in my experimentation.
