### ISSUE TITLE
[Question] How to use Mist without mining?

### ISSUE THREAD

**Issue by matunixe** [ethereum/mist#2165]
Hello there,

I'm trying to run Mist on a last gen Macbook Air and I would like to know what should I do to run it without running Geth. As it's not a very powerful computer I just want to sync with the blockchain, to check my wallet state.

Thanks in advance for your help.
Regards,

**Comment by luclu** [comment]
Hi @matunixe, if you only want to sync with the network (in order to interact and see the current shared state) simply start Mist/Ethereum Wallet. It uses the network client (node) "geth" to do this. 

So no need for mining. Please refer to [mining paragraph](https://ethereum-homestead.readthedocs.io/en/latest/mining.html) to gain a deeper understanding.

**Comment by matunixe** [comment]
Ok, thanks for your answer @luclu.
