### ISSUE TITLE
Send eth hasnt recieved

### ISSUE THREAD

**Issue by Carl2017** [ethereum/mist#2168]
Hi there,

I have downloaded the Ether wallet (from the official Etherium web site) and after installing it, use the Main account (Etherbase on Main Network) address to receive some Ether from a mobile app.
Later I realized there are more than 1.3 m Blocks before it sync

When i would be able to see my updated balance? What can I do recover my Ether?

Carl2017

**Comment by bptv1** [comment]
Did the same thing. It's confirmed  that it sent on the app but hasn't shown up in the Ether wallet. I didn't realize it doesn't show incoming transactions unless you have a contract set up and it requires ether to do so I'm kinda just sitting around waiting wondering what's going on. It's only been a few hours but still, should've showed up by now. I have the same sync issue as well.

**Comment by Carl2017** [comment]
My wallet has synced now but it could days. Let it run all night for few
days and will be synced.

**Comment by evertonfraga** [comment]
Hi, slow sync can be frustrating. Some recommendations:

- check your account's balance using http://etherscan.io
- make a backup of all account's keystore files via menu -> accounts -> backup -> accounts
- please check this troubleshooting guide on our wiki: https://github.com/ethereum/mist/wiki
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com if you need to make transactions in a hurry

If this didn't solve your issue, please follow these instructions and upload the node.log files:
- go to menu -> accounts -> backup -> application data
- zip and upload node.log and all other node.log.X files

In order to keep duplicated issues at minimum, let's keep this conversation at a single place, which will always be updated with latest syncing status: https://github.com/ethereum/mist/issues/3097
