### ISSUE TITLE
When connecting with certain daaps to an account the left (wallet, browser, connected daaps ) slidebar vanished. 

### ISSUE THREAD

**Issue by saso10** [ethereum/mist#2171]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment]
Hello, sorry to hear that. Although this problem is now solved on v0.8.10, I'd encourage you to delete/move your Lokidb file.

1) Go to finder and press `Cmd + Shift + G (go to folder)` and paste `~/Library/Application Support/Mist`
2) Then rename/move `mist.lokidb` file, and this `mist.lokidb~` file, if you have it.

That will work. And If you update to the new v0.8.10, you won't experience that again.
