### ISSUE TITLE
Missing Ethereum

### ISSUE THREAD

**Issue by Fanorn305** [ethereum/mist#2185]
#### System information
``````
Version: `0.8.9'
Windows 10 64bit
Node type: Geth 1.6.0
``````
I purchased some Ethereum through my Wallet with a credit card.  It connected to Coinbase and processed the transaction.  However when Coinbase sent the Ethereum to me, it was sent to some other wallet account # that I dont recognize.  My wallet is now fully sync'd with the network.  This was my first time putting anything into this wallet.  I didn't designate the wallet address to Coinbase, and there was no review of where it was going before I submitted.

Later, I purchased some more Ethereum through the wallet, and the second amount was transferred to my wallet correctly.

I dont know what I need to do to get the first Ethereum  I purchased?  Is the "Keystore" file where the keys are stored, or does that represent the # of accounts I have?  If not what file has the Keys?   There are two files in my Keystore file.

This is my missing Ethereum transaction..
https://etherscan.io/tx/0xad128846e3aa58b866961f0a611eec5f3af7398cac68a06e52d94374d7456724

**Comment by evertonfraga** [comment]
Hello @Fanorn305, answering your question about the keystore folder: 

Each file represents an account. They should be exactly correspondent in the wallet. You can identify the file's account by it's name. Just like the picture below.

<img width="430" alt="screenshot 2017-05-09 14 35 06" src="https://cloud.githubusercontent.com/assets/47108/25864194/fa42e5c8-34c4-11e7-9f2d-c89018c2bbc5.png">

Now, regarding coinbase, I think you should get in touch with them in order to clarify this situation.
