### ISSUE TITLE
Etherium were not enrolled

### ISSUE THREAD

**Issue by Rihard83** [ethereum/mist#2186]
#### System information
```
Version: `0.8.9`
OS & Version: windows 7
Node type: `eth/geth(default)`
```
Hello! 
Need your help. I Sent Etherium on the website "Bitsler" with my wallet mist. 
The funds were debited, the transaction is tracked https://etherscan.io/tx/0xc3d379a1e9beb384e55aef67ea94f9360da7b90c65dda05f7e9625938a07e317, but on my account at the "Bitsler" funds has not been received. Support "Bitsler" he replied, "You made a deposit with a contract. We don't accept contract as deposit". What's the problem?

**Comment by evertonfraga** [comment]
The Ethereum world have two entities capable of storing and sending value around: accounts and (smart) contracts. 
Not all recipients accept ether from contracts, though. It's a limitation on their side, on their own business and technical rules. You could ask them for a refund and operate again from your own account, instead of a wallet.
