### ISSUE TITLE
mist compatibility with hardware wallets? 

### ISSUE THREAD

**Issue by briannyeko** [ethereum/mist#222]
Will mist be compatible with hardware wallets such as Keepkey,Trezor and ledger in the future?

**Comment by frozeman** [comment]
Maybe

**Comment by bluecamel** [comment]
+1

**Comment by mcgravier** [comment]
Trezor firmware supporting Ethereum has been released. Ability to use it with Mist would be very appreciated

**Comment by lekanovic** [comment]
Mist compatibility with Trezor would be a really good feature, any update on this task?

**Comment by mcgravier** [comment]
Also, it is worth noting, that title is misleading - in context of wallet software, HD stands for Hierarchical-Deterministic, which is unrelated to hardware wallet support

**Comment by luclu** [comment]
I would love to see this being supported as this is in my opinion an outstanding and strongly desired feature for some, though we are currently saturated with work on our infrastructure, the integration and coordination of other core infrastructure pieces like swarm and ENS and well, overall stability is still far away from satisfying.

That said this piece might be tackled within the 0.9 line or rather beyond - though there could be some internal or external developer giving it the love it deserves any time soon!

**Comment by DuaneNielsen** [comment]
I would love to hold ETH as part of my investment portfolio, as I think it has great growth prospects.  I don't seem myself dropping serious money on it though without some kind of hardware based wallet.  Trezor seems to be the best one out there.. It would be comforting to be able to use it with ETH.

**Comment by lekanovic** [comment]
Yes I agree with that. There is another option you can use the Ledger nano s hardware based wallet. I have bought the Trezor so I have to wait for mist wallet to support it

**Comment by kayagoban** [comment]
Yes, I would love integration with my ledger s.

**Comment by Nogreedy** [comment]
+1 support for hardware wallets is very important.
Please ask support for Ledger Nano S and Ledger Blue.

**Comment by mrcybermac** [comment]
I can see that geth has some support for ledger nano s.  It recognizes when it's connected and presents it to Mist instead of the normal keystore.  However Mist doesn't really handle it well for a number of reasons:

1.  It doesn't show all the accounts.  For some reason Mist is only showing two accounts, yet when I connect the same to myetherwallet.com it can see numerous previously generated accounts.

2.  Mist still allows you to "create a new account" but then asks you for a password.  That's not correct as there are no passwords where a hardware wallet is concerned, the private keys are merely protected by a PIN on the hardware device which is outside the scope of Mist and the process of creating a new account should be offloaded to the attached hardware device.

I, for one, would very much like to see a smart integration between Mist and geth or other nodes in order to work with hardware wallets and manage their accounts gracefully.  I'm not sure if all this work should be done on the node side or if it's a mix of Mist and node functionality.  For example, with myetherwallet the wallet connects to and handles the hardware wallet independently of the node which by analogy would suggest that Mist could handle that connection when it sees one, knowing to bypass the keystore.  Yet we see that geth has implemented hardware wallet connectivity at the node level.  So does that mean that it should be handled at the node level?  Not sure.  Either way, it would be exceedingly delightful to have some user friendly hardware wallet support where we can manage multiple accounts along with ERC20 tokens held within a given account.

**Comment by mrbrdo** [comment]
👍  I had too many problems with myetherwallet and would really prefer using Mist. I know both parity and geth support it already.

**Comment by woodydeck** [comment]
Yea, no hardware wallet means commerce can't take place on Mist. Crypto worms and trojans are far too common. Ethereum is especially vulnerable since the addresses have no checksum built in, a trojan could just simply rewrite an address that looks very similar to the one displayed on screen. 

Mist is great now for registering domains, but I wouldn't keep more than a couple Ether on it. I operate with the assumption my computer is compromised when it comes to crypto. I wouldn't be able to sleep at night without it.

Trezor is very easy to implement. It just takes a day's grind to go through the documentation, and maybe a week of hating life to sort it. I wish every site on the internet used Trezor for authentication. There's really no point to having passwords except for additional, moderate layers of security.

**Comment by tageeboy** [comment]
For what its worth, I would LOVE to see Ledger Nano S (and other hw wallet) functions included in future releases of Mist. Best ETH wallet out there, HW support would put it as "the ONLY ETH Wallet" as far as I am concerned.

**Comment by prusnak** [comment]
> Trezor is very easy to implement. It just takes a day's grind to go through the documentation, and maybe a week of hating life to sort it. I wish every site on the internet used Trezor for authentication. There's really no point to having passwords except for additional, moderate layers of security.

@woodydeck How can I help you with integrating TREZOR?

**Comment by prusnak** [comment]
JFYI TREZOR support was just merged into geth: https://github.com/ethereum/go-ethereum/pull/14885

**Comment by alexvandesande** [comment]
Implemented via geth

**Comment by prusnak** [comment]
Does all functionality requiring GUI work properly?

**Comment by KazWolfe** [comment]
As far as I can tell, there is no GUI support for Trezors yet. We have to manually talk to `geth` if we want to unlock the device or similar. Even then though, that seems to be iffy as of now.

**Comment by diidiiman** [comment]
The way I manage to get around is to unlock the wallet on MyEtherWallet with Mist closed, then open Mist and operate with Trezor wallet from there. (Although Mist in Light mode sometimes does not find it)
