### ISSUE TITLE
Had to reinstall due to bug that ate all my hard drive space up while syncing. Now don't know how to access my old account. I have both the keys for it but don't know how to access it

### ISSUE THREAD

**Issue by whiteundies** [ethereum/mist#2290]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment]
Hi, slow syncing is a problem and quite frustrating. Some recommendations:

- check your account's balance using http://etherscan.io
- make a backup of all account's keystore files via menu -> accounts -> backup -> accounts
- please check this troubleshooting guide on our wiki: https://github.com/ethereum/mist/wiki
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com if you need to make transactions in a hurry

If this didn't solve your issue, please follow these instructions and upload the node.log files:
- go to menu -> accounts -> backup -> application data
- zip and upload node.log and all other node.log.X files

In order to keep duplicated issues at minimum, let's keep this conversation at a single place, which will always be updated with latest syncing status: https://github.com/ethereum/mist/issues/3097
