### ISSUE TITLE
Is my money lost

### ISSUE THREAD

**Issue by Heleri** [ethereum/mist#2355]
I opened mist wallet on May 3, i can't recall if a entered with Testnet.
I did the back up and have the Keystore file with the files.
I transferred ETH from Kraken but they never arrived, did not see them in my mist wallet. The transaction is visible on etherscan.io
Renewing the program i lost the account.
How can i restore the old account using the backup files?
I opened  myetherwallet and the backup file does not open there?

**Comment by richardforrestbarker** [comment]
I opened a new wallet recently as well and several of my transactions haven't come through according to the GUI; however I can see the transaction on the blockchain though and the app is taking forever to load up all the blocks in the chain (running for 4 days straight now).

**Comment by sathishvj** [comment]
@richardforrestbarker as long as you can see the transactions on etherscan and it shows on your account, you can at least be assured it is there.  When the sync finally finishes you will see it in mist.  In the meantime if you want to use the ether you can still use MEW.

@Heleri what happens when you try to open it in myetherwallet.  I've not so far had an issue with opening the account json file on MEW.

**Comment by Heleri** [comment]
Thank you! I have only backup file (UTC) and then in MEW it said that the file is encrypted and requires password.
But I kinda remember that I did not made a password for first main account- is it possible?
I can see account value but cannot enter.

**Comment by sathishvj** [comment]
No it is not possible that you do not have a password for the account.  Mist/Ethereum-Wallet asks you for the password first before creating the account.  So maybe try the passwords that you might have created it with.

In case your issue is resolved, you can close this issue.

**Comment by Heleri** [comment]
I downloaded Mist again and if I launch application (I might have done this before it finished all syncs)  there is already Main account (etherbase)
, version 8.10., and there is possibility to send funds. (did not ask to create password) 
I think it might happened that way. Is it possible?
Controversial is that if I use this UTC file in MEW, then it asked password.

**Comment by sathishvj** [comment]
Mist will find the accounts based on keystore files already saved on your computer.  But to do any transactions (Send/Contract), then it will ask for the password.

MEW on the other hand, asks for the password in the beginning itself when you load the keystore file in the 'Send Ether/Tokens' tab.

**Comment by Heleri** [comment]
I just used main account (Etherbase) without password just for getting TO :address.
I clicked transfer ether and tokens and I choosed TO: address and transwered ethers to this address from kraken.
So I do not have password.....
I understand that you can suggest only 1 solution:
1. Download Mist ast version again and copy this keystore folder(or file) to Apdata/roaming/Mist/resources/.....

I kind of did this but did not work- I try to download Mist again.
First time I  deleted alla MIst folders I had in computer(exept keystore folder)
Should I do it now or it does not matter?
Roaming/mist...
Download/MIst
Roaming/Ethereum folder.

**Comment by sathishvj** [comment]
Like I said in my previous comment, Ethereum-Wallet will allow you to see your account without a password (address, balance, etc.), but it won't let you Send transactions.  Send-ing will require a password.  So, without the password it is a one way street - you can send eth but you can't take it out.

**Comment by Heleri** [comment]
Thank you for your help but I still do not clearly understand situation.
1. MEW- I cannot send because  needed password. If I generated account at Mist without pw  how can I send?
You wrote- you can send ETH but you can't take it out.
So how could I send ETH?
2. What about Mist wallet - would it be possibilites to open wallet or send  ETH ther?

**Comment by richardforrestbarker** [comment]
You did not generate the addresses without a password. Mist will not allow
it. You need to wait for the blockchain to be completely downloaded before
you can send any. If you have another copy of geth running on another
machine with a full copy of the chain then you can copy the blockchain from
that system to the Mist wallet.

No matter what though, you cannot not send ether from Mist without the
password used to create the address AND a full copy of the blockchain. Just
be patient, mist will get all the blocks eventually. It took my system 4
days to get the whole block chain - and that's after copying over the chain
from another system. So patience is required too. Trust me it'll work
eventually.

On Jun 11, 2017 11:16, "Heleri" <notifications@github.com> wrote:

Thank you for your help but I still do not clearly understand situation.

   1. MEW- I cannot send because needed password. If I generated account at
   Mist without pw how can I send?
   You wrote- you can send ETH but you can't take it out.
   So how could I send ETH?
   2. What about Mist wallet - would it be possibilites to open wallet or
   send ETH ther?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/mist/issues/2355#issuecomment-307646802>, or mute
the thread

**Comment by sathishvj** [comment]
Sorry, I misspoke.  I meant that you can receive ETH but you can't send ETH without the password.
