### ISSUE TITLE
Broken Computer - Is it possible to recover my eth on another device?

### ISSUE THREAD

**Issue by lukecti** [ethereum/mist#2361]
#### System information
``````
Version: `0.8.10`
OS & Version: osx
Node type: `eth/geth(default)`
``````
So my mac has died... I've had no luck of getting it back on.

Is there any way of recovering my Eth from my Ethereum wallet onto a new device?

**Comment by antonroos** [comment]
I would also like to know this answer

**Comment by Pac23** [comment]
What Op could do is incase his hdd wasn't the reason his mac died he can boot into linux using a live usb/cd and recover the keystore files.

**Comment by alexvandesande** [comment]
You need to have your private keys in order to access your account. If you do not have a backup, then you should take your machine to a Data recovery specialist, after a computer dies, the data is often accessible and they can find you the private key, by either booting it with another OS or connecting the disk in another machine. You're looking for a folder called "keystore".
