### ISSUE TITLE
My eth's do not appear in the wallet

### ISSUE THREAD

**Issue by c4rl05br** [ethereum/mist#2511]
Why do not my eth's appear in the wallet but appear in etherchain?

![eth](https://user-images.githubusercontent.com/10926393/27107307-c9cc4cc6-506d-11e7-8832-bffe6f06634a.jpg)

**Comment by evertonfraga** [comment]
Because you haven't synced with the blockchain yet. This is a process that it's usually taking from 4-20h, depending on your connection speed and I/O speed (SSD is much better than HDD for that task).

Your funds are safe, though. If you need to transfer funds anywhere now, I'd advice you to use a third-party wallet such as myetherwallet.com

I'll close this for now. thanks.
