### ISSUE TITLE
v0.8.10 is so slow...why the Ethereum Devs not taken this wallet problems seriously?

### ISSUE THREAD

**Issue by super83** [ethereum/mist#2514]
#### System information
``````
Version: `0.8.10
OS & Version: windows 10
Node type: `eth/geth(default)`
``````
With this 0.8.10 wallet, it took me over 3 days to sync my wallet non stop using the fast sync and deleting my chain data :(

Come on Devs, where is the new update...this current 0.8.10 is so slow to sync.
There so many people are having problems to sync with this new update 0.8.10, so why the devs don't take this wallet problems serious?

I'm a big fan of Ethereum since long time but i'm very frustrating with the wallet slow sync.
Ethereum is worth Billions now and today the adoptions is so much faster than Bitcoin, but sadly the Ethereum Devs still not making the wallet development as a priority :(

Come on Devs...make your wallet to have fast sync as a default, not just during first installed only.

PLEASE have more Devs to work on Ethereum Wallet, so we can have better & fast wallet !!!

**Comment by chris-stones** [comment]
Me too....
New to etherium... It took a few days to sync... but i thought that one long sync would be the end of it.
24 hours later, i tried to re-launch... 4,000 new blocks to download...at about 2 blocks per second.
Thats 30 minutes!!!

It seems, that if i want to spend etherium, i need to wait 30 minutes multiplied by the number of days since I last launched the app.

CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
Solid State Hard Disk.
8 Gig Ram.
GPU: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)  (3076 Megs, Unified)
Distro: Arch
Kernel: Linux  4.9.11-1-ARCH

**Comment by alexvandesande** [comment]
We are reviewing at old unanswered issues, sorry it took so long to reach yours, it's a long backlog.
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com)

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
