### ISSUE TITLE
Using ethereum mist wallet is a terrible experiencet, to me.

### ISSUE THREAD

**Issue by sinoda168** [ethereum/mist#2543]
When I used it first time, I got the hunch that I couldn't trust it totally. Why? It always takes me much time to wait for its opening (around 2 hrs for one day's lag). What if one day it stuck in the process of looking for peers, downloading blocks and never get into the wallet !?

The nightmare happened. I open the wallet today. The reminder appeared when the blocks' downloading almost finished. Please see as below:

![mist wallet shown error message](https://user-images.githubusercontent.com/29498571/27252436-058fc80c-5391-11e7-92aa-e5e99c10ba41.jpg)

Then I went to C:\user\use name\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked\geth
to open geth accordingly. And it disappeared in no time after appearing. What am I going to do with it.

Luckily, I closed it and opened it the third time, the wallet opened !!! Of course I got to withdraw the Ether inside immediately.  But here came problems again. The amount of Ether inside was sufficient, but couldn't be sent. Please see as below:

![mist wallet keep reminding insufficient funds](https://user-images.githubusercontent.com/29498571/27252559-04f0a2ce-5394-11e7-948d-7168a7665205.jpg)

So I started from withdrawing 0.2 Ether, 0.5 Ether, 0.3 Ether (didn't work), 0.2 Ether, 0.1 Ether (didn't work), 0.09 Ether, 0.009 Ether (didn't work), 0.008 Ether. Geeeeee....!!!

Aside from having sufficient amount (including gas fee) and it kept telling me I had insufficient funds, there was another reminder keeping showing up. Please see as below:

![mist wallet keep going wrong](https://user-images.githubusercontent.com/29498571/27252613-9db933da-5395-11e7-84aa-09e99ec1175a.jpg)

And now, the wallet starts re-sync form from scratch. How come? Please see as below:

![mist wallet restart syncing from scratch](https://user-images.githubusercontent.com/29498571/27252647-676d810e-5396-11e7-8b8c-80ddc8df16f5.jpg)

Luckily I didn't loose this 1 Ether coin in the wallet in the end. But it does scare me a lot to reuse it. To an average user like me, it is not that friendly.

**Comment by alexvandesande** [comment]
Thank you for the feedback, we are reviewing at old unanswered issues, sorry it took so long to reach yours, it's a long backlog. On the first issue: where you opening geth manually every time? It looks like an error on closing geth on the last time it was opened, so it might the wallet lost connection because of it. I'll keep an eye for such errors.

The second issue is about sync and we are working very hard to solve that.
 
This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com)

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097

Finally the third issue was about sending all your ether: in order to calculate gas and send it all, you can simply click the "send everything" and next time it would have calculated that for you.

Sorry for your bad experience.
