### ISSUE TITLE
I am missing tokens that I transferred to my wallet last night

### ISSUE THREAD

**Issue by georgesamman** [ethereum/mist#2590]
Is this due to the backlog caused on the network yesterday?  When will they come through?

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment]
Can you confirm that using a network explorer such as https://etherscan.io ?

**Comment by georgesamman** [comment]
The transaction isn't even showing up when I put in the ID but its gone from where I sent it.

**Comment by Jahriver** [comment]
Georgesamman, I am having the same problem. I am hoping it is just due to network congestion and that we will both eventually get our tokens.

**Comment by Yoelx** [comment]
Maybe this will help someone else. I thought I had the same problem, but turned out to be something else.
I transferred another currency than Ether (in this case TRST) and it didn't show up in my wallet, though the transfer was successful. It turned out I needed to select the CONTRACTS tab and click WATCH TOKEN to add the TOKEN CONTRACT ADDRESS of the TRST coin. Then it showed straight away. More info [here](https://github.com/bokkypoobah/TokenTrader/wiki/TRST-%E2%80%90-Wetrust#how-to-check-your-token-balance-in-ethereum-wallet--mist)

**Comment by evertonfraga** [comment]
As @Yoelx said, if you are using another token, then yes, you should add that token to the watch list.

But the network was really busy due to these ICOs that are happening. To check if your transaction went through, do this:

1. click on the transaction log at the bottom list of the wallet
![image](https://user-images.githubusercontent.com/47108/27436107-94de5d24-5734-11e7-9685-9a2ee8a80dd7.png)
2. Click on the link at the top of the modal.

You'll head to the etherscan, where you can check if the transaction has propagated to the network.

I'll close this for now, feel free to reopen.
