### ISSUE TITLE
Mist, Coinbase, buying ETH, WTF!?

### ISSUE THREAD

**Issue by dudevongregerz** [ethereum/mist#2636]
So I have Mist and it uses Coinbase to fund it via credit card. Does that mean I now have two accounts out there that are vulnerable?

1. Does the risky Coinbase account now also hold and allow control over my ETH?

2. Will the Coinbase purchase eventually show in my Mist Wallet?

3. Will the ETH that may end up showing in my Mist Wallet be the real and only location/control of my ETH?

**Comment by dudevongregerz** [comment]
Additionally, it has been about a half hour and the ETH purchase still hasn't shown up, anywhere.

Does all this super slow processing and huge ledger that has to constantly sync for every user totally nullify the value of any popular blockchain technology? Sure, you eliminate the middle man and assure an immutable ledger, but you add slow processing and an unwieldy constantly changing master file that everyone has to wait for. Think of all the sync'ing processing power and time associated with this ever growing ledger. It's like a snowball rolling down a ski slope or a man with an eating disorder ... eventually getting just to big to be of any practical use.

**Comment by sathishvj** [comment]
I do not really know how the Coinbase part works since it doesn't work in my geography.  But I'm going to make a few guesses ... 

* for 1) and 3) Ether sent to your account is going to only be accessible to those who have the keystore file and the password.
* for 2) The coinbase purchase should show in your mist wallet.  (provided the entire chaindata has synced)

**Comment by evertonfraga** [comment]
1) Coinbase **will not** have access to your ether once transferred. 

2) After a short time, Coinbase should transfer to your account. But it will only display in your wallet after syncing. Good news is that you can check it on https://etherscan.io/ Just put your account address on the website search.

3) Yes!  As long as you keep your Keystore + password safe, no one else will ever have access to them. Neither coinbase nor the wallet could steal your funds.

**Comment by dudevongregerz** [comment]
Thanks for your answers - very helpful. Yes, the Coinbase purchase eventually got to the Mist wallet. Evidently, there was a big backup at Coinbase due to too ETH transactions (dumps?) - this slowed the process down to take four hours before the Wallet showed the ETH.

Thanks for explaining that Coinbase only facilitated the purchase and does not hold or provide access to the ETH >>>> it only made the purchase and allocated the converted USD >> ETH to the public address provided.

Now on to the next hurdles/misunderstandings.

**Comment by sathishvj** [comment]
Can attempt to answer the 2nd part also.  With EthereumWallet/Mist the whole process looks unwieldy and large since you are running a full node.  This is kind of like running a full mail server.  You obviously don't have to do that and you can use a thin client that just connects to a remote service.  As with email, the tradeoffs will be there that the server and whoever runs it potentially has full access to all your communications/data.

'Slow processing' under heavy loads is a known problem in this project which is still in early development.  Future months/quarters/years should see this being addressed.  Similarly there are ongoing discussions/work on the size of the chaindata and how the authenticity of a transaction could be verified without having the entire chain available.  Your questions are therefore valid, and all I can say is welcome to it all.  :-) 

Apart from those, processing is actually very fast for certain functional areas (but certainly not yet for all).  Where financial transactions across countries would take days, ethereum can do it in a dozen seconds (not including confirmations).  Even local transactions won't require separate processes of sale and then settlement later (minutes, hours, or days) and will speed that up.

**Comment by dudevongregerz** [comment]
Thanks for your insights Sathishvj! Sounds like you're optimistic that the issues will get resolved (speed and chaindata size) while recognizing that the current state is already faster in many use cases.

Not sure how big a ledger would get if it were to hold the entire history of *everything*, or even a fraction of it. At the same time, if everyone holds (or has some reliable remote access) to the entire blockchain, in their lifetime, they may only query/change a fraction of a fraction of a fraction of the ledger. It's like carrying every book ever written around in a backpack and only reading the introduction of one.

I once heard someone say that there will be a "chain-of-chains". I guess this would be like a Google of chains (except decentralized). I'm guessing this would give individuals/bots/smartContracts specific chain+access+sync of smaller as-needed parts of the world of blockchains - only the books you will read/need appear in your backpack as-needed.

Anyway, just trying to get my brain around all this. ANY feedback, comments, or corrections to my thinking is much appreciated.
