### ISSUE TITLE
Look for a system wide installation of geth or eth

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#264]
I'm maintaining the mist packages for ArchLinux and need some guidance.

Starting up mist always tries to start a geth node in `${pkgdir}/usr/share/${pkgname}/resources/node/geth/geth`, but usually people install and maintain their own version of geth or eth in their system, e.g., `/usr/bin/geth`...

Would it be possible that mist checks whether any suitable client is available in `$PATH` before starting it's own node?

Discussion from [AUR](https://aur.archlinux.org/packages/mist/):

> For some odd reason /usr/share/mist/resources/node/geth/geth has no execution privileges after installation with pacman. This is why I'm getting the same error as @notungx when I run mist. Adding the privilege solves the problem.
> 
> The file is not marked as executable probably because it's unpacked from a .zip achive, which has no concept of access privileges. I see that PKGBUILD explicitly sets privileges for libnode.so and Ethereum-Wallet. It should be doing that to geth as well. Please add this line at the end of package():
> 
> ```
> chmod 755 "${pkgdir}/usr/share/${pkgname}/resources/node/geth/geth"
> ```
> 
> For a moment I thought that maybe lack of exacutable flag is deliberate - after all geth is an optional dependency here. But no - mist tries to use its own copy of geth even if you install the geth package from AUR. It does not seem to detect /usr/bin/geth. The dependency is misleading and should be removed.
> 
> The error and the dependency make it look as if geth wasn't bundled with mist until very recently. Is this what happened here? 

And:

> I get the following error after executing mist:
> 
> ```
> CONNECT to IPC PATH: /home/santi/.ethereum/geth.ipc
> CONNECT to IPC PATH: /home/santi/.ethereum/geth.ipc
> NODECONNECTOR ERROR { [Error: connect ECONNREFUSED /home/santi/.ethereum/geth.ipc]
> code: 'ECONNREFUSED',
> errno: 'ECONNREFUSED',
> syscall: 'connect',
> address: '/home/santi/.ethereum/geth.ipc' }
> Node type: geth
> Network: main
> Start node from /usr/share/mist/resources/node/geth/geth
> Stopping nodes...
> Starting geth node...
> UNCAUGHT EXCEPTION { [Error: spawn EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
> Stopping nodes...
> ```
> 
> In my laptop works just executing mist without the need of executing geth first... any ideas?

Should I make the shipped geth binary executable for now? I would prefer using the system wide installation of geth.

**Comment by frozeman** [comment]
You're absolutely right with the system with version.
Though there is the problem that the node which is installed system wide might be outdated and mist requires a newer version (for API changes etc). If you can enforce a version in your package that would be fine.

I'm not on linux and not so firm on linux packages.

If you can help me checking for a system wide installed version first, would be awesome.
The start code for the nodes is here: https://github.com/ethereum/mist/blob/master/modules/ethereumNodes.js#L176-L183

This should do the job: https://github.com/springernature/hasbin

I can  add this, but would like to have a discussion on shipped vs. installed binary.
I may have to check the node version before i start the node (arghhh more complexity)

**Comment by 5chdn** [comment]
I can use the shipped binary if the version is important. Does that mean you will also in future releases bundle the geth into mist releases? Is geth also available if I build from source?

**Comment by frozeman** [comment]
geth and eth is already in the mist releases, under resources/node..
but not for all versions, (e.g. not for linux 32 bit)

**Comment by cameel** [comment]
Hi @frozeman, I'm the one who commented on it in AUR :)

> geth and eth is already in the mist releases, under resources/node..
> but not for all versions, (e.g. not for linux 32 bit)

What's the reason for that?

> If you can help me checking for a system wide installed version first, would be awesome.
> The start code for the nodes is here: https://github.com/ethereum/mist/blob/master/modules/ethereumNodes.js#L176-L183
> 
> This should do the job: https://github.com/springernature/hasbin

I have originally suggested detecting `geth`, but now that I think about it, it's more conventional for Linux packages to accept full paths as compile-time options. This prevents attacks that rely on putting stuff in user's `PATH`. Also, I think that most experienced Linux users would expect it to work that way.

Another way to do it would be to keep the hard-coded default in the code but add a command-line option to override it. The downside is that the packager would have to move `/usr/bin/mist` executable and replace it with a wrapper script that passes it the path appropriate for the system.

In my opinion both of these will make more sense than checking `PATH` at runtime, because the choice between the bundled and system-wide `geth` is packager's decision. Changing it would, logically, change package's dependencies.

> I may have to check the node version before i start the node (arghhh more complexity)

I'd leave that to the package manager in each specific distro. It's a system built to deal with that particular problem after all. Just document the required version in the release notes. To do it robustly you'd have to either rely on version hard-coded in `geth` or interact with every package manager directly. And it would be pretty limiting for distro maintainers unless you want to specify a whole range of working versions - but that's a lot of unnecessary effort to test them all.

That being said, some sanity checks on startup are still a good idea. Just not simple version checks. If there's a way to check for presence of specific functionality or incompatibilities, that would be of much more value in my opinion.

> > > The file is not marked as executable probably because it's unpacked from a .zip achive, which has no concept of access privileges. I see that PKGBUILD explicitly sets privileges for libnode.so and Ethereum-Wallet. It should be doing that to geth as well.

While we're talking about packaging, what do you think about switching to using `.tar` archives for linux packages? Specifically `.tar.gz` or even `.tar.xz` which offers much better compression. `.zip` has two issues:
- It can't store access permissions. After you unpack it, you have to manually find executables and change their flags. If the packager misses one, the application won't start (it's actually the issue that started this whole discussion).
- It does not store the character encoding used for file names. And the encoding used on Windows is usually not UTF-8, but one of the ancient ASCII-like code pages. If you're on Linux and ever have to unpack a file created on a non-English edition of Windows, you'll feel the pain. Especially if you don't know the original language :) Of course it's best not to use diacritics in file names and I think you don't right now but if you ever want to, it's a limitation.

**Comment by 5chdn** [comment]
While we talk about packaging! Why is there an absolute version string in the build path? This causes really headache. For instance, after I build `mist-git-0.5.1.r25.g661f46a` from source I will find executables in `mist/dist_wallet/Ethereum-Wallet-linux64-0-5-2`

Note the offset, there seems to be a 0.5.2 release upcoming, but the tag still refers to 0.5.1 and therefore it's almost impossible to create packaging scripts which automatically determin the binary path.

**Comment by hiddentao** [comment]
What about searching for an appropriate system-wide geth, and if not found then downloading the required version from the web? Thus, at startup Mist would first do this (and pop up a "downloading progress" window if necessary). This allows for system-wide geth usage whist also removing the need to bundle geth within Mist and thus have to keep it up-to-date with releases.

**Comment by luclu** [comment]
Could we:
 - probe `/usr/local/bin/` / `/usr/bin/` for geth
 - extract the `VERSION` string  from the cli help screen
 - compare and decide which on to start 

Also we could warn about an outdated system-wide version - but only once per version.

**Comment by 5chdn** [comment]
For ArchLinux, you could do `$(which geth) version | grep -m1 "Version" | cut -d'-' -f1 | awk '{print $2}'`

Long example:

     ~ $ which geth
    /usr/bin/geth
     ~ $ /usr/bin/geth version
    Geth
    Version: 1.4.10-stable-5f55d95a
    Protocol Versions: [63 62]
    Network Id: 1
    Go Version: go1.6.2
    OS: linux
    GOPATH=
    GOROOT=/usr/lib/go
     ~ $ $(which geth) version
    Geth
    Version: 1.4.10-stable-5f55d95a
    Protocol Versions: [63 62]
    Network Id: 1
    Go Version: go1.6.2
    OS: linux
    GOPATH=
    GOROOT=/usr/lib/go
     ~ $ $(which geth) version | grep -m1 "Version"
    Version: 1.4.10-stable-5f55d95a
     ~ $ $(which geth) version | grep -m1 "Version" | cut -d'-' -f1
    Version: 1.4.10
     ~ $ $(which geth) version | grep -m1 "Version" | cut -d'-' -f1 | awk '{print $2}'
    1.4.10

Which, Grep, Cut, Awk should be all the same in Linux environments. Give it a try with Ubuntu for example.

**Comment by luclu** [comment]
ongoing PR: https://github.com/ethereum/mist/pull/1047

**Comment by luclu** [comment]
@5chdn this feature is be implemented in the latest releases.

**Comment by odanoburu** [comment]
is this already implemented? I'm having trouble having mist find my geth installation, as per my [question](https://ethereum.stackexchange.com/questions/21707/connect-mist-to-geth-running-in-private-testnet) on SE.

I **am** specifying the ipc path, and even the path to geth, and after several tries changing several parameters I can't have mist connect to my geth instance.
