### ISSUE TITLE
Mist 0.5.1 transfer all ether out of an account

### ISSUE THREAD

**Issue by cap2002** [ethereum/mist#280]
Please see submitted image.

https://i.imgur.com/5o1ik4B.png

**Comment by frozeman** [comment]
We will improve the display of the values for the next release. The problem is that as safety we add 100k gas to the estimated gas price, which then makes it over the amount you calculated (amount + fee) and shows the error.
if you change the provided gas to be exact 21000, it should go through fine. 

But we will then show that the transaction may have been out of gas, as we take gasProvided and compare it to the gas used.

This are "restrictions" by the EVM.

if we would set the gas Amount perfectly there are chances that the estimate was wrong, as the chain changes and you couldn't move the money.

I will try to find a good solution for that.

**Comment by cap2002** [comment]
Thank you. You are doing excellent work - I love this community!

**Comment by frozeman** [comment]
In the latest #wallet branch i added a send all button.
![screen shot 2016-03-08 at 11 44 26](https://cloud.githubusercontent.com/assets/232662/13630722/12979e18-e5e1-11e5-8363-7dd0dbf86995.png)
