### ISSUE TITLE
Funds have dissapeared

### ISSUE THREAD

**Issue by ValKos** [ethereum/mist#2802]
Please, explain me how to recover my funds that had been in my wallet, but after acidentely removed folder "ethereum" in appdata (I removed that folder, silly me) funds have gone.
In spite I have some UTC files, I haven't been able to recover my eth money on new syncronized Mist. Even though I copied UTC files in new keystore folder.
Please, help. I completely newby in cryptocurrency.

``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by evertonfraga** [comment]
Ok @ValKos, i'm sorry for your experience. 

Mist uses a full ethereum node. That helps the network to keep safe and fluid. However, it's becoming a pain for normal users, as you'll have to download the whole blockchain just to get started. 
In order to check your funds and to transact, you can use http://MyEtherWallet.com service. Watch out on the internet, because there are wild phishing campaigns about online wallets, but this one is reliable. 

There you'll upload your UTC file, unlock it with your password, then you will have access to your funds.

**Comment by sathishvj** [comment]
You can also check if your funds are available at: etherscan.io/address/0x... put your address at the end.

Then, as mentioned in the previous comment, you can use https://www.myetherwallet.com to transact until your full node is synced.
