### ISSUE TITLE
Can i delete the blockchain lokal without loose my coins?

### ISSUE THREAD

**Issue by BoBBer446** [ethereum/mist#2870]
my wallet does not sync since a few days ago. So i cant send or receve coins -.-

V ery BAD! can i delte all to start Syncing new?

**Comment by M41** [comment]
You don't have to delete it if you have enough space.  It's better to re-name the blockchain folders so you don't make any mistakes.  Then run "Geth --fast" so it starts sync from the beginning and creates new folders because you changed the folder names. 

*** But be careful!  keep Keystore folder safe and make backup copies. Your private keys are in JSON files in keystore folder. Do NOT delete keystore folder:  Mist > Files > Backup > Accounts   - this takes you to Keystore folder.  Never delete.  Keep it safe!!!!

**Comment by BoBBer446** [comment]
if i do that, i habe 0 eth ....? :/

**Comment by BoBBer446** [comment]
here i write the long answer:
https://github.com/ethereum/mist/issues/2874#issuecomment-319904958

**Comment by BoBBer446** [comment]
Solved!
https://github.com/ethereum/mist/issues/2874#issuecomment-319904958
