### ISSUE TITLE
keystore dir different on ubuntu and win

### ISSUE THREAD

**Issue by winsvega** [ethereum/mist#288]
when I choose backup Account on windows 
it opens 
/ethereum/keystore

but on Ubuntu it just opens 
.ethereum/

**Comment by luclu** [comment]
Mist (Ethereum Wallet) configuration are stored in OS-specific user folders as in:
https://github.com/ethereum/mist#installation

The folders you related to are the OS-specific user folders of https://github.com/ethereum/go-ethereum

Though this is supposted to work this way as of the OS-specific folder structure.

**Comment by luclu** [comment]
Electron's [docs](http://electron.atom.io/docs/all/#appgetpathname) suggest the [current](https://github.com/ethereum/mist/blob/4f8614c3352cec6d5a7f4284d2d625a16ea0061c/modules/menuItems.js#L84) use of `setPath('home')`.

But this seems to point to the generic `/home` folder in Unix-like distros instead of the user's home folder.
Strangly adding some nested foldername like `/home/foo` or `home/.ethereum` traverses into the user's home folder.

In this fashion `home/.ethereum/keystore` points to `.ethereum`.
Which is weird...

**Comment by luclu** [comment]
issue still persists as of electron 1.0.1.
