### ISSUE TITLE
ICN transfer missing

### ISSUE THREAD

**Issue by arod71** [ethereum/mist#2928]
Hi Guys,

I'm a noob and would really appreciate a little guidance. I sent ICN to the preexisting Iconomi wallet in version 0.9.0 in 12 hours ago. Still not arrived. If it is a blockchain sync issue, how long does it take to fully sync? It has taken over 2 days to get 4,148,762 blocks. Do the tokens just sit out in virtual world until the sync has fully completed?

Thanks!
Alan  

``````
Version: `0.9.0`
OS & Version: WIN10 Pro 64
Node type: `ETH`
Number of blocks synchronized: 4,148,762
``````

**Comment by garretlaxton** [comment]
Try searching your address or tx# on http://etherscan.io

**Comment by arod71** [comment]
Thanks for the guidance! I did that and the transaction is in there for the ICN, so it has registered in the system and the address checks out with the ICN wallet in my desktop Ethereum Wallet. 
![empty icn wallet](https://user-images.githubusercontent.com/30955691/29250741-7b7fd086-800d-11e7-94d7-2f27f3663417.png)
![etherscan io confirmation](https://user-images.githubusercontent.com/30955691/29250742-7b821738-800d-11e7-89e2-4c87c25f8c11.png)

**Comment by garretlaxton** [comment]
Your iconomi doesn't show as Ether if that's what you're wondering, I can see you have 104 iconomi tokens just make sure to backup that wallet.

**Comment by arod71** [comment]
But how then to move the ICN back out? No ether = no gas?

**Comment by evertonfraga** [comment]
Hi @arod71, 

if you want to check your ICN balance from within Ethereum Wallet, you should first watch that Token out. Otherwise, it wouldn't be able to automatically detect it. 

Please head to Contracts tab > Watch Token

having the chain synced, just type ICN on the token contract address field, as follows: 

![image](https://user-images.githubusercontent.com/47108/29391933-fcd8967a-82d0-11e7-9dde-a9cdc4a92693.png)

Then confirm it, and check on your account if balance matches.

**Comment by arod71** [comment]
Awesomeness! Thank you big big!
