### ISSUE TITLE
Cannot transfer between accounts using AlethZero as the back-end

### ISSUE THREAD

**Issue by destenson** [ethereum/mist#294]
I am attempting to transfer some ether between two of my accounts, which are imported and accessible with AlethZero (v1.2.1) on Windows 10. I have AlethZero in the background & launch Mist (0.5.1 (beta 9)). It sees all my accounts from AlethZero as expected. When I try to deposit to one from another, it pops up the confirmation screen & asks for a password. When I enter it, it clears the field and does nothing until I select the cancel button, at which point Mist says "Transaction Denied" in a red box in the lower right corner. In AlethZero, I have "Confirm Transactions" unchecked, but it's behaving the same regardless.

The same transfer occurred successfully when using AlethZero to create the transaction directly.

I have done this same procedure before in recent previous versions of Mist & AlethZero, but it seems to be broken in this release.

**Comment by luclu** [comment]
Hi @destenson is this issue still occuring as of version 0.7.2?

**Comment by destenson** [comment]
@luclu It was still happening with the latest version I tried, 0.6.1. I will try with 0.7.2 and get back to you shortly.

**Comment by destenson** [comment]
@luclu, yes, this is still not working for me with 0.7.2.

**Comment by luclu** [comment]
@destenson the eth backend is currently broken https://github.com/ethereum/mist/issues/607 as there are several unresolved bugs. We we give it some love during the next versions. Most likely your problem has already been fixed by the IPC-refactor in version 0.7.5 - still eth's connection isn't without problems.
Watch out for the changelogs. In the meantime you can copy the keyfiles to geth's keystore.
I will close this for now.
