### ISSUE TITLE
Ethereum Wallet wont sync. Been trying to load it for 4 days. It starts and then stops. Any way to fix this? 

### ISSUE THREAD

**Issue by Reiz45** [ethereum/mist#2973]
Version: Win 64. Geth `0.9.0`
OS & Version: windows
Node version: `geth 1.6.5` 
Number of blocks synchronized: 0
```
I receive an Ethereum Node Connection error on startup a lot and the wallet wont ever sync. 
Sometimes after I restart my computer it will launch and work for a few minutes, but then it stops syncing. I close it out and reload but the same thing. I've spent 4 days starting it and stopping it and still can't sync it. I had this issue with 0.8.10 so I downloaded 0.9.0... Same issue. 
Also, I have ETH that was transferred from GETH mining that is not showing up in the wallet because it wont sync. 
<!--






 -->

**Comment by nazimran** [comment]
Unfortunately there is no way to solve the problem right now.
I've tried downloading wallet data for a month  But i failed.
 Do not tired yourself . Sit back and pray. Maybe a help comes. I hope you have a god And it saves us from this trouble. God be the help of all of us.

**Comment by darinkes** [comment]
Also trying to use the Ethereum wallet, but syncing doesn't seem to finish ever.
Already removed chaindate several times, started geth with fast-syncing serveral times.
Syncing is jumping back and forward, 80% -> 2% -> 20% -> 99% and so on.

Made it to 102 Blocks (~99%) but then still syncing forever.
Will syncing ever finish? Is this expected behavior?

**Comment by wtfiwtz** [comment]
See this thread: https://github.com/ethereum/go-ethereum/issues/15001
