### ISSUE TITLE
sending ether to new ether wallet problems

### ISSUE THREAD

**Issue by geestar** [ethereum/mist#3007]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by joshksas11** [comment]
This was a hack. Geestar has stolen my single etherium from my etherium wallet.  Is there any way to recover?. I am just getting this email because I finally re-gained my email accounts from him. It is likely that all of his trades are hacks.  The United States fbi and united states secret service has been made aware of his hack of my eth and btc. Please hey back to me.  I can confirm my identity in any way applicable. Please get back to me.  ThanksJosh kramer


Sent from my Sprint Samsung Galaxy S8+.
-------- Original message --------From: geestar <notifications@github.com> Date: 8/30/17  7:40 PM  (GMT-05:00) To: ethereum/mist <mist@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [ethereum/mist] sending ether to new ether wallet problems
  (#3007) 
Closed #3007.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ethereum/mist","title":"ethereum/mist","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ethereum/mist"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #3007."}],"action":{"name":"View Issue","url":"https://github.com/ethereum/mist/issues/3007#event-1228610051"}}}
