### ISSUE TITLE
Sent real Ethereum to account on Rinkeby network

### ISSUE THREAD

**Issue by Pink-Devil** [ethereum/mist#3009]
As told in the title I didn't know I was on a network that didn't accept real Ethereum, as seen here I sent about 0.5 Ether https://etherscan.io/address/0x97a26cc7588d881143e1871bf95a8fd6946c9970
Can I please get the Ethereum back if possible to another working Ethereum address?

**Comment by domibarton** [comment]
Hi there. 

I think it was `0.05 ETH` rather than `0.5 ETH`. And I'm sorry to inform you that you can't have your money back, because that's not possible that way! The only way to get back your money, is to "find" the owner of the wallet / address (if there's one) and ask him… and that's near to impossible ;)

I know it doesn't help, but you just learned the hard way what can happen in the worst case. Thankfully, it was only `0.05 ETH` (approx `USD 20`).

Cheers
Domi

**Comment by Pink-Devil** [comment]
I am the owner of the address, I use nanopool for my mining and it deposited to my address and it doesn't show up in my Mist Rinkeby network account

**Comment by Pink-Devil** [comment]
Okay I solved it by using myetherwallet to send the transaction instead

**Comment by evertonfraga** [comment]
@domibarton, please don't spread misinformation. 

ethereum accounts are just key pairs (public and private), and they work in every possible network. Just move your keystore (UTC file) to the desired `network/keystore` directory, and you can move funds with Mist/EthereumWallet.

**Comment by domibarton** [comment]
@evertonfraga sorry, I've misunderstood the question an thought he sent ETH to a wallet which is not his… 

@Pink-Devil sorry mate!
