### ISSUE TITLE
New Geth 1.7.0 is the worst yet

### ISSUE THREAD

**Issue by powpig** [ethereum/mist#3055]
- [Yes ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `9.0.0`
OS & Version: Windows 10
Node version: `geth 1.7.0` 
Number of blocks synchronized: 4268805   Over 20K remaining
```
I uninstalled the old Geth 1.6.7 and downloaded and installed the new 1.7.0.
I was able to get through about 2000 Blocks per 24 hour period with the old Geth 1.6.7.
I opened the new Geth 1.7.0 directly and let it run for 6 hours, it only got through 333 Blocks.
I closed it, re-synced the time on my system clock and opened it again.  It just took 34 minutes to download 10 Blocks.
Back to the drawing board guys, this Geth 1.7.0 is garbage!  The worst Geth yet.

**Comment by wtfiwtz** [comment]
See https://github.com/ethereum/go-ethereum/issues/15001

**Comment by RiverRhine** [comment]
**Spent ~4 days testing on a decent system: We probably _have_ a problem with GETH  Megara (v1.7.0)** 

I'm using GETH and Mist from the beginning on. Geth and Mist usually worked fine for me since they exist. But my local blockchain grew up to ~227GB with ~125,630 ldb files over the last ~1,5y and I wanted to sync a fresh copy now. 

**The good:** GETH (0.7.1.) works on that old large chain with no problems at all!
**The bad:**  It simply won't sync (from scratch). Tested all "tricks" I found around here, but it **wont** finish syncing (details below) 

**Test machine: W7x64, 32G RAM, 8Core, 1TB SSD**
No RAM problems, no network problems (6MBit). 
I tryed several starts from scratch (with empty chain folder C:\Users\XXX\AppData\Roaming\Ethereum\chaindata). 

**Some experience and details from my last test:** 

(Not starting sync through mist but from console)

**geth.exe  --fast --cache 4096**
Node starts ok in fast mode:
![grafik](https://user-images.githubusercontent.com/32365896/30976819-152a301e-a476-11e7-84d8-34ce2a29a16c.png)

![grafik](https://user-images.githubusercontent.com/32365896/30976701-bf42673e-a475-11e7-83cf-3a6a178c9320.png)

... after running 10h everything is still fine
![grafik](https://user-images.githubusercontent.com/32365896/30976789-fc920af4-a475-11e7-97b8-b6aa2560f7c5.png)

![grafik](https://user-images.githubusercontent.com/32365896/30976991-8735821c-a476-11e7-8e1a-fae26a6b72cd.png)

![grafik](https://user-images.githubusercontent.com/32365896/30977212-24e656d0-a477-11e7-8751-ca2433a36809.png)

... so we nearly ran up to the last (current) block, but now it only "Imported new state entries". **Just ~250 blocks missing** (compared to [www.etherscan.io](url))

... waiting some more time but the LOG shows no new entries, and no files are touched by geth anymore:

![grafik](https://user-images.githubusercontent.com/32365896/30977421-c4f1f2d8-a477-11e7-981c-e21377223acc.png)

Now fired mist (v0.9.0) and "Launch Application" just to see whats showing up there:
![grafik](https://user-images.githubusercontent.com/32365896/30977578-406be37e-a478-11e7-91b6-0f70d14c1308.png)

**Status:** No blocks added and bad account values shown. Hanging at 99% blocks.

**(Q: Is anybody here who waited maybe another ~2 days in this state an _was_ successfull?)**

Now stopping GETH with ctrl-c. + shutting down Mist. Last LOG entry is now:
![grafik](https://user-images.githubusercontent.com/32365896/30977824-0d72c036-a479-11e7-9349-10b9d0125a71.png)
That means there where no LOG entries any more for some time.

Restarting GETH, "just in case" ;-) :
![grafik](https://user-images.githubusercontent.com/32365896/30978232-39232be8-a47a-11e7-94c1-ef92bcea4a0c.png)

Have been here before : Never ending "Imported new state entries" ...
Giving up for now.

**My conclusion:** 

- GETH is currently not syncing from scratch here
- No chance to sync without SSD (Disc IO was crazy! )
- Newcomers will be probably irritated by this "user experience"

I finally installed parity and was fully synced (in warp mode or so ) in ~2,5h? Imported the mist wallets. Works like a charme. (I never touched parity before ...)

For now my 227GB GETH chain is syncing fine and I will keep it alive until there is a solution for this hassle. Well, that's not a pretty solution.

Sorry for the lengish post, but maybe it's usefull to someone else having similiar trouble.
This is not meant as a rant at all. I appreciate all the work done here!

Thank you.

**Comment by wtfiwtz** [comment]
@RiverRhine you need to look for these log entries: "Imported new chain segment" - these are getting starved through the network. If you disconnect and reconnect from the network, you might get some more diverse peers that have these segments.

You also need to be on geth 1.7.0 as there was a change from block 1.7M onwards... see https://github.com/ethereum/go-ethereum/issues/15185

It gets there eventually, but with some persistence.

**Comment by powpig** [comment]
"It gets there eventually, but with some persistence."
-----
I keep hearing this but I'm having my doubts.

Been running Geth virtually non-stop since early Aug, (always updating with the newest release), that's almost 2 months straight and I just keep falling further behind, currently about 32K blocks behind and not gaining.

The new Geth 1.7.0 has sped up since I first posted above 10 days ago,  I've downloaded 4672 in the last 48 hours, so just less than 100 blocks per hour.  At this rate it'll take me almost 2 weeks just to catch up to where I could sync today.  By then, I'll be who knows how far behind.

I was able to sync back in July without too much trouble but something has changed since then.

**Comment by wtfiwtz** [comment]
```
geth --cache=2048 console

> admin.addPeer("enode://111767f1b1f7e8047c61c6f6daccbe6e16ee5b81034b492d756869d5994db052b6aaea701b7c57a5093df96a2eed2a2396543614f9a227a760eb50d0f3eb770f@210.84.23.51:30303")
```

Try that... I'm downloading now and am only 5000 blocks behind (and catching up fast)

**Comment by powpig** [comment]
Thanks for the suggestion wtfiwtz.
Gave that a try and got only slightly better results
Ran it for 12 hours and downloaded 1417 blocks
I also noticed that not every block got downloaded with your "fix"
As you can see, block #s 4292271 & 4292277 did not get "imported".  Any explanation why?
![gethsnip](https://user-images.githubusercontent.com/29794420/31024279-64eb593e-a4f3-11e7-9f42-950193c6a90b.JPG)

**Comment by evertonfraga** [comment]
> admin.addPeer("enode://111767f1b1f7e8047c61c6f6daccbe6e16ee5b81034b492d756869d5994db052b6aaea701b7c57a5093df96a2eed2a2396543614f9a227a760eb50d0f3eb770f@210.84.23.51:30303")

hi, @wtfiwtz. Is this a special peer?

**Comment by evertonfraga** [comment]
@RiverRhine that's such a great write-up!

@powpig keep in mind Mist and Geth are related projects, but they are not the same. For issues with geth, please refer to their repository: it'll be easier to troubleshoot your problems.

https://github.com/ethereum/go-ethereum

**Comment by wtfiwtz** [comment]
@evertonfraga no it was just my machine, which caught up to the latest blocks pretty quickly... unfortunately I couldn't keep it running indefinitely.

**Comment by 01GOD** [comment]
Pfff...sadly ethereum is a sad pile of cr@p and seems to be an obvious scam. Years of preparation to launch it were possible, and to make it great BEFORE launching the platform...a single skilled engineer could have made it GREAT...yet ethereum sadly seems to be cr@p...at least the tools are. "Node needs to sync" every f'ing day and every time any eth cr-app is opened. Yet, none of them ever seem to finish.

**Comment by 01GOD** [comment]
I think the ethereum blockchain is rigged to be difficult to fully download. Hiding something.
