### ISSUE TITLE
stand by on "ethereum node connected" with mist0.91

### ISSUE THREAD

**Issue by stbregeon** [ethereum/mist#3101]
hello,
since this mornig, I use Mist v0.9.1, with Light Client integration (beta).

when i use it for the firt time, this morning, evry thing is ok.  synch and balances was ok.

i.m out of my wallet

and now when i want to go into my whallet, i c'ant.  i'm stuck on the window "ethereum node connected".

(when i launch geth console, synch restats normelly)

how i can unlock the ethereum program ?

regards

**Comment by stefangordon** [comment]
Deleting your `geth/lightchaindata` directory and restarting client might work - this solved for me.

**Comment by ericjarvies** [comment]
On OS X, deleting  ```lightchaindata```  did not solve the main blockchain sync problem.

In fact, it is only possible to see your wallet balance using the **Light Client integration (beta**), _obviously_ because that **remote** blockchain is valid ... unlike the **local** blockchain, which seems not to be **importing new chain segments** correctly (_if at all)_.

Eric

**Comment by arseniy12345555** [comment]
I have the same problem, stuck on 'node connected' on mac...
