### ISSUE TITLE
Figure out the money 

### ISSUE THREAD

**Issue by EmperorLucifer666** [ethereum/mist#3106]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by ericjarvies** [comment]
To ease your mind, the problem is not with your personal wallet, i.e.- your ETH balance is still there (safe).

If you look at your node.log file, you will -likely- notice the last (_most recent_) entries are errors (e.g.- **CRIT**, **WARN**, etc.).  A _healthy_ node.log file should contain multiple '**INFO Imported new chain segment**' entries towards the end (_most recent_).

Eric
