### ISSUE TITLE
went off while downloading plockchain

### ISSUE THREAD

**Issue by Wazzzzup** [ethereum/mist#3232]
Hello! 

I started using your wallet. While it was downloading blockhain my comp switched of (problems with electricity). After I switched the comp the Mist was working. How can I check did it finish download and if not how can I finish it?

**Comment by alexvandesande** [comment]
We are reviewing at old unanswered issues, sorry it took so long to reach yours, it's a long backlog.

You can check the status on either the top bar (on the wallet) or in the lower left (in Mist). It should say something like this:

<img width="73" alt="screen shot 2018-03-05 at 4 55 50 pm" src="https://user-images.githubusercontent.com/112898/36996651-17d0ff36-2096-11e8-8e80-40c0d7361ee2.png">

Showing how much time has elapsed since the last block. If it's days or hours, then it's not in sync.
