### ISSUE TITLE
No etherbase set and no accounts found as default

### ISSUE THREAD

**Issue by douglasdeodato** [ethereum/mist#3276]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: Mist and Ethereum Wallet 0.9.2
OS & Version: windows10 64
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

I did download almost the whole chain, was few blocks left, so I decided to click in testnet to open the wallet.

and after click in test net to open the wallet I start get this error, please how to fix this?

now my wallet it is not working so pretty annoy after spend 7 hours downloading the bblockchain. :(

=============== Nov 12, 2017 (GMT) ===============
11:23:27.928822 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
11:23:27.992825 version@stat F·[5 104 1095 7601 5495] S·28GiB[542MiB 208MiB 2GiB 14GiB 10GiB] Sc·[1.25 2.09 2.10 1.53 0.11]
11:23:27.996825 db@open opening
11:23:28.046843 journal@recovery F·1
11:23:28.051833 journal@recovery recovering @71703
11:23:28.078955 version@stat F·[5 104 1095 7601 5495] S·28GiB[542MiB 208MiB 2GiB 14GiB 10GiB] Sc·[1.25 2.09 2.10 1.53 0.11]
11:23:28.174004 db@janitor F·14305 G·3
11:23:28.174004 db@janitor removing table-71705
11:23:28.175004 db@janitor removing table-71706
11:23:28.176005 db@janitor removing table-71707
11:23:28.176005 db@open done T·179.1799ms
11:23:28.181004 table@compaction L2·1 -> L3·4 S·7MiB Q·128184777

AppData\Roaming\Ethereum Wallet
node file says:

WARN [11-12|12:14:33] No etherbase set and no accounts found as default 
INFO [11-12|12:14:33] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9
INFO [11-12|12:14:33] Allocated cache and file handles         database=E:\\BLOCKS-COIN-2\\ethereum-blockchain-nov-2017\\geth\\chaindata cache=1024 handles=1024

node.log

WARN [11-12|11:23:27] No etherbase set and no accounts found as default 
INFO [11-12|11:23:27] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9
INFO [11-12|11:23:27] Allocated cache and file handles         database=E:\\BLOCKS-COIN-2\\ethereum-blockchain-nov-2017\\geth\\chaindata cache=1024 handles=1024

![error](https://user-images.githubusercontent.com/993318/32698500-0f7eb06c-c79f-11e7-852b-bca67355895f.png)

**Comment by rannmann** [comment]
I ran into this too.  I deleted my data directory which fixed it, and made sure to enter a password after switching to rinkeby.  From the behavior I saw, I believe you only have so many seconds to enter a password and if you don't set one in time, it breaks.  Then it crashes before you can do anything every subsequent launch, until you delete the data dir.

**Comment by bford21** [comment]
@rannmann I'm seeing this issue as well. Where is the data directory located that you deleted to fix the issue?

**Comment by cub4vcu** [comment]
Same issue! Still trying to resolve.

**Comment by bmoore117** [comment]
I have this issue as well, pretty annoying! Did anyone else figure a way around it?

**Comment by bmoore117** [comment]
Leaving this comment here as I have found a workaround. For the TL;DR skip to the end

The core of the issue is that when you switch from mainnet to any test net, mist.exe tries to kill and relaunch geth.exe with different parameters. If you launch mist from the desktop shortcut, I don't know exactly what's going on, but mist is in some kind of mode where any warnings from geth are treated as errors. You'll note in @douglasdeodato's original screenshot, the messages displayed in the error dialog are only warnings. Seems like the devs need to tweak whatever's hosting the mist process when launched from the desktop.

At any rate, for a workaround solution, simply pop open a powershell prompt in your Mist install dir, and launch mist.exe from the command line. It will start the graphical application as normal, and you can switch between all networks and create accounts no problem. The reason it works is when launched this way, mist's output is bound to the powershell terminal instead of whatever Windows component is hosting mist when launched from the desktop, and so any warnings or errors that mist generates simply get printed to the terminal screen. Kinda useful to see what's happening with mist anyway!

**Comment by kingkung** [comment]
Worked for me!

**Comment by WimDeGroote** [comment]
If you are not soo technical here is what you do:
Right click on your "Mist" icon on your dekstop
Choose "Properties"
Click "ShortCut/Open File Location"
Copy the URL fom the address bar "C:\Program Files\Mist" (or whatever it says on your machine)
Click Windows Start button 
Type "Powershell"
Run Powershell from the menu by click it
type cd "C:\Program Files\Mist" or whatever you copied from above
type ".\Mist.exe"
And your download will continue :-)

**Comment by flyq** [comment]
When I want to do sth in test network, I have the problem, too.
Thanks to WimDeGroote.

![default](https://user-images.githubusercontent.com/16486808/34974032-e3dd85c8-fac5-11e7-82d3-f9cb6de1a552.PNG)


![default](https://user-images.githubusercontent.com/16486808/34974034-e7165058-fac5-11e7-9e34-fb54f124cf2e.PNG)

type ./Eth and `<Tab> Keyboard` 
type enter

And it works.
