### ISSUE TITLE
The synchronization stop at 99% !

### ISSUE THREAD

**Issue by GDMFSoAB** [ethereum/mist#3278]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.2`
OS & Version: OSX 10.10.5 Yosemite
Node version: `geth 1.7.2` 
Number of blocks synchronized: 99%
```
Hello,
Since many weeks, i can't access to my wallet because, at the opening, the synchronization's running but stop at 99% !!!
I erased several times the blockchain folder to resynchronized the whole blockchain but the problem keep on again and again.

An idea to resolve that ?

Thx.
M.

**Comment by fogonthedowns** [comment]
I've been stuck at about 40k blocks remaining for days on my dev system

**Comment by GDMFSoAB** [comment]
For me, it's only about 110 blocks remaining !

**Comment by mkdamike** [comment]
I'm having the same problem!!!!! I NEED my ETH to be active right now. This is unbelievable and totally unacceptable. Someone please tell me how much longer is this going to take?????

**Comment by freemann** [comment]
Same problem overhere for weeks. What an disaster!

**Comment by evertonfraga** [comment]
Hi everyone, this is not necessarily a Mist issue. Geth node is the one to blame. 

It is probably downloading State Entries while it seems "stuck". It takes long, but it eventually ends. You can start geth separately in order to follow a more in-depth log. 

How to start Geth separately: https://github.com/ethereum/mist/wiki#start-the-node-manually

Please refer to Geth repository for more informations: https://github.com/ethereum/go-ethereum/issues/14647
