### ISSUE TITLE
Node syncs at launch and has peers but cant get new blocks

### ISSUE THREAD

**Issue by bamos01** [ethereum/mist#329]
Using Mist 0.5.1 on MacOS-  was working for a while but I noticed it was slow syncing.  now it will sync when it first launches but then no new blocks are imported even though it usually has ~8-12 peers

**Comment by Tekarihoken** [comment]
I have the same problem with Mist 0.5.1 on Windows it work for a while and after a certain time it stop synching, I am obliged to close it and relaunch it in order to get it synching again

**Comment by bamos01** [comment]
I deleted the wallet and resynced the blockchain.  It worked for a while but now the problem is back again.  Doesn't seem to happen on my other Macs, but this one otherwise seems to be working normally.  Any idea what could be going on?

**Comment by johnpitchers** [comment]
Same Mist 0.5.2 on MacOS ElCapitan. I have plenty of Ether in my account.

Syncs at launch and then nothing. Trying to add a wallet contract and Mist shows "Creating..." but never gets anywhere. With geth console running in terminal I can see the blocks updating on my node but Mist's header shows an old block number and "xx minutes since last block" in red. 

If I close the geth console down, Mists immediately displays a "Connection Error" in red and my pending contract disappears. Restarting the console Mist syncs again but only the once and I'm back to where I started.

**Comment by bamos01** [comment]
Mine seems to be working now.  Not sure what happened.  Maybe there are more valid peers available with homestead?
