### ISSUE TITLE
Wallet Crashes My Internet

### ISSUE THREAD

**Issue by markcus007** [ethereum/mist#3320]
Hi Everyone,

When syncing my Wallet, my internet crashes. I have done a little research and the problem might be that my router doesn't allow all the connections. So I have to add Port Forwarding, but I don't know what data to put in. I have added a picture of the data my router requires. 
![image](https://user-images.githubusercontent.com/12004944/33222749-d6d19014-d12f-11e7-951b-a0ecdc288af3.png)

If anyone knows that this is not the problem, please let me know. 

Thank you.

- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
Hi @markcus007 

here are some links that might help:
https://github.com/ethereum/mist/wiki
https://ethereum.stackexchange.com/questions/809/which-tcp-and-udp-ports-are-required-to-run-an-ethereum-client

Mist uses Geth in order to sync. Should you still have problems, please refer to their repository: https://github.com/ethereum/go-ethereum/issues
