### ISSUE TITLE
I do not see my Ether from the Rinkeby - Test environment

### ISSUE THREAD

**Issue by Chrisknijff** [ethereum/mist#3331]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

I bought last Friday 24 Ether. Unfortunately I had a Wallet installed on the Rinkeby - Test environment in the speed. I am a beginner in the world of the coin. Afterwards I discovered that the specified address was an address of the Test environment. The shipment from the Exchange to this address went well, but it is also an address in the main Blockchain. I know this because I have checked that with etherscan.io. The problem now is that the Wallet Account is from the Test Network and the Ether is in the main Blockchain. I can not see them from my Test Network Wallet. 
Is it possible to import the Wallet Account from the test environment into the Wallet on the Main Network? 
Can somebody help me? I am afraid I may have lost everything.

```
Version: `0.9.3`
OS & Version: windows10 win64
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```
Used Wallet Ethereum-Wallet-win64-0-9-3.zip

**Comment by Chrisknijff** [comment]
Accidentally opened twice, I have closed it and created a new one

**Comment by Stoneyx1** [comment]
Hello, I have the same issue where I accidentally send a small amount of ether to Ethereum Wallet using Rinkeby Test Network. I am trying to transfer the funds now. How were you able to solve this problem? I see my Ether on the main Blockchain, so I know it was delivered successfully, but it does not show in my Ethereum Wallet (Because this is the Rinkeby Test Network). I will appreciate your feedback.
