### ISSUE TITLE
what is the min amout to deposit on the ethereum wallet

### ISSUE THREAD

**Issue by anders31** [ethereum/mist#3353]
hello, i would like to know what is the min amout to deposit on the ethereum wallet ?
because i have deposit 20$ of ether to the wallet and i still see 0 on my account

**Comment by 37** [comment]
Hey @anders31. As far as I'm aware there is no minimum so long as you include enough gas to cover the transaction. You can find some information on a suitable amount of gas [here](https://ethgasstation.info). 

If you've covered that as a base, then make sure you let your Ethereum wallet sync fully against the blockchain since your balance will likely only update when this is sorted. It can take quite a while if running Ethererum Wallet in 'normal' mode, so maybe try 'light' mode by going to Menu > Develop > Sync with light client. 

Hopefully that helps!
