### ISSUE TITLE
0 ETH since last version (0.9.3)

### ISSUE THREAD

**Issue by fcladf7** [ethereum/mist#3368]
Hi all,

Well... since last patch, I've searched a solution to my problem without success.
My account shows 0 ETH but blockchain explorer shows me the real amount.
Somebody got à solution to this problem ?

**Comment by unknown1235** [comment]
maybe need to wait for it to complete syncing???

**Comment by fcladf7** [comment]
Thanks for the help but that's not the problem.
Got no problem of syncing.

**Comment by hagitarowe** [comment]
@fcladf7 
I ran into this issue, and it was due to running an older version of wallet / geth. Have you tried re-installing wallet / geth & re-syncing?

**Comment by fcladf7** [comment]
When you say re-installing, you mean uninstall and re-install ?
Because when I updated my wallet with 0.9.3, I just re-installed in the folder containing the old version. That's a kind of re-installation, no ?

**Comment by fcladf7** [comment]
Well... I suppose I can say goodbye to my .5 ETH...
Why is there so fucking many problems with this wallet ???

**Comment by jonbateau** [comment]
I am running Ethereum Wallet 0.9.3 from my latest (2/13) download.

After progressive syncing across 8~10 days, it finally reached sync status and churned as I would assume a normal node would/should... that 'normal' status lasted about 2-days.

Since around 2/24 the  node has done pretty much nothing but sit there.. eeking along. 

Against my better judgement I transferred some ETH to it on two occasions.. and can ONLY see the values in the wallet when I select to invoke the 'Sync With Light Client(beta)' option.

Values show up .. BUT now .. even more weirdness.. On one account it continues to say 'wrong password', when I try to send ETH out..  and though the password could be wrong .. I normally paste a known value in all password processes, as oppose to type .. just so my fat fingers won't be the devil... and slip in something un-expected.. (ergo..: there should be a way to see what one has typed before committing).

Now today I have tried moving ETH to another outside wallet .. and again with the known password. This time it worked .. or so it seemed. The process reflects that the transaction worked (password was valid), BUT it sits there with zero confirmations now 6-hours later.

I think the problems are related .. but not too sure .. and certainly hate investing more effort or ETH if this is the only expected outcome. 

After reading the countless .. suggestions to remove, reload, re-sync, it is obvious that this is not elegant, nor ready for prime time, sadly!

I am quite open to suggestions.. and even the chance to waste more time .. 
but 4+ years later.. I do grow tired!
:-)

**Comment by alexvandesande** [comment]
@fcladf7  you can access your ether by using another wallet, even if this wallet is not working. Try:  [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com)

Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097

@jonbateau  for your password troubles, have you tried using the same accounts but on other wallets to test if it's a password or a wallet issue?
