### ISSUE TITLE
Cant sync need help

### ISSUE THREAD

**Issue by GoneNuts** [ethereum/mist#3375]
```
Version: `0.9.3`
OS & Version: osx 10.11.6 (15G31)
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4680003
```

I have tried resync 4 times same problem each time the last time i resynced i removed both chain data, ethash and lightchaindata with backups still having same issues gets to 99% max then continually chasing the chain  

Ether is not shown in the wallet
Wallet is not fully 99% synchronized but is stuck during the last part
My transaction is not confirmed

Been like this since 27 October 2017 waiting for updates gone through 3 updates no luck with any...

<img width="412" alt="screenshot 2017-12-05 15 26 01" src="https://user-images.githubusercontent.com/409152/33615044-efb1f7dc-d9d0-11e7-9b0a-529702260ce8.png">

[node.log.zip](https://github.com/ethereum/mist/files/1531704/node.log.zip)

**Comment by GoneNuts** [comment]
Just thought I would add i have tried both mist version 0.9.3 and eth wallet 0.9.3 both react the same

**Comment by rafales** [comment]
Had the same problem. it will download ~99% of blocks, then it will download "chain structure", then it will download the remaining blocks. It's not possible to know the number of "states" in chain structure upfront, so it will grow. As far as I remember yesterday it was about 5 mln, so be patient.

**Comment by imar2016** [comment]
I have had the same problem for over 7 months and it has almost sent me mad, I cannot do anything to get this to sync. Some of my friends have the issue also and i only know of 2 people with a working synced wallet in my group of friends. i think the late 0.8.x or very first 0.9.x releases this issue started for me. I have 5 PC's, complete install from scratch on all 5 and they exhibit the same problem. OS : win10 64bit. Every time this topic comes up someone closes it and relates it to some random issue without any explanation or advice on how to fix.....i expect it to happen here....i pray that this time its different. If anyone knows the fix for this please PLEASE share

**Comment by rafales** [comment]
@imar2016 where does your sync stop?

**Comment by imar2016** [comment]
99%....like everyone else's. There is a plethora of users complaining about this problem, god through the issues and read the sync problem ones....Why dont they pull down this official wallet until they actually can get it to work...its ridiculous and getting out of hand now..

**Comment by rafales** [comment]
@imar2016 the wallet downloads two things: blocks and states ("blockchain structure"). It knows the number of blocks (more or less), but it doesn't know the number of states, so it's constantly growing. As I said - 2 days ago it was at 5 milion. Where did it stop at blocks? Where did it stop (did it stop?) at states? Do you have peers connected?

**Comment by imar2016** [comment]
i have 13 peers connected. Its irrelevant where it stops at blocks, because a simple restart of the wallet will let it catch up a few blocks then stop again after downloading a few (hope you understand what i mean), its usually 201, 100, 101 blocks that it gets stuck at. The highest ive let the structure download to was 28 million. It took weeks, and i just couldnt stand it anymore...

**Comment by rafales** [comment]
@imar2016 28 million? That really sounds broken (as for blocks - it tries to download structure first, then downloads the rest of the blocks, so that's not the problem).

**Comment by imar2016** [comment]
structure is always huge...i wish i could remember which release this started doing this on...late 0.8.x i just cant remember which...every release prior to that was fine.

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com)

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
