### ISSUE TITLE
Ethereum Wallet transactions without password confirmation?

### ISSUE THREAD

**Issue by MWDV22** [ethereum/mist#3456]
Hi 

I found a transaction on etherscan from my wallet ( see below) details) 
Both tranactions are not done by me me and are not showing in my transaction log on the wallet page. 

Can someone explain what happended and how this could happen without password confirmation. 
The tranfer is showing up in my overvieuw below the wallet? 

https://etherscan.io/address/0x9d444bbc12fd9ba3525009aff122ce98ddd13b74#

This is the adress that first got one ehter and after that emptied my wallet. 

My Wallet is a Win 64 and up to date. below to overview of the tranactions and the adress they went to. 

![afbeelding](https://user-images.githubusercontent.com/34681816/34158056-463949d6-e4c4-11e7-9149-8b5c8bebc8e7.png)

many thanks 

MWDV

**Comment by JamesDall** [comment]
Most likely explanation for this is that someone stole your password & json file and did the transaction from somewhere else.

**Comment by evertonfraga** [comment]
Hi @MWDV22, you can rest assured because you ether is not at risk. 

There were no outbound transactions from your wallet. The account only had inbound transactions 
What I can identify is that your local wallet wasn't synced with the network, and as such, showing a 0 balance.

Consider using http://myetherwallet.com if you need to make transactions in a hurry.

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more sync informations.
