### ISSUE TITLE
Ethereum Wallet needs forever to sync.

### ISSUE THREAD

**Issue by Twinstar2** [ethereum/mist#3463]
Hey i bought some ETH and Tokens a while ago and everything synced "okay" the whole Blockchain synced within 4 days on my HDD with my System having 8GB RAM at that time.
No i want to make some transactions but i can't, because the Wallet syncs forever, i need to sync 500.000 Blocks and has taken 3 Days to get 60.000 of them.
Geth used 100% of my HDD resources, so i moved the whole thing to my new M.2 SSD, also i upgraded to 16GB 3200Mhz RAM. But it still only syncs with a speed of 1 block per 2 seconds. I have 100Mbit Internet so this is not the bottleneck as you can see here:

![Task Manager](https://image.ibb.co/niCBPm/2017_12_20_2.png)

I use the newest version of the Wallet on Windows 10 what can i do?

**Comment by cross** [comment]
I was looking to open a similar issue.  I had months ago managed to get my full node sync'd, but that took forever.  Now, my computer has been offline for a few weeks, and the prospect of catching up looks laughable.  It seems to be able to only get 1 to 3 blocks every 10-15 seconds.  It's currently getting blocks ~459000 of 4758854.  I'm running on a Mac, but don't know if that matters.

Anything I can do to help the geth process catch up faster?

**Comment by roscoaus** [comment]
Linked question, is it normal for the first sync to take days to complete (part if of the setup process for an Ethereum Wallet)?  I'm up to block 4766682 of 4766795 and this hasnt changed in the last 12 hours.  Screen isnt frozen as the number of peers is changing and occasionally see a percentage ~99.95%.  No hard drive activity at the moment either.  Is this normal and do I just need to wait it out?

**Comment by jbenedet** [comment]
Apparently this is a frequent issue that has been plaguing ETH developers for years, based on my recent search queries...I come here with the same problem as mentioned above. After approximately 5 days of syncing, closing the app and reopening I am finally within 100 blocks of syncing. That said, any progress appears to have stalled as the rate of syncing new blocks has slowed to the approximate rate of the creation of new ones. To say this is frustrating is a monumental understatement...

I have seen many suggest using third party wallets but that will not work for my situation given that I mistakenly transferred my ETH from coinbase to my ETH wallet prior to syncing...In addition, I find that a system which requires a third party solution for something as fundamental as access to a wallet is  critically flawed. This flaw absolutely undermines the current value of ETH relative to other crypto (i.e. the competition) imo. Nevermind the security risks associated with this. We want our ETH visible, transferable AND secure...

Others have also suggested performing using parity or some other (unfamiliar) application to expedite the process...Let me be clear folks: we're dealing with 100's if not 1000's of dollars worth of ETH in these accounts. Most people--including me--don't feel comfortable deleting folders and uploading unfamiliar apps to move and/or access large sums of their personal money...Doing this without the element of personal wealth at stake would be quite different...

GET THIS SYNCING ISSUE FIXED. I understand that ETH comes with more technical capabilities; but this tech --which I greatly appreciate --cannot come at such a burden as to undermine its most basic functions....This issue has me---and I'm sure millions of others across the globe--questioning the synergy of complex tech with practicable money....

**Comment by bowloffun** [comment]
I'm on day four or five of waiting to sync.  It says 225 blocks left but that's probably incorrect by now as it hasn't changed for a day or so.  Is there really no solution for this? Besides using a different wallet....

**Comment by hkirsman** [comment]
Why does it start re-checking the blocks? I see it shows 75 blocks left. Then it shows 80 blocks left. I close the app, start it and it shows 91 blocks left. 0% done. It doesn't make any sense to me.

**Comment by Padred** [comment]
Days spent reading forums, trying different solutions.
NOTHING WORKS.
Both Mist and Ethereum Wallet are non-working crapware?
How is this even possible?

FYI:
I am using a clean Windows 10 Enterprise 2016 LTSB machine, updated to the latest build.
[1607.14393.1944]

I suspect your software is puking because of file and directory permission issues.

**Comment by rtom098** [comment]
having same issue, my wallet syncs since more than a day and never gets done. Always when it's close to estimated number, the number of nodes increases so I never be finished with synchinc this. 
Really dissappointing.

**Comment by lowlanda** [comment]
Mine is broken too

Was working last week, broken this week. Does my head in..

**Comment by jbenedet** [comment]
I have been on hiatus from my ETH since my previous post, periodically checking for a solution patched by the developers. 

Seems obvious to me, but in my view, there should be a "fast sync" option available in the application once it is opened, for those who do not wish to mine or generate contracts....

**Comment by jbenedet** [comment]
The issue with the final set of blocks seems to be that new blocks (with associated chain structures) are constantly being generated (mined) and that the details of those blocks need to be communicated to peers before being up-loadable to your computer. The generation + communication causes a lag sufficiently large so that most connections/computers cannot keep up. And as the amount of miners increases along with the complexity of chain structures this process becomes more burdened over time...

In ETH's early life, with far less miners and less complex chain structures the process likely worked well. But in its current form today in 2018 it is unusable for most...We need an adaptation (similar to what I outlined above) from the developers to make this system usable for millions of users simultaneously...

**Comment by Twinstar2** [comment]
So i try to sync my ETH Wallet now over **2 Weeks** on an high end Desktop and it's still not done. Feels like the Future...

**Comment by lowlanda** [comment]
Check out issue #2466, and follow instructions for MyEtherWallet download and use, if you need a workaround until they fix it again

**Comment by Skippydog** [comment]
Uggg..... I was hoping for some answers and well it just seems everyone agrees this wallet is garbage :(

**Comment by ericwjr** [comment]
Same issue...wallet hasn't sync'd after 2 days.  Is there a way to send from this wallet without it syncing?  Otherwise my ether is just sitting there and I can't do anything with it.

**Comment by lowlanda** [comment]
Not sure atm ericwjr. I keep trying but still no luck, hence the suggestion to use an alternative method.

Good luck :)

**Comment by bowloffun** [comment]
I finally got my ETH out of the wallet and am giving up on using the wallet as it never synced.  Used myetherwallet.com and my Keystore/JSON File to access funds. Best of luck everyone.

**Comment by Evlos** [comment]
![screen shot 2018-01-09 at 00 42 52](https://user-images.githubusercontent.com/517862/34681386-b09184a2-f4d6-11e7-98fa-58aab3604734.png)

I'm using fast mode, it is been 3 days, and I feel really desperate.

**Comment by lowlanda** [comment]
2.5 days and 40+ gig less on SSD for my current attempt Evlos. "I want to believe" lol.

Ended up using the alternative again yesterday. It does feel good to have a backup plan that works. Particularly when ETH prices are so high atm.

![ethwall](https://user-images.githubusercontent.com/20736001/34682247-68f31450-f4f2-11e7-8ef3-132937bbff17.PNG)

**Comment by evertonfraga** [comment]
Please check this quick guide: https://github.com/ethereum/mist/issues/3097

**Comment by michaelx2018** [comment]
Anybody knows what is actual number when chain structure ends counting?

**Comment by cruzcranford** [comment]
I've been syncing for 3 months, this program is shit.

**Comment by CaptainMorgans** [comment]
How do we know when it has completed the Sync?

Here is what I am seeing on my wallet right now.

![image](https://user-images.githubusercontent.com/3514724/36550138-35ad2f9e-17fd-11e8-84ac-65c578b56c9f.png)

**Comment by yannisstrijkers** [comment]
Hi Guys, i sended ETH to ethereum wallet before syncing, trying to import it into MEW, but doesnt recognize password. So using MEW is not an option. how has solution for this issue?

thanks

**Comment by PIZANTH** [comment]
Where are the geniuses that designed this crap? My money is out in Limbo. I transferred an amount of Ethereum to my wallet before it was synched, now its been weeks and not synched yet. WTF?

**Comment by BreakHeadz** [comment]
Collect on new life.. 
0xFE902372f2F9561bb3CfFc5e191F9B7C9F2615a1 
Tnx who care. 2018 peace

**Comment by Diemberger** [comment]
Guys, also experiencing same issue, wallet takes forever to sync. 

Any solutions so far? Wallet syncing stuck with 60blocks left for almost 2days now :(

**Comment by PIZANTH** [comment]
Well, I have good news. After running my computer for six weeks, 24/7, I went to the develop drop down box in the upper left hand corner after launching the application. I scrolled down to "sync with light client (beta)" double clicked on it and bam, all of a sudden I am synced and my missing Ether appeared in the balance. Two days is nothing man. I bought a new hard drive and uploaded all my files and kept it as a backup because I thought I was going to burn up my the hard drive that had been working overtime. By the way if you have a screen saver turn it off. It consumes a lot of CPU operating energy. Let me know if that helps.




-----Original Message-----

**Comment by Diemberger** [comment]
@PIZANTH,

it's good I dropped here after 2 days ;) 

Wallet is now synced using the lite client, It just needs some patience before you'd get peers, mine was synced with only 1 peer connected. So yeah, for some users that still having issue in syncing, just try the light client, let it run for a couple of minutes to find peers, (maybe around 30-45mins)

**Comment by massasoit** [comment]
Ive been scrounging online forums and github, youtube, trying to find one decent answer that helps a non-technical person fix this issue, there has been none. Pizanth, yours came close but i dont have a light client in my Eth client. I've updated both geth and the wallet. stuck at 65...then goes to 105 and comes down to 65 and repeat!
any help ?  got Eth stuck in this wallet for the last 418 days.

**Comment by lowlanda** [comment]
If you really need to access your Ether, try the MyEtherWallet method I mentioned above. I'd also suggest installing another wallet like Jaxx, and send your ETH there.

I used MyEtherWallet a few times, but now use Jaxx because I can have my ETH, BTC, BCH and DASH all in one place. Haven't tried Ethereum Wallet since, but looks like they're still having issues with it.

Basically, there are alternative solutions that work! If anyone needs help, I'm happy to chat privately or publicly to help you access funds, as I'm sure others here would too. Your funds are all still there, just frustratingly out of reach for many :/

Best of luck regardless, don't let it get you down!

**Comment by massasoit** [comment]
Thank you Pizanth and lowlanda, 
Finally after 3 days of downloading and countless forum search, i finally downloaded and could see my balance and asks for a password which it never did when it was created. so now back to sq 1. Looking at [](https://github.com/ethereum/mist/issues/3513) 3513for furthering this discussion since all password related issues have converged there. Even filled out the google form. Hopefully before end of year should resolve this. Thanks guys for reaching out.

**Comment by lowlanda** [comment]
Yeah you need a password.. You would've created it when you 1st started
