### ISSUE TITLE
I can't see ETH from my mining pool, and can't sync completely either.

### ISSUE THREAD

**Issue by lunear** [ethereum/mist#3574]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows 10
Node version: `geth 0.0.0` 
Number of blocks synchronized: 4,515,44
![capture](https://user-images.githubusercontent.com/35475181/34968694-bd70d080-fa38-11e7-987d-c1737e01c34f.JPG)
2
```

Hi, I have used mining pool to earn some ETH coins, then I transferred to this wallet. But I can't see my all my coins. I transferred 0.38ETH but only see 0.12. Then my 120GB SSD was full, and the sync was stuck at some number over 4,300,000. So I upgraded to 240GB SSD, thought it would be enough. But just after one week, it was full again. Now I am using 2TB HDD as OS disk, but the sync is stuck at 4,515,442. My question is how I can see all the ETH coins I transferred in, and how I can sync completely to see the coins and transfer them out to Coinbase? Thanks.

**Comment by evertonfraga** [comment]
I totally understand the frustration. The upcoming Geth 1.8.0 will address many of those issues. The sync will be lighter on your machine and will take up to 50% less space.

In the meantime, here are some considerations:
- check your account's balance using http://etherscan.io
- make a backup of all account's keystore files via menu -> accounts -> backup -> accounts
- please check this troubleshooting guide on our wiki: https://github.com/ethereum/mist/wiki
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com if you need to make transactions in a hurry

In order to keep duplicated issues at minimum, let's keep this conversation at a single place, which we'll post about updates regarding sync: https://github.com/ethereum/mist/issues/3097
