### ISSUE TITLE
cant set location of block chain

### ISSUE THREAD

**Issue by fenderrex** [ethereum/mist#3607]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows
Node version: `geth umm` 
Number of blocks synchronized: 70k more to go 1/21
```

my main drive has 240gb of a block chain this is a SSD! i need to set the path and system links don't work in windows

**Comment by alexvandesande** [comment]
Hi @fenderrex 
Sorry, that feature is not available on Mist, which is intended to be more general audience. If you want, you can start your own geth node with a custom blockchain location.

We are working to solve the sync issues, so that all users don't need to store 250gb: https://github.com/ethereum/mist/issues/3097
