### ISSUE TITLE
Can't sync on El Capitan

### ISSUE THREAD

**Issue by songproducer** [ethereum/mist#362]
Gets stuck every time:

'Processing block 1,150,705 of 1,155,496.'

**Comment by swt83** [comment]
I have same issue.  Other tickets suggest it's a time/clock sync issue, but I haven't figured it out yet.

**Comment by frozeman** [comment]
It's processing the state. Please be patient. If you click on menu>develop>log file. You should see that.

**Comment by swt83** [comment]
The log file has been the same each time I check it.  I've been "needs to sync, please wait" for over 30 minutes.

**Comment by frozeman** [comment]
Please make sure you router is not blocking peers and you have you computer time synced.

**Comment by swt83** [comment]
The computer (Mac) time syncs to Apple servers in America.  I don't know of a way to force it to "re-sync".  Regarding the ports -- the app was syncing fine before the Homestead changeover, using 0.5.1.

**Comment by swt83** [comment]
Also, I'm showing the app is using 10% of my CPU and doesn't seem to fluctuate.  It's 10% solid consistently.

**Comment by swt83** [comment]
Sorry for the spam, just wanting to report everything.  I still had 0.5.1 installed, and it doesn't work anymore either.  Same issue, never ending "please wait".

**Comment by jacogr** [comment]
I finally got around to testing on my El Capitan machine (I already logged a bug on my other machine, non-Capitane, which doesn't work at all).

Same issues. It does not work at all where 0.5.1 at least worked on this machine. As soon as I open it starts falling behind in blocks. Yes, I am syncing as per the default to the apple timeservers. However, these servers are in Europe, I'm in Africa. Not sure if that has something to do with it - if you are checking against servers elsewhere, the distance is just a nightmare.

So no, nothing wrong on my end, however Mist is completely broken as off now - I have ETH, just cannot do anything with it.

**Comment by seekr** [comment]
I'm experiencing the same issues both with Mist and CLI "geth console" (more background story below)

I'm posting the screenshot of geth console verbosity 5:

![image](https://cloud.githubusercontent.com/assets/2786460/13815405/27cc391e-eb69-11e5-976e-f55b759bfc1b.png)

**Long story:

I've been struggling with similar problem for a week now. When I first launched Mist (last week) I did manage to download the whole chain once and started pool-mining via AlethOne, but then I noticed I would get a random stop alert from the pool saying the miner stop when I was in fact sitting in from of the screen watching the hashrate flutuate (mining, from what I understand). 

Then I started noticing Mist not launching because it couln't find peers or it would find very few of them, but would take forever to sync. Thinking that maybe the files were corrupted, I deleted everything and started from scratch (but keep my wallet address key). This is when I decided to install CLI tools as well. With the CLI tools I can see that the syncing is happening, and it feels speedy enough to start with but then grinds to an halt. PeerCount also never goes above 7-9 and stays at 1 or 0 many times.

**Comment by eharvest** [comment]
I had the same issue. Got stuck after random amount of blocks. After restart of ethereum stuck again aso. Then I did geth -nat=none and it spewed out constantly:
..`
I0319 22:16:23.528799    7518 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=131594): checksum mismatch, want=0xc5f6f33 got=0x4f0f3b49 [file=012064.ldb]
I0319 22:16:29.271615    7518 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=131594): checksum mismatch, want=0xc5f6f33 got=0x4f0f3b49 [file=012064.ldb]
I0319 22:16:36.133056    7518 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=131594): checksum mismatch, want=0xc5f6f33 got=0x4f0f3b49 [file=012064.ldb]
...
`
I just deleted 012064.ldb, restarted ethereum and could successfully sync.

**Comment by swt83** [comment]
I can confirm that simply rebooting your computer solves this problem.

**Comment by popiahalex** [comment]
<img width="592" alt="screenshot 2016-03-26 22 18 43" src="https://cloud.githubusercontent.com/assets/7612947/14060495/fce12e68-f3a0-11e5-9741-4b079533b1aa.png">

Cant move and can't importing as well...

**Comment by luclu** [comment]
Please try version 0.7.4 as it is bundled with geth 1.4.4 which cointains several bugfixes and improvements on synchronization.
I will close for now as this is most likely fixed. Feel free to report back and discuss if you are still affected!
