### ISSUE TITLE
Question about eth wallet (meta mask) bug

### ISSUE THREAD

**Issue by jazzinuf** [ethereum/mist#3626]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by jazzinuf** [comment]
I have made a metamask acnt to store my ico token BAR with ETH. There was a glitch in the system with metamask, where my seedphrase wouldn’t restore my original account with my tokens but gives me a new account that has no value. I emailed the team and is pretty slow on responding. I have a feeling the system generated a seedphrase for a different account from a glitch in the system. Can someone please let me know if it’s possible to recover my tokens?

**Comment by marcgarreau** [comment]
If you have your private key or a keystore file, you can use those to access your wallet from another service, like MyEtherWallet or Mist. You said you emailed the metamask team, but you can also file an issue in the appropriate repo (probably https://github.com/MetaMask/metamask-extension/issues ?) I'm closing this issue, because it is not specifically related to Mist. Feel free to follow up if you have more questions.
