### ISSUE TITLE
balance is not updated

### ISSUE THREAD

**Issue by DOCUA** [ethereum/mist#3627]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows
Node version: `geth 0.0.0` 
now: 137 block left
```

- Ether is not shown in the wallet
- I send ether to the wallet but it doesn't show up
https://etherscan.io/address/0x5526efba8878ad9c4bb9eed4c4825e03318f9378

please help. thanks

**Comment by marcgarreau** [comment]
Typically this is because your geth node has not fully synced. Until it is, you will not see your proper balance. If you need to use your funds before your local node is synced, you can access your wallet through a service like MyEtherWallet. Closing the issue, but feel free to comment further if you have additional questions or details.
