### ISSUE TITLE
Sent ETH from Bitstamp to Ledger nano - funds in "internal transaction"

### ISSUE THREAD

**Issue by Arno7** [ethereum/mist#3629]
Hello,

I withdrew .22370372  eth from bitstamp to my ledger wallet and the transaction is appearing in "internal transaction". My address is:   0x3088C856fc2DF62839bA8E81d81026D3a36c01a5

What can I do to have these funds appear in my wallet? They have never made it to my wallet. Need immediate assistance please!
<img width="430" alt="screen shot 2018-01-27 at 3 49 13 pm" src="https://user-images.githubusercontent.com/35361809/35476307-8ab29ba0-037b-11e8-85ac-4cda80465a32.png">

**Comment by evertonfraga** [comment]
Hi @Arno7, sorry for the delay.

The transaction was indeed successful, and you should rest assured that you have control of those funds. However, in these recent days, it's being a bit rough to sync with the network, that's why it still display zero balance. 

If you have an immediate need to move those funds, you can use https://MyEtherWallet.com and follow their instructions.

I'll close this issue, feel free to comment.
