### ISSUE TITLE
recover password

### ISSUE THREAD

**Issue by scratchy001** [ethereum/mist#3630]
Hey guys,

I've downloaded ETH wallet from the official site in the spring when I started mining.
At some point I wanted to create a backup and if memory serves right, it didn't allow me to export it unless I set a password to it.
Noooow... the problem is that I don't remember the password. 
It can be formed from a few bases + a few suffixes.
I've tried a lot of them but none seems to be working.
It's not much what I have there (didn't mine ETH, mined something else and exchanged to ETH).
I can even prove what and when I mined, when and where I made the exchange. So it's my account.
But I can't transfer the funds out of it.
Can anyone help me? There'a a guy that helps people but he said that the 1.1 ETH in my wallet is too little for him to consider trying.
Thank you so much in advance!

**Comment by marcgarreau** [comment]
Sorry to report that (by design) there's nothing we can do to assist with password recovery. If you're comfortable with code, it may be worth your time to try a brute force password recovery tool like pyethrecover. I have never used it personally, so I can't walk you through that process. As an example, though, here's one comment with details of someone who had success with that route: https://github.com/ethereum/mist/issues/3176#issuecomment-347361860. Good luck!

**Comment by svobodnu1** [comment]
hello, I can help with the recovery of the wallet, apply 20% of the amount pc-dopomoga@mail.ru
