### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by unknownhostname** [ethereum/mist#3650]
Its been 2 years since I tried to sync ethereum wallet. After 2 years I come bakc and still the same problem 99% sync ... 

We build smart wallets

We build smart contracts

We build unstoppable applications

But we cant build a proper software to sync our blockchain..

All this with 100+ billion market cap... pathetic

**Comment by Taledeyo** [comment]
Better..come to stay on my private Island...go to snorkeling and relaxing
on the beach.;)

เมื่อ 1 ก.พ. 2018 4:14 PM "unknownhostname" <notifications@github.com>
เขียนว่า

**Comment by evertonfraga** [comment]
Hi, slow syncing is a real problem and quite frustrating. Some recommendations:

- check your account's balance using http://etherscan.io
- make a backup of all account's keystore files via menu -> accounts -> backup -> accounts
- please check this troubleshooting guide on our wiki: https://github.com/ethereum/mist/wiki
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com if you need to make transactions in a hurry

If this didn't solve your issue, please follow these instructions and upload the node.log files:
- go to menu -> accounts -> backup -> application data
- zip and upload node.log and all other node.log.X files

In order to keep duplicated issues at minimum, let's keep this conversation at a single place, which will always be updated with latest syncing status: https://github.com/ethereum/mist/issues/3097

**Comment by unknownhostname** [comment]
[node.log](https://github.com/ethereum/mist/files/1687372/node.log)

check node.log and tell me whats wrong... 

I dont think anything is wrong ... it doesnt even records the problems to node.log file.

terrible software
