### ISSUE TITLE
Transaction fee of 300% the transferred amount

### ISSUE THREAD

**Issue by maverick85** [ethereum/mist#3653]
I'm trying to transfer 0.03 ether and I'm being asked a fee of 0.1 ether which is approximately 80 EURO. for a 25 euro transfer??? the fee is 300% of the value??

<img width="530" alt="screen shot 2018-02-01 at 16 07 29" src="https://user-images.githubusercontent.com/10200278/35688864-11181728-076a-11e8-8326-f4feaa452a08.png">

**Comment by Taledeyo** [comment]
Hi..I'm just beginer..even not get token yet.

เมื่อ 1 ก.พ. 2018 11:08 PM "Ricardo" <notifications@github.com> เขียนว่า

**Comment by evertonfraga** [comment]
Hi @maverick85,

This is not the expected behavior. Please inform your software versions:
- Sync mode: Is the Light Client (`Develop > Sync with Light Client`) enabled or not?
- Geth version (`Develop > Node > Geth (x.x.x)`)

Thanks!

**Comment by maverick85** [comment]
Hi @evertonfraga, thank you for your reply.

regarding your questions:

1. yes sync mode is enabled
2. geth 1.7.2

cheers

**Comment by michnovka** [comment]
I confirm the same issue for QASH token in my wallet. min fee is 0.1 ETH!!! for 3.5 ETH I can have transaction mined within 30 seconds. Looks not like expected behaviour. When I switch to ETH instead of token, fees are 1000x smaller.

Ethereum Wallet 0.9.3
GETH - VERSION: 1.7.2-stable-1db4ecdc

Im running ubuntu 64bit and installed Ethereum wallet from .deb (but I think this is irrelevant)

**Comment by maverick85** [comment]
Hi there,

I'd like to leave an update here;
So, meanwhile I've re-downloaded the ethereum wallet from ethereum.org it was already up to date but I downloaded it again anyway.

Somewhere along the way the fee changed to what let's assume a correct value.
For the 0.03 transfer I was 'charged' a 0.000363 fee.

What happens now is that there are NO CONFIRMATIONS in 12 hours.

Attaching another screenshot

<img width="608" alt="screen shot 2018-02-02 at 10 45 59" src="https://user-images.githubusercontent.com/10200278/35729878-03257fd6-0808-11e8-854b-9c6598a5e4c6.png">

When I click the transaction ID, etherscan tells me

> Sorry, we are unable to locate this Transaction Hash

**Comment by maverick85** [comment]
15 hours 0 confirmations

@evertonfraga @ryanio

**Comment by michnovka** [comment]
@maverick85 can u post link to etherscan so that we dont have to retype it from SS? Thanks

**Comment by maverick85** [comment]
https://etherscan.io/tx/0xe5176749bf8456e39bcc61bec6a17555648bcbd5c5aa42742a3133743e52f3e1

**Comment by maverick85** [comment]
@evertonfraga hey mate what's up?

3 days zero confirmations. My node is in sync. I replied to all your questions, some feedback is appreciated. thanks

**Comment by evertonfraga** [comment]
If you've got zero confirmations after a large sum of time, it's clear that your transaction didn't go through. 

At the moment, the wallet doesn't let users set the nonce while sending transactions, so I'd recommend — in order to avoid double transactions — you to test out another wallet to resend the transaction with the same nonce value (Metamask or MyCripto).
