### ISSUE TITLE
My ether wallet on desktop doesn't show the amount ether I have in the wallet so cannot create the wallet contract.

### ISSUE THREAD

**Issue by Angelina2016** [ethereum/mist#3681]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
Hi @Angelina2016, that makes 100% logic sense. 

In order to the wallet show correct balances, you have to be in sync with the network. Currently the fastest way to achieve that is enabling `Develop > Sync with light client`. 

Preferably after updating to [version 0.10.0](https://github.com/ethereum/mist/releases/tag/v0.10.0)
