### ISSUE TITLE
Ethereum Wallet never end sync

### ISSUE THREAD

**Issue by sam1138** [ethereum/mist#3698]
hi 
I'm very new here; I have the subject problem
sync seems to never finish

Version: `0.9.3`
OS & Version: windows 10 64 bit
Node version: `geth 1.8.1` 
Number of blocks synchronized: stuck at 65 blocks left
pc cable connected
internet speed: around 14 Mbps

I'm using the command 
geth --rpc --fast --cache=1024

worked on all sunday
monday night
tuesday morning
still not finished

![immagine](https://user-images.githubusercontent.com/36677861/36447102-9d15e98a-1683-11e8-9f92-346c59b4cec7.jpg)
![immagine2](https://user-images.githubusercontent.com/36677861/36447103-9d4c13ac-1683-11e8-8f4d-bbd7bc40d8d4.jpg)

thanks for help

**Comment by sam1138** [comment]
sorry Barfield36 
it's the same string....I'm already using it as you can see from my first screenshoot

this night is passed and again sync not completed
thanks in advance friends for the support
David

**Comment by PepeLopez** [comment]
Same here - never get synced, always around 65 blocks to sync.
Actually, my account shows 0 ETH instead of it's real value. 
Extremely disappointing...

**Comment by CalvinHartwell** [comment]
+1

Actually, I managed to get the sync to finish but wallets still show 0 balance. You perhaps could try spinning it up on EC2 for faster network connectivity but honestly this needs to be fixed. 

My guess is that it is caused by the performance of the Ethereum network (usage dramatically increased recently I believe) or an ISP throttle.

I've not read the entire ETH source-code, mist or geth, but it could be an intentional throttle produced by the developers as a means of stop-loss. If you can't use your wallet,  you can't sell or transfer eth, pretty simple. I hope this is not the real reason. 

I managed to get my ETH to the exchange using [https://www.myetherwallet.com/](https://www.myetherwallet.com/). It should work fine but be careful, especially if you have a large amount of ETH.

**Comment by sam1138** [comment]
updates
at today more than 62 Gb downloaded ...
is this normal? 

interesting what said by Calvin...

for my very limited knowledge of this arguments the sync problem is still on the table...

![immagine3](https://user-images.githubusercontent.com/36677861/36503031-113de1f0-174c-11e8-9a41-ac93aa62947a.jpg)

**Comment by stepanhack** [comment]
Try using --syncmode light, otherwise you will have to download the whole chaindata which is currently at 50gb+ (https://etherscan.io/chart2/chaindatasizefast). 

See this how to use the light mode with geth https://www.reddit.com/r/ethereum/comments/669cn9/how_to_use_the_geth_light_client_in_combination/. Otherwise you can do the same thing in the Mist Wallet by checking, Develop ->Sync with light client (beta).

**Comment by sam1138** [comment]
great stepanhack !!!
I think it worked !! 
really few minutes to sync

![immagine4](https://user-images.githubusercontent.com/36677861/36504451-d6f49246-1750-11e8-9fbf-38a8b68fb9d3.jpg)

really thanks for help!

**Comment by CalvinHartwell** [comment]
> great stepanhack !!!
> I think it worked !!
> really few minutes to sync

I was in the same position, but balance would still not appear even though sync'd.

**Comment by FGYPXZ** [comment]
Using Light version hepls to see the balance, but the transfer fees are much highier than in the main wallet. Min. 0.05 Eth for transaction. It seems Ethereium is a bubble and does not cost that much, because it's useless.

**Comment by bifetuga** [comment]
It just doesn't end, it's an endless nightmare been at it for 4 days... afraid to say that this wallet is a major fail

**Comment by bitNINj4** [comment]
I have the same issues on multiple Win10 Pro 64 PC's. It's extremely frustrating to watch the chaindata folder increase and decrease in size but never surpass ~62GB while sequentially writing and deleting block data.. :(

**Comment by Bernard-Biolchini** [comment]
Im with the same problem and the solution is painful because you'll have to restart the sync.
But it was impossible to solve without doing that because everey time that my computer seems to be reaching the last block started to sincronize the chaindata , finally, that was an endless process.

You need to go to C:Users: Name of Computer (Each computer has a personal name):App:Roaming:Ethereum:Geth:Chaindata //DELETE THIS FOLDER Chaindata

Now you restart the process from zero , but now you will finally find the END
