### ISSUE TITLE
Mist is not injecting web3 in the firfox browser

### ISSUE THREAD

**Issue by neverbackdow** [ethereum/mist#3702]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: Ubuntu 17.10
Node version: `geth 1.8.1` 
Number of blocks synchronized: 1809344
```

html file:-

<html>
<script src="web3.js"></script>
<script>
if (typeof web3 !== 'undefined') {
  web3 = new Web3(web3.currentProvider);
} else {
  // set the provider you want from Web3.providers
  web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
}

alert(web3.eth.accounts);
</script>
</html>
 
Error :-
SyntaxError: An invalid or illegal string was specified
inpage.js:10796
Loading failed for the <script> with source “file:///home/pradeep/testrpc/web3.js”.
test.html:2
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/
test.html:14308:40198
Error: CONNECTION ERROR: Couldn't connect to node http://localhost:8545.
test.html:14308:27650
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
test.html

**Comment by evertonfraga** [comment]
Hi, I am not sure I understood your question.

What application are you using, Mist or Firefox? Can you send a screenshot? 

Thanks!

**Comment by evertonfraga** [comment]
Hi, from what you told me, it has little to do with Mist. 

If you are developing a dapp in Firefox and a Metamask transaction window popped up, you are possibly calling some function like `MyContract.method.call(…)` instead of `MyContract.method(…)`

I'll close this issue, please make good use of web3.js documentation, according to the version you are using:
- https://github.com/ethereum/wiki/wiki/JavaScript-API
- http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html
