### ISSUE TITLE
Ether lost - HELP!

### ISSUE THREAD

**Issue by bikerboy4489** [ethereum/mist#371]
Ok so here's how my ethereum wallet used to work. I would open the app and it would prompt me for my master password, it would then sign me in and hey presto there was my account which held around 25 - 30 Ether in it and then below that was my wallet which holds 34.99 Ether in it.

I then made the mistake of updating to win64-0-5-2 which removed the prompt for password and I now can no longer access the account that holds my Ether, I can only see my wallet. Now this is EXTREMELY frustrating as for the past few weeks I have been trying to transfer my Ether from this account in to my wallet so it was safe however the transaction would start and then fail.

How can I get the new version to prompt me for my password so I can access my accounts again?

Thanks in advance.

James

**Comment by alexvandesande** [comment]
Hi @bikerboy4489 don't worry you didn't lose anything.

So what happened is that the wallet comes bundled with two nodes, Geth and Eth. Since you had a master password, this means that you were using the eth, the c++ node that has some issues in building for windows. Here's what you can do:

Open the wallet and see if you can switch nodes from geth to eth on the develop menu. If it does then you'll be asked your master password and you are done. If you can't then do one of these:

1) wait until there is a new wallet with eth for windows support

2) Install eth manually and then you'll be able to switch it.

3) Run an older version of the wallet and move your funds

Please reopen the issue if that doesn't solve your problem

**Comment by sharipeach** [comment]
@alexvandesande 

Might you be able to help me too?

I had 123 Ether in my Mist wallet today.  I updated MIST to today's version, and I chose yes to the hard fork.  When my wallet opened, my ether are gone.  My Dao contract is grey'd out.  What happened?  How can I recover my ether!?

Thanks!
Shari Peach
