### ISSUE TITLE
deployed controct missing ?? Do not complie contract ? two questions

### ISSUE THREAD

**Issue by INTERESTING-OMG** [ethereum/mist#3732]
mist: 0.9.3
windows 10
 `geth 1.8.2-stable` 
private chain

Sorry, I am not good at English.
Today I update my geth. It is really stupid!
Now I hava two questions. 
I use geth to start a private chain by powershell. I deploy the contract in it by mist . When I restart the powershell and mist , the contract missed ,the ether in my account turn into zero and only my account left !

Secondly , this question happens sometime , especially when the contract is too long. When I put my contract in mist , it is not compiled ! it shows 
"在这里填入合约源码。您可以在下列连接中找到合约的范例 ethereum.org：
建立 代币
启动众筹
创建区块链组织"

Sorry , I failed to upload pictures.

**Comment by evertonfraga** [comment]
Hi @INTERESTING-OMG, how are you?

Ethereum Wallet's contract compilation feature was superseded by https://remix.ethereum.org. You can use remix from Mist. It will compile your contract, respecting gasLimit and other Solidity criteria. 

As for ethereum balances, please note `geth --dev` does not save data, as you might expect. In order to persist information in your private blockchain, please use `geth --dev --datadir [directory]`. 

More information at: https://github.com/ethereum/go-ethereum/pull/15323
