### ISSUE TITLE
hello need help cant restore my keaystore 

### ISSUE THREAD

**Issue by hanspeter77** [ethereum/mist#3735]
hey im need help the new geth version is an worm says my kaspersky im mußt shot down kaspersky to run eth wallet;( first problem
an now i will open eth wallet and anytime says make new account also my keystore files are in the keystore butt he dosent load this i dont now why ??
can anyone help me please

**Comment by simon66** [comment]
Hi @hanspeter77 
Are you saying that your antivirus is detecting `Mist` as a virus?
Your wallet is stored at `\%APPDATA%\Ethereum\keystore`. The wallet name should start with `UTC--2018-02-07-.....`. If `Mist` is asking for a wallet, just import that one in.
Also, whats your native language? Someone from the team might speak the same language as you and make the helping process a bit more easier :)

**Comment by hanspeter77** [comment]
es funktioniert abe rich mußte eine ausnahme hinzufügen bie meim antivirus kaspersky.
der sagte nähmlich die neue geth version ist ein wurm ??

**Comment by philsmd** [comment]
I think the best thing you can do here is to contact the vendor of your security software / antivirus / anti-malware (in your case kaspersky) and ask them if they can verify the binaries again and eventually whitelist them or change their heuristic checks etc to not block mist/ethereum wallet/geth.

I think the main problem could be that geth (go-ethereum, see https://github.com/go-ethereum) which is used by mist/ethereum wallet could also be used for mining ...  and unfortunately since there are many new malware species developed these days with hidden mining code (or maybe even with geth itself as the miner) included, it could happen that some security suites try to block each and every binaries that could be used for mining.
I think that the only solution here is that you (and maybe other affected users reading this) contact the company that develops the anti-malware/anti-virus software and tell them that they should only block it if the user didn't explicitly installed the software (mist/geth etc) and of course the anti-virus software should also be able to "allow running mining software" (therefore some dialog/check should allow the user to explicitly tell e.g. kaspersky that mining is allowed on this system).

I don't think this is a mist/ethereum wallet problem at all. It's more likely a false positive detection (not in all cases because it could also happen that bad actors include the geth binary AS-IS without modification and let the victims system mine for them) of the anti-virus software.

**Comment by evertonfraga** [comment]
Hi @hanspeter77,

We got in touch with Kaspersky labs, and it was a false positive. More info: https://github.com/ethereum/mist/issues/3338#issuecomment-349229346
