### ISSUE TITLE
Accounts should provide option to store a password hint

### ISSUE THREAD

**Issue by xor-freenet** [ethereum/mist#3744]
if you follow the best practice of avoiding key re-use then you will quickly run into having many accounts, each of which having a different password.

Thus it would be nice if it were possible to store a passwort hint for each account.
This could also reduce the number of support requests w.r.t. lost passwords.

Implementation-wise I would recommend implementing it to ask for a hint right when asking the user to set a password. This means it can check whether the hint contains the password itself in order to disallow that, and it also encourages users to set a hint.

(I have not used the contract-based wallets yet so if they also need a separate password then this issue applies to them as well of course.)

**Comment by gargoyle** [comment]
@xor-freenet No. It should not!

Your passwords should be long random strings which you have no way of remembering and store them in a password manager. Most password managers have the option to generate such passwords too. Eg, heres 3 from my password manager (don't use these):-

- tic-pry-verse-any
- humid-amide-dome-antic
- aba-feud-raise-jonas

I can personally recommend 1Password and Enpass. The latter being my manager of choice at the moment as it works on Windows, Linux and Mobile (iOS) and syncs via dropbox.

**Comment by PhilippLgh** [comment]
Totally agree with @gargoyle.
The idea of a password hint is not bad per se, but it is not suitable in security critical environments (like wallets).
Since your password should be a long random string anyways, no password hint could *securely* help you remembering it.
We are always trying to find better solutions while keeping a good balance between convenience and security. The team knows that remembering more and more passwords becomes a problem in itself and we are open for suggestions. Measurements that weaken the security level however will not be considered for future releases.
Thanks - closing the issue

**Comment by xor-freenet** [comment]
@gargoyle @PhilippLgh 
> Your passwords should be long random strings which you have no way of remembering and store them in a password manager. Most password managers have the option to generate such passwords too. Eg, heres 3 from my password manager (don't use these):

Uhm, sorry, I did by no means whatsoever intend to not use fully random passwords!
I didn't explain my intentions well enough:

The problem is that using different fully random passwords for e.g. a dozen accounts would mean that I have to try out each password on each account when I want to send ether.
That's obviously an inacceptable amount of work.

Writing the associated account address on the paper with the passwords is *not* an option as the paper should be safely backed up in multiple places and thus is not easy to modify when generating new accounts for daily use.
Thus the association which of the random passwords belongs to each account needs to be stored in the wallet software -that's the suggested password hint.
That hint would not contain any information which the password could be derived from. It merely would be an index number such as "Password 5 on password sheet of 2018".

-> Please re-open. I'll edit the original issue description to make this more clear so I don't bother further people with the easy to misunderstand original description.

**Comment by xor-freenet** [comment]
@gargoyle @PhilippLgh 

Also please notice that having the user try out the dozens of passwords of all accounts when sending from a single account would also mean that if the software is compromised they'll be providing the malware with the passwords of all accounts at once, thus allowing theft of **all** ether.

(Which is the reason why I want to use a different password for each account - to ensure entering the password only implies the risk of one account getting stolen.)

**Comment by gargoyle** [comment]
I think you have miss-understood how a password manager works. The password is stored with the account number and any other information you want to store for that individual account. So you can safely go direct to the password you want.

I'm not sure why you are storing passwords on bits of paper!

Also, I don't understand the reason for a single user having multiple accounts?

Perhaps you have an edge use case which you could explain a bit better?

**Comment by xor-freenet** [comment]
@gargoyle 
> I think you have miss-understood how a password manager works. The password is stored with the account number and any other information you want to store for that individual account. So you can safely go direct to the password you want.

I'm a programmer, you don't need to waste your time on explaining simple things like password managers to me :)

> I'm not sure why you are storing passwords on bits of paper!

A password manager is not a valid thing to use in a context which requires high security as the passwords as stored on the same system as the software which consumes them.
Thus unlocking it for any unimportant frequent daily activity such as reading your emails means you risk that malware which is already on the system steals your ether.

A physical piece of paper fixes this by the system not having access to the password until you actually use it. Further you can store it even in a different physical location to be secure against theft and this: https://xkcd.com/538/

> Also, I don't understand the reason for a single user having multiple accounts?
> Perhaps you have an edge use case which you could explain a bit better?

There are at least four, three of which I'd consider non-edge:

### Taxation

In some jurisdictions the source of money is very relevant for how it is taxed.
I suppose you can imagine this without me bringing up a lengthy example? :) 

### Privacy

Publicly showing that you own a large amount of money by having all of it in a single account which you use for daily transactions attracts criminals.

### The system being compromised while you enter the password

Using a single account with a single password means stealing those allows theft of all ether at once.  Consider the following not-so-unlikely threat model:
  - A remote code execution exploit is found in Geth or any other thing on the system which allows the attacker to install a trojan.
  - A trojan uses the exploit to:
    - disable auto update in victim wallets, virus scanners, etc. so nothing can tell you that you've been hacked.
    - wait until you want to send ether. Once you do it sends **ALL** your ether to the attacker.

So typically  due to the auto-update disabling you will only notice that you've been hacked once you try to send coins and they don't arrive at their destination - but then it's already too late because all your coins were in the single account you just entered the password for.
If you distribute your funds across multiple accounts there's a chance you'd be just trying to send as much coins as there are in a single one and you thus don't unlock all accounts for the malware.

FYI I don't consider this an edge use case as RCE exploits are found very frequently on modern systems.

### Avoiding crypto exploits

I assume a single account consists of a single pub-/privkey pair (correct me if I'm wrong).
I assume it's done like in Bitcoin where the address of the account is the hash of the public key, and transactions from the account contain the pubkey and a signature of the privkey.
I.e. until you send the first transaction the pubkey is not revealed to the public, and also not any signature of the privkey.

Vulnerabilities in cryptography which allow extracting the private key from public information are typically more feasible if the public information is the pubkey and/or a signature than if the public information is just the hash of the public key.
Thus as soon as you send coins from an account for the first time it is less secure against future vulnerabilities in the crypto than it was when just the address was publicly known as the transaction reveals the pubkey and a signature.
Hence on Bitcoin re-use of a single address is discouraged and should be discouraged on Ethereum as well. See https://en.bitcoin.it/wiki/Address_reuse

Arguably, even if a single account is not equal to a single privkey but equal to a single seed from which multiple privkeys are derived it is still a good idea to not re-use accounts for multiple sends:
A single seed is still a single piece of entropy, and the more information you publish which was derived from it the more information is available for attacks on the crypto / guessing the entropy.

**Comment by gargoyle** [comment]
Thanks for taking the time to explain, I understand your point of view much better now. (I'm also a developer)

However, I think these are mostly down to your choices in privacy and security and I still think adding password hints is a big no no from a software point of view for two reasons: First, for everyone that uses them sensibly, there are 1000 lazy people that will use them incorrectly and you then place a burden on the software development teams to try and counter-act such behaviour. Secondly, what happens when someone else's idea of what is the "best practice" for privacy and security differs from yours and mine? Does the software team then have to implement "feature x" because that help their use case? Not a sustainable approach to software dev - as you know.

Lines need to be drawn. 

From a geth users point of view, I'm happy that the best current approach is that the account is locked with a private key which is secured with a password. In order to compromise the account you already have to overcome 2 factor authentication - you need the key and the password to unlock it.

How you store this information is then beyond the scope of geth development. 

I may choose to keep everything on one system which I am confident is secure. I may choose to keep keys and passwords on separate external drives, or bits of paper. That's my problem. The XKCD dude with the $5 wrench can just as equally beat out the location of the bits of paper as he could a password!

In your case, the answer would be to implement an index sheet to go along side your password sheet to hold the information you are suggesting goes in the hint field. Eg. Index sheet might have "Account X => Blue password sheet, 5th line". Then you store the two sheets in two different safes, or whatever.

Same applies to any discussion of malware. It's like trying to blame the bank that your wallet got stolen because you left it in your coat picket while you nipped to the loo. If you allow your system to be compromised whether its a computer with malware, or someone sneaks a copy of your safe key and photocopies your password sheets - that's a weakness in your security system.

Finally, from my understanding, the multi-account idea is sound as long as you keep the money in the system. You can anonymously control as many accounts as you like. However, as soon as you want to transfer money in or out of that system, you have to register somewhere - Unless you know someone that hangs out on street corners and will physically hand out cash in exchange for Ether?
