### ISSUE TITLE
After syncing, Mist doesn't update info (but stays syncd)

### ISSUE THREAD

**Issue by housemobile** [ethereum/mist#3837]
Version: `0.10.0` win64
OS & Version: windows 7
Node version: `geth 1.8.2` according to Mist, but I've self-installed 1.8.3
Number of blocks synchronized: 5,441,756 

![mistsync](https://user-images.githubusercontent.com/17286590/38780303-81e32ae4-40a2-11e8-9d24-34b0d657ec96.png)

I syncd it yesterday. After it catches up to the current block the bottom left part of Mist (pic attached) doesn't continue to update. But I just successfully sent a tx, so it does in fact remain syncd.

**Comment by housemobile** [comment]
maybe it's this?

https://github.com/ethereum/go-ethereum/pull/16360

**Comment by marcgarreau** [comment]
Pardon the response delay and thanks for this report @housemobile. I don't see this behavior when synced with a light client. Which sync mode are you experiencing this with? And you're connected to your node not managed by Mist? We're hard at work on a new architecture that replaces this component, among others; so, if its not addressed before, it will be in the next release.

**Comment by iquidus** [comment]
I have encountered a similar issue, altho im in a somewhat unusual scenario (running Mist code with a geth fork based on an earlier version of geth), so may be unrelated to OP. However thought I would chime in in-case it provides some insight. I am launching in development mode (yarn dev:meteor, yarn dev:electron)

In my case my node (launched by Mist) is staying sync'd with network (new blocks coming in as they are mined) however after a
```
Node started syncing, stopping app operation
Restart app operation again
```

takes place nodeInfo is not updating block number (or time since last block). 

readding mistInit() (removed in https://github.com/ethereum/mist/commit/a161cf6e911997cea347d08d344545e750bb1fa6 ) forces  reset, getting block number updated correctly, however this is not an ideal solution.

**Comment by housemobile** [comment]
@marcgarreau I'm in light client as well. I recently deleted the whole database and resyncd fresh. Seems a bit better now.

@iquidus development mode is far beyond my technical capabilities.
