### ISSUE TITLE
Wallet does not update geth ==> light sync breaks

### ISSUE THREAD

**Issue by WernerderChamp** [ethereum/mist#3855]
Ethereum wallet does not update geth every time. Even if I clear the whole folder it still downloads 1.8.2.
Because of this issue https://github.com/ethereum/go-ethereum/issues/16612 this breaks the light client and might be responsible for a few syncing issues here.

```
Version: `0.10.0`
OS & Version: windows
Node version: `geth 1.8.2`
```

**Comment by tocorobo** [comment]
I just tested this on a fresh VM. Downloaded https://github.com/ethereum/mist/releases/download/v0.10.0/Ethereum-Wallet-win64-0-10-0.zip unpacked the zip and ran the Ethereum Wallet.exe

After a few moments the following come into existence and both files are 37,255,611 bytes.
%userprofile%\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked\geth-windows-amd64-1.8.2-b8b9f7f4\geth.exe
%userprofile%\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked\geth.exe

The latter one is executed and starts running (since there is no manifest; all we have to go on is the filesize and the name of the geth folder in the unpacked dir seems to indicate it is version 1.8.2 (this correlates with the version reported via the UI at Develop>Ethereum Node>Geth 1.8.2).

Furthermore; if you manually over-write %userprofile%\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked\geth.exe with a newer version of the geth.exe executable; on next startup you'll notice "Downloading New Node" after which the exe in that directory is replaced once again with the v1.8.2 one.

**Comment by PhilippLgh** [comment]
Please see ethereum/mist-shell#7 for progress on this issue
