### ISSUE TITLE
Erhereum wallet won't load

### ISSUE THREAD

**Issue by davecam73** [ethereum/mist#3901]
Ethereum wallet getting stuck at node connected. Any solutions to solve this issue please?

```
Version: `0.10.0`
OS & Version: windows 8.1
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

[Files.zip](https://github.com/ethereum/mist/files/2020345/Files.zip)
[Screenshot.zip](https://github.com/ethereum/mist/files/2020346/Screenshot.zip)

**Comment by Libbzter** [comment]
I am having the same issue. I would think that the Mist wallet from Ethereum project would be the most stable. This does not seem to be the case. Please fix this!

**Comment by Libbzter** [comment]
The wallet seems to have synced for me now, but I tried to send some Ether, it seems to work as normally, but, did not actually send. It does not show up in the history, or on the blockchain. I don`t dare to try sending it again.

**Comment by jfgreen01** [comment]
Yep, same issue; won't ever find a peer for past couple weeks now. I tried syncing downloading chain structure and no go either. I have not been able to use my desktop eth wallet for tx in weeks.

Not sure why the ethereum developers are doing this; could you imagine the thousands of people that can't access the ethereum node? Is everyone supposed to use myetherwallet.com to load their wallets? Is this some kind of Joke?

Notice the Wanchain.org wallet is cloned from the ethereum client source code and literally has no issues finding peers instantly; downloads structure no issue, syncs perfect quickly and efficient every time as soon as wallet opens up to 21+ peer connections.

What's going on with this is just a joke. Kinda puts in perspective why would people use the eth network if they can't even access the node.

This is the first time ever I had to install the metamask chrome extension to make a transaction because I needed to make a transaction. Is this fair?

Can someone from the eth development comment on this?! How does Vitalik open the desktop client when he's traveling everywhere?! you tell me he's not getting the same issues.. bs.

who is this Lorezyra clown that just closes the posts with no solution in sight and claims issues are resolved.

**Comment by jfgreen01** [comment]
I can almost guarantee if this is not fixed while thousands of people can't access their wallets ethereum is going back to $100

**Comment by lorezyra** [comment]
@jfgreen01,
I'm **not closing** anything. If you bothered to see my post, you would see _I'm only trying to link the related issues_.
I'm in the same boat as most here. After evaluating Ethereum's officially recommended wallet, I'm ready to dump my coins and find a better project.

Best of luck to you...

**Comment by evertonfraga** [comment]
Hi! We have an updated version which drastically changes the way Mist syncs. After downloading version v0.11.0, please enable the Light Client (`Develop > Sync with light client)`

https://github.com/ethereum/mist/releases/tag/v0.11.0

I am closing this thread. If any of you still have any trouble **please feel free** to file a new issue or comment in an open one that better describes your situation.
