### ISSUE TITLE
presale import: password issue

### ISSUE THREAD

**Issue by justinxor** [ethereum/mist#436]
Node type: geth/eth
OS: osx
Network type: main/test
Mist version: 0.5.2

My presale wallet import password works on kraken's import website, but not on mist. Is it possible that you don't support special characters such as "/" or "*"? Cause my password contains those.

**Comment by hpjoe01** [comment]
Really I think so too.
I'm same situation now.

My password have "!" special character. Then I try import .json file to Mac OS X wallet but showing "wrong password"....

I really worry because I send message to support but no reply.

So this situation password including special character pre-sale .json file only can import from Kraken....
But little bit scare use Kraken anytime can happen like GOX.....

I really fix this problem ASAP.

**Comment by hiddentao** [comment]
This is a known issue and will be fixed in the next version, see #182.

Meanwhile you can still import your wallet (e.g. `my_wallet.json`) from the command-line:

```bash
$ geth wallet import my_wallet.json
```

**Comment by hpjoe01** [comment]
I understand.

Many thanks!

**Comment by alexvandesande** [comment]
fixed
