### ISSUE TITLE
I can't move funds from the contract wallet using the second owner's key

### ISSUE THREAD

**Issue by pacifics** [ethereum/mist#473]
I wanted to secure funds in a contract wallet using mist.
Two accounts. One with a password I know well and one with the password in a "safe".

I created contract wallet with the second account but it became the first one in Mist and I can't use the second account to transfer funds. Even if it is under dayly limit.

**Comment by frozeman** [comment]
Do you have enough ether to pay for the gas in the "owner" account, which created the wallet?

**Comment by pacifics** [comment]
31.47 finney.

**Comment by pacifics** [comment]
This owner account was created with Myetherwallet and I imported it.
The second account was created in mist and I want to use it for confirmation and only if need to transfer more then the dayly limit.

But the application wants me to use the second account to send fund.

Note : I have more than 30 finney in each account.

**Comment by frozeman** [comment]
It always takes the first owner as the one to send from the wallet. If you want to change the order of the owners you would need to do this over the console.

Open the console using CMD/CTRL + ALT + i

Then type: `Wallets.find().fetch()`

Select the object which fits your wallet, copy the `_id` property and the `owners` array content elsewhere.

Then switch the array positions of the owners, so that the one from mist, is first by writing:
```js
Wallets.update('the_idPropertyContent', {$set: {owners: ['0xthemistonefirst...', '0xtheotheronelast...'] }});
```

**Comment by pacifics** [comment]
Done. Thank you.
I suppose it will be possible to change the first owner without console in a next release.

**Comment by alexvandesande** [comment]
@pacifics we didn't consider a use case like yours and thought that in most cases users would have only one owner per machine. We will consider better ways to deal with this in the future, thanks!
