### ISSUE TITLE
MacOSX El capitan (latest) Mist (latest) not synchronizing

### ISSUE THREAD

**Issue by neuroether** [ethereum/mist#487]
Node type: geth
OS: osx
Network type: main
Mist version: 0.6.2

![screen shot 2016-04-09 at 20 55 13](https://cloud.githubusercontent.com/assets/18372744/14407603/66fcceb6-fe95-11e5-834a-d25c4e6ae56a.png)
![screen shot 2016-04-09 at 20 58 29](https://cloud.githubusercontent.com/assets/18372744/14407613/da028d9c-fe95-11e5-925e-371fde12d366.png)

![screen shot 2016-04-09 at 20 56 46](https://cloud.githubusercontent.com/assets/18372744/14407609/a01e552a-fe95-11e5-88f2-75aeb39d298f.png)

**Comment by hiddentao** [comment]
From the logs it looks like it is fetching blocks from the network ok. Is it that the Mist GUI freezes and/or doesn't progress forward?

**Comment by bas-vk** [comment]
It looks like block import is really slow. Synchronization started at 20:38:51 and the first 2 blocks are imported 22 seconds later. This is not uncommon when the synchronization process just starts. Depending on how fast peers are found and how fast these peers are able to send you data it can take some time. When faster peers are found the block import speed will increase (if its a peer related issue).

Since you are ~80.000 blocks behind importing 2 blocks will be such a small progress that you won't see any change in the progress bar. Could you let us know if this is still a problem?

**Comment by neuroether** [comment]
Thanks I ran a geth brew upgrade and update and the synchronization got faster and in 24hrs was up to date. Thanks for the support!

**Comment by neuroether** [comment]
Thanks I ran a geth brew upgrade and update and the synchronization got faster and in 24hrs was up to date. Thanks for the support!
