### ISSUE TITLE
mist error after electricity was cut suddenly

### ISSUE THREAD

**Issue by tanitpunique** [ethereum/mist#489]
Node type: geth/eth
OS: windows 7/
Network type: main/test
Mist version: 0.5.2

- Screenshots

[fichier erreur ethereum mist.docx](https://github.com/ethereum/mist/files/213037/fichier.erreur.ethereum.mist.docx)

**Comment by bas-vk** [comment]
I don't speak French so its hard to understand what the actual problem is. It seems that the directory where the block chain data is stored is corrupt. Could you verify that you are able to access `c:\Users\mediscience\AppData\Roaming\Ethereum` and `c:\Users\mediscience\AppData\Roaming\Ethereum\chaindata` in explorer?

If not then the filesystem is corrupt and your best way forward to solve this is probably to remove `c:\Users\mediscience\AppData\Roaming\Ethereum`. Please make sure you have a backup of your keys in case there are one that are valuable for you. If you are able to access them then the database file is corrupt which can happen when not properly shutdown. In that case remove `c:\Users\mediscience\AppData\Roaming\Ethereum\chaindata` and `c:\Users\mediscience\AppData\Roaming\Ethereum\dapps` and restart mist. It will synchronize from scratch.

**Comment by luclu** [comment]
@tanitpunique Did @bas-vk answer helped to resolve your problem?

**Comment by alexvandesande** [comment]
It says your a file inside chain data was rendered corrupt. Delete that file (or the whole directory) and sync again.
