### ISSUE TITLE
extremly slow sync on mechanical HDD

### ISSUE THREAD

**Issue by saulhudson1** [ethereum/mist#518]
Node type: geth
OS: windows 7
Network type: main
Mist version: 0.7.1

my sync has been left on over three nights now and are still only at block 850k out of 14 000k, roughly 50%.
When i test my line it gives something like 40/10 Mbit.
Is there something to be done?

**Comment by luclu** [comment]
@saulhudson1 please edit your issue to include your OS, Mist version and the backend-client (geth, if you just downloaded the Wallet).

Three night seems too long. Just some groundwork: You might try to restart the Wallet to get a fresh set of peers to download from. What is your CPU utilization? What kind of storage are you using?

**Comment by frozeman** [comment]
@luclu this is a reoccurring issue and im already aware of this, as well as the go team (which needs to fix it). You can link these issue with the first one on this subject, and i can close the duplicates.

**Comment by saulhudson1** [comment]
@luclu  thanks, updated! im still leaving it syncing each night, up att approx 75% now and counting. 
CPU at bout 10-30% and ram at bout 50%, regular laptop mechanical hdd.

**Comment by luclu** [comment]
related: #439 
Updating to SSD helped - though this might **not be** the real solution.

**Comment by robonix** [comment]
I have a similar problem

I'm using a Lenovo laptop with 6 Gb of RAM with a 100 Gb SSD
Processor: i5 
OS: Windows10 x64
Network type: main
Mist version: 0.7.2
Internet Speed: 10Mbps

Also I've constantly looked at my CPU, Ethernet, SSD, and RAM usage and the numbers are always within normal operating tolerances.

I've been trying to sync the wallet for over a month now without any luck.
Everything seems to start out OK but then the download starts hanging and if i just leave it (as I have in the past for just under 72 hours) it just hangs and will stay stuck on the random block it decided to stop syncing. The only way I can get the sync process to continue from where it left off is to close Mist wait a minute or so and start it up again.

It was a slow and tedious process but on my first try I got some where around block 500,000, but it was taking forever (this was back when Mist version was 0.7.1) so I erased the content in the chaindata file and started over thinking the download might have goten off to a bad start because I was having internet isues. Unfortunately (even though I had resolved to see the sync process to the end the second time around) the sync process hanged at a little past block 1,000,000 and no mater how many times I restarted Mist or how many nights I left my computer on hoping it would start synchronizing again, I had no choice but to start the process over again.

It has been 6 times that I've started the process over and every time the sync hangs indefinitely at some random point between block 650,000 and 1,000,000.

Does any one have any ideas as to what the problem might be and what I can do to fix it?

Thanks in advanced :)

**Comment by luclu** [comment]
Go-Team is working on this during the next release line 1.5:
> We're aware of abysmal hdd performance. We have 2-3 prs pending for 1.5 that will significantly improve performance (3-4x). We're also prepping state trie pruning which should solve scalability issues for the mid-term.

**Comment by luclu** [comment]
Just to keep you updated on some developments and minor performance improvements during the 1.4 line: https://github.com/ethereum/go-ethereum/pull/2585

**Comment by karalabe** [comment]
We're planning a DB reorg that will make geth work on HDDs an order of magnitude faster. Half of it is done, another half is yet to be done. Results until now confirm that the speedups are significant.

**Comment by Shadowstep33** [comment]
Not sure if it really helps but I noticed when I exit Mist I can see geth still running in taskmanager

**Comment by evertonfraga** [comment]
Issue closed due to inactivity. Please reopen if problem persists.

**Comment by jurajseffer** [comment]
This is still the case. I'm unable to sync with Mist 0.9.0 on a 1TB mechanical hard drive. It's too slow to catch up with new blocks, saturating HDD usage to 100%. I have tried several times by wiping out chaindata folder and doing the fast sync. It gets reasonably quickly to 4.2M blocks but then goes one block per 2 seconds.

**Comment by bcp-software** [comment]
Agreed with @jurajseffer , still a major issue.

**Comment by internalfx** [comment]
Seeing this as well
