### ISSUE TITLE
Do I really have to pay to create a wallet to deposit money?

### ISSUE THREAD

**Issue by stefek99** [ethereum/mist#52]
I'm confused.

I clicked on "create wallet".

As opposed to "create contract".

Do I really need to spend ETH (that I don't have) to create wallet and deposit ETH?

![screen shot 2015-10-15 at 08 09 28](https://cloud.githubusercontent.com/assets/249703/10506901/577377d6-7314-11e5-90b7-ef0b515ed154.png)

(and of course message *account does not exist or not enough funds* can be more specific)

So alpha, I was warned. I like software that talks nicely to me: https://twitter.com/stefek99/status/654391430803288064

**Comment by alexvandesande** [comment]
The wallet is a contract, which you can use to have multiple owners – and because for technical reasons pure accounts can't keep logs, so that's why you need ether to create a contract. We are looking into how to better differentiate accounts and wallets. 

I will look into better error messages, thank you!

Yes, I know that the wallet is rather frustrating if you don't have any ether, but we will make a nicer on boarding process in the future that will guide the user to the steps of setting up everything to get some ether..
