### ISSUE TITLE
How to fix the corrupted/missing blockchain data?

### ISSUE THREAD

**Issue by More-decentral** [ethereum/mist#581]
Probably due to false positive of antivirus software, the blockchain data files under **~/Library/Ethereum/Chaindata** on my Mac are probably corrupted or have missing pieces.

How can I re-download or re-sync the Ethereum blockchain?   Should I delete all the data files (.ldb) under **~/Library/Ethereum/Chaindata**?

OS:  Mac OSX  10.10.5
Ethererum wallet: 0.7.2

**Comment by wynem** [comment]
I also encountered this problem today. 

Waiting on solution.

**Comment by obscuren** [comment]
I have seen reports of actors uploading the **binary** of a virus on to the Ethereum blockchain, which by itself does **nothing** (because a binary needs to be executed in order to be effective). AV software will see this and quarantine the piece (the `.ldb` file) and this causes the Ethereum chain to be corrupt. If your AV software has a way to "undo" the changes and place it out of quarantine, please do so and **do not delete** it. If you've delete it you need delete the `chaindata` folder and restart the client.

We're looking in to this "issue" and looking whether there's anything we can do to prevent the AV software from going off.

**Comment by luclu** [comment]
I will close this as this issue was pooled in https://github.com/ethereum/mist/issues/573.
