### ISSUE TITLE
Balance wont update

### ISSUE THREAD

**Issue by Neonian** [ethereum/mist#605]
Node type: geth
OS: windows 64
Network type: test
Mist version: 0.7.2

My balance of ETH does not update on my wallet. Wallet (TEST-NET) is fully updated (not the Main Network), so did i make a mistake couse i sent the ETH on the test-net account? 
Is it possible that the balance is not updated due to not fully updated "main network" ? 
ETH should be "there" just that is doesnt show it, it is still possible to send it somewhere? 

![noeth](https://cloud.githubusercontent.com/assets/19249152/15176906/acc67fdc-176d-11e6-988b-bccc8f7bb824.png)

**Comment by luclu** [comment]
@Neonian unfortunately you send **main-net** ether to a **main-net**-address you don't control. Sadly there is no way to recover it.
In futue releases there will be alerts when **test-net**-addresses are copied.
Regarding the visual identicons - they are the same for the same address on any (private or test) network due to the nature of the encoding.
I'm sorry for the inconvinience.

**Comment by Neonian** [comment]
WoW, well, you live and you learn.

ty :+1:

**Comment by alexvandesande** [comment]
Actually you can recover it. Go to your backup folders, find a ethereum/testnet/keystore and move the contents to the ethereum/keystore
