### ISSUE TITLE
ETHER WALLET WONT SYNC

### ISSUE THREAD

**Issue by MrMontana** [ethereum/mist#623]
When starting my Ether Wallet is syncs for about 10 mins and then stops....very little. Then have to close it does the same. I have tried 30+ times.

![screen shot 2016-05-13 at 9 11 30 pm](https://cloud.githubusercontent.com/assets/19239031/15246356/9dea4c9e-194f-11e6-8f3b-aaf0121cfc5e.png)

**Comment by luclu** [comment]
Please provide these information:

Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

**Comment by Wat3v4** [comment]
Yeah happens to me too, on both PC and Mac..
What I found to work for me was to press "skip" and let it run a little and then it starts to sync on the wallet UI itself.. 
It tends to get stuck less in that state..

**Comment by m0se** [comment]
Maybe you can start `geth --fast` and let geth sync on it's own before starting the wallet UI. How you do that depends a little on:
>OS: linux/windows/osx

**Comment by Wat3v4** [comment]
@m0se How to do that on OS X?

**Comment by m0se** [comment]
It's been a while since I last played with mist on osx, but essentially you need stop Ethereum Wallet completely first and then open a Terminal and start `geth --fast` there. For that you need to find the path to the geth binary shiped with Ethereum Wallet. It should be something like `/Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth` (asuming you put Ethereum-Wallet.app in to /Applications).

Maybe check first with running something like:
```
/Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth help
```
In the output of that you can check in the section "ETHEREUM OPTIONS:" if the default --datadir points to the right place.

Then you can start geth with:
```
/Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth --fast
```

It takes a few moments till it starts downloading blocks and when it does you should be able to see out put in the terminal every few secs that blocks has been downloaded mostly 256 blocks at once. When it starts to show entries with only one block ever few secs for some time then it's done and you can stop geth in the terminal with `ctrl+c` and try to start the Ethereum Wallet again.

**Comment by MrMontana** [comment]
@luclu 

Node type: geth 1.3.6
OS: osx
Network type: main
Mist version: 0.7.2

**Comment by MrMontana** [comment]
@m0se thats some tech lingo I dont get but the app has no folders to access from the finder, it just open right up and come with some txt docs

**Comment by m0se** [comment]
Sorry, I think there are not a lot of ways to explain that simpler without filling pages. Just tried to provide a instruction to @Wat3v4 since he asked for osx.

I don't think there is a graphical way to do this with Finder, for the `--fast` option you need to use "Terminal.app" to start geth. You could right-click on Ethereum-Wallet.app and choose "Show Package Content", then you can navigate to geth with Finder, but this won't help since just doubleclick geth will not start it with `--fast` for that you need to do it in the Terminal-app sorry.

@Wat3v4 one additional thing I forgot to mention, for the `--fast` option to work your chaindata folder.needs to be empty.

**Comment by MrMontana** [comment]
@m0se thanks mate - I actually followed you r instructions and worked it out though I dont know what the chaindata folder is, can you direct me to doing that please?

**Comment by MrMontana** [comment]
@m0se been like this for 10 mins now
![screen shot 2016-05-13 at 11 35 23 pm](https://cloud.githubusercontent.com/assets/19239031/15249550/72fede5a-1963-11e6-9b84-776a7728660b.png)

**Comment by m0se** [comment]
Maybe hit `ctrl+c` and give it another try. 
How are your system resources, I got that a few times when to much stuff was running on my old Mid-2012 MBA 4GB (with linux). Additionally I'm not sure if the `--fast` is just ignores, when chaindata contains data, but I seem to remember seeing a warning about --fast not beeing used due to allready containing data in blockchain directory.

Since I don't run OSX anymore I can't check where the caindata folder is located, but it's next to the keystore folder (in case you already found that for backup or something) in geth's datadir. check `geth help` to see the default value of `--datadir`. I think it is something like /Users/<you>/Librarry/??/chaindata.

**Comment by MrMontana** [comment]
Everything is  closed so should be running well. (2011 macbook pro)

Are these folders in the Finder?

**Comment by m0se** [comment]
Yea, you should also be able to find them in Finder,.. 
Try something like this in the Terminal:
```/Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth help|grep datadir```

..then you should get output like this and see the path to the folder:
```
  --datadir "/home/username/.ethereum"      Data directory for the databases and keystore
  --keystore                            Directory for the keystore (default = inside the datadir)
  --ipcpath "geth.ipc"  
```
(but that's linux, yours will probably contain "Librarry/.." on osx)

**Comment by MrMontana** [comment]
Ive done that in terminal. But what there is the folder? Please remember I am an everyday computer user...no tech or code knowledge. This s what came up...now what?
![screen shot 2016-05-14 at 12 13 55 am](https://cloud.githubusercontent.com/assets/19239031/15250572/c9090690-1968-11e6-907a-2f3d663f34c2.png)

**Comment by m0se** [comment]
Easiest with finder is probably to use menu "Go->Go to Folder" and then copy&past the "/Users/.." path from Terminal. I had forgoten that Apple hides the user's Librarry folder in Finder, but with Go to Folder it shoud open that folder in Finder anyway.

**Comment by MrMontana** [comment]
Thanks. I did that, founf and emptied everything out of the chaindata folder. Puththe -- fast command line in and it has fatal error...see below:

Fatal: dapp db err: resource temporarily unavailable (check if another instance of geth is already running with the same data directory '/Users/joshuataylor-anderson/Library/Ethereum')

**Comment by MrMontana** [comment]
ive just started ethereum agan and it started from 0 and moving well...sound sorted?

**Comment by MrMontana** [comment]
Goodamn it...spoke to soon...froze at 47,000

**Comment by MrMontana** [comment]
@m0se thank you for your help, I ended up deleting the whole program and re-downloaded. Up and running now with old keys loaded up. :)
