### ISSUE TITLE
Need ETH to create contract to receive presale ETH

### ISSUE THREAD

**Issue by belgacoin** [ethereum/mist#64]
Hello,

I'm already in contact with ETH helpdesk. Because I have an issue with my presale wallet, they asked me to download and install this GUI wallet.
My GUI wallet has 0 ETH, so I can't create a wallet/contract to receive my presale ETH on it. How do I proceed? (attached screenshots)
Thanks for your feedback.

![schermafdruk 2015-10-23 14 43 11](https://cloud.githubusercontent.com/assets/4160284/10710123/7b08a7b0-7a4a-11e5-9ba3-b4be02b95527.png)
![schermafdruk 2015-10-23 14 43 25](https://cloud.githubusercontent.com/assets/4160284/10710124/8179d92a-7a4a-11e5-92d0-ea37012816fb.png)

**Comment by frozeman** [comment]
You don't need to create an contact based wallet to receive ether.
If you want to import you presale wallet file, you currently need to import it using the `geth` commandline:
`geth wallet import /path/to/my/etherwallet.json`

**Comment by belgacoin** [comment]
thanks, can I receive ETH on the contact based wallet (e.g. from exchange)? I see this tx in the blockchain but not in my wallet.
thx

**Comment by belgacoin** [comment]
So the address I'm talking about is 0xf9c83464421372e632fd335ce046425c2166abce.
If I check https://etherchain.org/account/0xf9c83464421372e632fd335ce046425c2166abce#txreceived
I see two received TX but only the first (5 ETH) is visible in my wallet (the contract based one).

Also, I'd like to ask if I can find the private keys in the Ethereum folder in /Library (on my mac)
Thanks again!

**Comment by frozeman** [comment]
The gas provided was not enough and therefore the money never arrived, You need to contact @poloniex and tell them that they should provide at least 50k gas, otherwise tx into the wallet will fail.

The money is still at their account .

See here: https://etherscan.io/tx/0x4e79aec6f01ec0d8e720351aa9f0d25241f66e6121be1b6b158d884b0f2dc9a4

The gas used is the same as the gas provided, so it seems they didn't provide enough.
We will add an `outofgas` property to the receipts.

**Comment by belgacoin** [comment]
thanks, I will contact them asap.

**Comment by belgacoin** [comment]
That turned out well. Poloniex send it again with enough gas this time. 
Enjoy the weekend ;)
