### ISSUE TITLE
Add contact feature

### ISSUE THREAD

**Issue by SebastianBoyd** [ethereum/mist#69]
There should be a way of storing the addresses of other people without their password so you can easily send them ether without having to type out their address.

**Comment by frozeman** [comment]
Will come

**Comment by jtoomim** [comment]
+1. It is common for people to repeatedly send money to the same person due to ongoing business relationships. Having a list of known recipients with human-readable nicknames will make that common use-case much easier.

Today I sent around 80 ether to the wrong person because I got two of my frequent-payees' addresses confused. If we had had this feature, I probably would not have committed that error.

**Comment by luclu** [comment]
@jtoomim I'm very sorry to hear about this. This important feature is planned an might be implemented in the `0.9.x` line due to our limited resources.
I will close this one as a duplicate of:
>  Add addressbook-functionality #201
