### ISSUE TITLE
password on eth wallet 0.7.3. doesnt work

### ISSUE THREAD

**Issue by Drummz** [ethereum/mist#701]
Node type: geth/eth
OS: osx
Network type: main/test
Mist version: 0.7.3

i already tried to sync my wallet a few times and after i dont know 20 times wallet synced.
But when i tried to send some eth on another address it was writen first that it couldnt connect with the nodes...ok... but after that problem my pasword didn't work anymore. I have pass which i created on the beginning but it doesnt work...

Any expirience with that?

**Comment by Kojee** [comment]
Have you tried updating your password trough Geth? You can download it here [Geth](https://github.com/ethereum/go-ethereum/releases), then open a cmd in the folder you downloaded it and inserting the command `geth account update ` and then the number of the account you want to update( for instance if you have only one account you can  write 0, or you can insert geth account list to see every account), and then inserting your password. If it's correct it will ask you to change it.
Try this way to at least see if you remember your password correctly, because Mist often didn't send transaction because of the "couldn't connect with nodes" error.

**Comment by Drummz** [comment]
Thank you very much for your answer. I will try it that way!

--
Lep pozdrav/Kind regards/Atenciosamente
 
Anže Žurbi – Zurby

musician, independent cultural worker, drum teacher, ambassador at Different Company, endorser at Manicdrum Company, independent LEO member
 
Phone: 
SI - 00386 40 552 884
BRA - 0055 11 97555 3221
Mail: 
zurbydrums@gmail.com, 
zurby@different-eye.com,
Zurby@leobrasil.net
Anze.zurbi@krypterix.com
Skype: groovykindof70
Web: 
www.facebook.com/Anze.Zurbi, 
www.different-eye.com,
www.myleobusiness.com/zurby,
www.leocoin.org
www.leoxchange.com

**Comment by luclu** [comment]
@Drummz also make sure to check out these recommendations: https://github.com/ethereum/mist/issues/669

**Comment by luclu** [comment]
I will close this for now.

**Comment by Drummz** [comment]
I am on tour and i didnt try it yet. I will let u know if it works. Thank you

--
Lep pozdrav/Kind regards/Atenciosamente
 
Anže Žurbi – Zurby

musician, independent cultural worker, drum teacher, ambassador at Different Company, endorser at Manicdrum Company, independent LEO member
 
Phone: 
SI - 00386 40 552 884
BRA - 0055 11 97555 3221
Mail: 
zurbydrums@gmail.com, 
zurby@different-eye.com,
Zurby@leobrasil.net
Anze.zurbi@krypterix.com
Skype: groovykindof70
Web: 
www.facebook.com/Anze.Zurbi, 
www.different-eye.com,
www.myleobusiness.com/zurby,
www.leocoin.org
www.leoxchange.com
