### ISSUE TITLE
Mac OS X Mist: 0.3.5 Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by santyr** [ethereum/mist#71]
I'm unable to send ETH in any amount from my wallet.  It always throws " Insufficient funds for gas * price + value".  I've tried deleting all the files under ~/Library/Ethereum and ~/Library/Application Support/Mist and restarting, but this hasn't helped.  Any thoughts on how to troubleshoot and correct?

**Comment by frozeman** [comment]
This means you don't have enough money in your owner account, as this is the one who pays for the gas

**Comment by santyr** [comment]
Thanks. Adding more funds to my owner account from another (external) account did the trick.   I'd probably categorize this as a bug, since it's possible to transfer enough funds from one's owner account into his wallet that the funds effectively get "stuck" until more funds are added to the owner account.

**Comment by frozeman** [comment]
But thats how the ethereum system work. We could write the contract in a way that it refunds the owner at all times, so the funds there never run out, but apart form that its how accounts own contracts.

The owner/actor always pays the gas ;)

**Comment by alexvandesande** [comment]
>  since it's possible to transfer enough funds from one's owner account into his wallet that the funds effectively get "stuck" until more funds are added to the owner account.

We will handle this by rewriting a new wallet contract that refunds the owner for gas usage.

**Comment by slava-vishnyakov** [comment]
Frankly, for a newbie that message is kind of scary. At first it sounds scary, kind of like "you can't move your money anymore". I'd say that this message could use a little more helping points, like "You can send no more that XX finney" or "You need to add XX finney to your account "Main account" in order to proceed with transaction".

**Comment by frozeman** [comment]
This is an error from the node, which i simply pass through. Yes we could improve it, but we don't have a nice technical solution for this yet (E.g. error codes), which let me do this properly

**Comment by slava-vishnyakov** [comment]
Pity. Should we maybe open a new bug to track this idea?

**Comment by frozeman** [comment]
Exists since a long time ;)
https://github.com/ethereum/go-ethereum/issues/768

**Comment by slava-vishnyakov** [comment]
I mean for a better message in this case, because this is one of the first things that a newcomer to Ethereum sees. I mean - the codes are a prerequisite, but the main idea is that in this particular case we need something that shows not only the nice error message, but also a solution (something like "Add XX ether to your main account"). Otherwise, even with a nice message like "We can't transfer your money" it might be confusing :)

But anyway, thanks for the info! :+1:

**Comment by ScrambleKid** [comment]
I'm having the same problem, however I can't transfer funds to my main account for the same reason (not enough for gas) and I don't have an external account to transfer from. So now what?
