### ISSUE TITLE
The wallet is showing 9 times the amount of dao tokens i actually own !?!?!?!?!! 

### ISSUE THREAD

**Issue by Guido1234** [ethereum/mist#734]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by mruepp** [comment]
This is what happens when I manually import the Presales Wallet from DAO:

Passphrase:
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x4a9b5e0, 0xc820012090)
	/Users/jeffrey/goroot16/src/runtime/panic.go:464 +0x3e6
github.com/ethereum/go-ethereum/accounts.decryptPreSaleKey(0xc8203f1000, 0x1ea, 0x3ea, 0xc820011560, 0x12, 0x8, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/accounts/presale.go:56 +0x7b6
github.com/ethereum/go-ethereum/accounts.importPreSaleKey(0xadc9808, 0xc82040e0e0, 0xc8203f1000, 0x1ea, 0x3ea, 0xc820011560, 0x12, 0x0, 0x0, 0x0, ...)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/accounts/presale.go:34 +0x8c
github.com/ethereum/go-ethereum/accounts.(*Manager).ImportPreSaleKey(0xc82040ab00, 0xc8203f1000, 0x1ea, 0x3ea, 0xc820011560, 0x12, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/accounts/account_manager.go:316 +0xb3
main.importWallet(0xc8203d2f00)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/cmd/geth/accountcmd.go:300 +0x387
github.com/codegangsta/cli.Command.Run(0x4bf2850, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4d08160, 0x1e, 0x0, ...)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:174 +0x1399
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc8203d2c80, 0xc8203d2b40, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:298 +0x11c9
github.com/codegangsta/cli.Command.startApp(0x4bf7170, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4cb27e0, 0x17, 0x0, ...)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:249 +0x74f
github.com/codegangsta/cli.Command.Run(0x4bf7170, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4cb27e0, 0x17, 0x0, ...)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:65 +0x79
github.com/codegangsta/cli.(*App).Run(0xc8203d2a00, 0xc82000a280, 0x4, 0x4, 0x0, 0x0)
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:187 +0x112b
main.main()
	/Users/jeffrey/go/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:266 +0x53

**Comment by mruepp** [comment]
What I actually did was I copied the json on the DAO Website into a txt file and named it presale-wallet.json. Because i never had the option to download the wallet as a file.

**Comment by luclu** [comment]
Guys please don't hijack issues and take your time to file them.
