### ISSUE TITLE
Ethereum wallet froze and now shows unknown failed transactions 

### ISSUE THREAD

**Issue by daraosn** [ethereum/mist#743]
Node type: geth
OS: osx
Network type: main
Mist version: 0.7.4

So last night, I upgraded from 0.7.2 to 0.7.4, after launching my Ethereum Wallet, it completely froze for some time. At the beginning when launching, it was responsive, but little by little it started to become slow until it rendered unresponsive.

<img width="939" alt="mist-wtf" src="https://cloud.githubusercontent.com/assets/1020989/15634482/33ac14de-25c5-11e6-9ec8-0c9fa12b398a.png">

I closed it, and today I received several notifications of transactions failed (which btw I didn't make), and some of them are listed here... I have no idea which addresses are:
https://etherscan.io/address/0xdf21fa922215b1a56f5a6d6294e6e36c85a0acfb
https://etherscan.io/address/0x8B3B3b624c3c0397D3da8Fd861512393d51DCbac

My ETH and DAO tokens balance seems to be good.

But most importantly, why did this happen ?
Is it related to https://github.com/ethereum/mist/issues/739 ?

**Comment by dennyuel** [comment]
Have the same problem, plus my DAO token balance isn't correct either...

**Comment by FaguiCurtain** [comment]
see here
https://forum.daohub.org/t/transactions-that-i-dont-recognize-showing-up-in-mist/3695/13

**Comment by luclu** [comment]
thanks @FaguiCurtain. [iamtrillion](https://forum.daohub.org/t/transactions-that-i-dont-recognize-showing-up-in-mist/3695/17) wrote:

> pls note, if you see some transactions showing up in your mist, its not because there has been a compromise, its because you are seeing transactions of SOME people WHO are sending to the DAO contract address instead of their wallet address(its showing up in mine too).
Thus all our watch token values have increased by atleast 40,000+, as at 10mins ago the DAO has 56,372.49654952 tokens due to the last 17 people(wallet addresses) who sent their tokens to DAO instead of their own wallet addresses.
That is why your watch token values has greatly greatly increased but the token values for each address in your wallet is correct.
