### ISSUE TITLE
Regular release cycle - ship early, shop often

### ISSUE THREAD

**Issue by hiddentao** [ethereum/mist#758]
I propose that we release regularly with Mist, specifically **every 2 weeks or every month**. My rationale for this as follows:
- Releasing regularly keeps us on our toes in ensuring that the product is continually fit for purpose
- It users confidence in us, knowing that they will get an improved product soon
- It makes the internal progress we make on Mist clearly visible to the external world very effectively
- It forces us to better prioritise what items need to be worked on for the next release 
- It allows us to test what we build sooner by putting it into the hands of users

In order to accomplish regular releases we need:
- Continuous integration and testing which automates UI testing
- A robust, core product. The core functionality of the app has to be solid across all supported platforms
- Regularly sorting and curating of Github issues and milestones
- A process for determining what issues should go into the next release - this could perhaps be a discussion during our team meetings. Or maybe we don't decide every single item that goes in, just a few major ones, and then simply release with what's available at the time. 
- An acceptance that we may not always finish every ticket assigned to a release. This is ok as we can push tickets down to the next iteration. But the release must still go ahead if useful work has been done.

**Comment by hiddentao** [comment]
Right now we have milestones 0.7.5 and 0.8, with all long-term work happening in 0.8. This can be kept as is. What I'm saying that after 0.7.5 is out we should do the next short term release(e.g. 0.7.6) soon afterwards, and so on.

**Comment by ravno** [comment]
Where one can see the dates for the next releases ? Really looking for upgrade to the last 0.7.4 (which more often isn't working then working)

**Comment by larrysmith1000** [comment]
Yes, when is 0.7.5 released?

**Comment by davedavis** [comment]
Great idea. I think there's a lot to be said for smaller more frequent releases. In general, when a frequent schedule has been established, users are more patient. People cannot understand why the current issues, which they consider critical, have not been fixed yet. 

Look at Jaxx as a really good example of this working well. They had some serious bugs and many were not fixed in the next release (or even the following one) but their users knew that they could expect a new release in the coming days/weeks and that their reported bug would be gotten around to eventually. 

Right now, I think Mist is starting to develop a significant reputation issue. Not all users read the issue list or Gitter. All they see is a (relatively) long gap since "anyone bothered to do anything". Rapid, smaller releases can have a disproportionate benefit to credibility and trust. Regular smaller updates beat out big updates spaced further apart every time for client applications in most cases. Even the smallest of releases can be seen by the average user as "heavy development" and that can be enough to appease non critical complaints. Without a PR/Marketing team, right now, the mood is somewhat of a "they're doing nothing to address this massive problem". 

Setting up CI is definitely worth the effort, especially when it turns users into champions rather than "customers" that need to be placated. In fact, CI doesn't even need to be implemented for this aspect to work well. Just regular, predictable releases. It doesn't necessarily matter what's in those releases. It would also free up a lot of development time not having to respond to an escalating volume of the same questions as people get more and more annoyed over sync/memory leak/copy & paste etc. They'll know it's probably going to be fixed in the next 2-3 cycles so no need to bother asking. Because right now, people are complaining because they feel that there has been such a long delay in a fix that you must not know about it so if they don't report it (or in this modern age, complain about it on social media), then it hasn't even been acknowledged yet. 

Frequent releases can be seen as a cheap form of PR in that sense. Communication is all that is required in many cases and the communication method that will reach the most people is a release (with a changelog/change toast of course). 

We've actually done some research on this area outside of development too and users are happier when communication of ANY sort is made, even if it's negligible updates. 

Of course all your other reasons are valid too :)
