### ISSUE TITLE
Strange transaction listed in Mist from an account I don't control

### ISSUE THREAD

**Issue by mrcybermac** [ethereum/mist#781]
![screen shot 2016-06-05 at 1 35 33 pm](https://cloud.githubusercontent.com/assets/6118944/15809154/3e8cdd5c-2b47-11e6-9e7c-30614a52bc26.png)
I turned on my Mist Wallet this morning, and once it finished loaded, I saw an osX notification that a transfer had been made in the middle of the night while I was sleeping.  Huh?  Needless to say this scared me so I investigated further inside Mist itself.  The Mist wallet is listing in the  'recent transactions' list a transaction that was sent from an address that I have no control over, is not in my wallet, and it sent to the DAO.

http://etherscan.io/tx/0xe9c0a9d9bac6f1b787572ce013068e6a791bad7fadfc5cc62b5b8b082a3db631

This is not a transaction from any of the accounts in my wallet.  Why is it being listed as if I sent this transaction in my own wallet?  This must be a defect right?  I can't see any legitimate reason why I'm seeing this transaction.

![screen shot 2016-06-05 at 1 35 33 pm]

Thanks,

(https://cloud.githubusercontent.com/assets/6118944/15807774/6d11ff96-2b23-11e6-98ec-c1c1549cb0ac.png)
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by LukaszOls** [comment]
Hi,

This is not an issue with Mist. In fact it is most likely doing exactly what it should if you're watching The DAO contract.

You're seeing the transaction because you're watching The DAO and someone (probably by mistake) sent their DAO tokens to the DAO address. Looks like many people made similar transaction in last few days so I would be more concerned with a fact we don't see more of them (I can see this transaction in my Mist as well, see below) 
![image](https://cloud.githubusercontent.com/assets/19762237/15813867/40ddb4d2-2bba-11e6-85f9-783cb08e48c5.png)

This is the list of recent transactions with D tokens sent to The DAO address: http://etherscan.io/token/TheDAO?a=0xbb9bc244d798123fde783fcc1c72d3bb8c189413

I'm not sure why we are not seeing all of those, but I'm not convinced it is a bug.

Anyway, for anyone who sent his/hers tokens to The DAO address there is a proposal here: https://www.reddit.com/r/TheDao/comments/4mbg7r/proposal_40_tokens_sent_to_thedao/ for them to be returned automatically in future.

**Comment by mrcybermac** [comment]
Thanks!
