### ISSUE TITLE
fix eth (c++) node

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#834]
Current issues: https://github.com/ethereum/mist/issues/607
Ongoing PR: https://github.com/ethereum/mist/pull/841

**Comment by luclu** [comment]
Update script still outstanding.
Pinging @hiddentao

**Comment by hiddentao** [comment]
Yeah, we're waiting on the Eth team to do something about people have previously set master passwords.

**Comment by bobsummerwill** [comment]
So my repo-reorg work is coming within touching distance of going live.

You can preview it at https://github.com/bobsummerwill/cpp-ethereum/tree/merge_repos.

And example ZIPs, if you want to play around ... https://github.com/bobsummerwill/cpp-ethereum/releases/tag/develop-v1.2.9.282

The new Appveyor/TravisCI automation includes the fix for the dylib paths, so you won't need to do any post-processing anymore - just drop the content into your folder.

We have merged a fix related to master password which I think is the same as you are referring to above (@chriseth?) - https://github.com/ethereum/webthree/pull/187.    Or is the issue referred to above something different?

And the toggle will need re-enabling too, eh?

There is a chance we will do a cpp-ethereum-1.3.0 release tomorrow, or if that doesn't happen then certainly on Tuesday.     We'll be back in https://github.com/ethereum/cpp-ethereum, and the webthree-umbrella era will be over.

**Comment by hiddentao** [comment]
@bobsummerwill ethereum/webthree#187 looks like what we need - I'll comment in there for clarification.

**Comment by luclu** [comment]
Version `1.3.0` [bob's repo](https://github.com/bobsummerwill/cpp-ethereum/releases/tag/v1.3.0) should work as the following issues have been resolved:
 - not HF compatible
 - old master-passwords (created before version `1.2.9`) will stall the communication to the node
 - and your case `eth_sendTransaction` was depreciated and removed due to an vulnerability and replaced by `eth_unlockAccountAndSendTransaction` which is not implemented in `1.2.9` - which prevents using the send function

Version `1.3.1` should be released in the following days.
We might want to externalize the eth nodes from the repo to prevent further growing:
>  download eth-nodes with gulp / remove from repo #894

**Comment by bobsummerwill** [comment]
Yeah - on-demand download would make sense to avoid repo-bloat.

Aside - you can ditch https://github.com/ethereum/mist/blob/develop/nodes/eth/fix_darwin_paths.py too with v1.3.0.

I fixed that missing automation step during the Jenkins -> TravisCI migration.

It will literally be ZIPs from Github to grab-and-unzip.

**Comment by bobsummerwill** [comment]
Here for now:
https://github.com/bobsummerwill/cpp-ethereum/releases/tag/v1.3.0

Moving very soon to:
https://github.com/ethereum/cpp-ethereum/releases/tag/v1.3.1

I've also added OS X Mavericks support back into our matrix (because only Mavericks binaries run successfully on the 2009 era Mac Pro hardware which TravisCI is running on).    No doubt if I monkeyed around with -march settings I could build a single set of binaries which worked for all OS versions ON El Capitan, but I've done bothered with that yet.

So we have:
- Windows x64 (min-spec we're saying Windows 7, but I think that might actually work back to Vista)
- Ubuntu Trusty x64 (but the ZIP isn't fully standalone, though I hope to get there with static linkage binaries on Alpine using musl)
- OS X Mavericks, Yosemite and El Capitan (all x64)

We're not building any 32-bit binaries right now, either for Windows or Linux, but the build works from source, and I would like to re-add those soon enough.

**Comment by luclu** [comment]
Thank you Bob for your efforts!
> No doubt if I monkeyed around with -march settings I could build a single set of binaries which worked for all OS versions ON El Capitan, but I've done bothered with that yet.

Does this mean that currently there is no single OS X binary that could work on 10.9 to 10.11?
Currently our release model as well as the build scripts are one binary per platform. Do you know which binary was used in earlier versions?

**Comment by hiddentao** [comment]
Yep, would be nice if we could have one binary for all OS X versions, allowing us to continue releasing a single Mist/Wallet build for OS X.

**Comment by frozeman** [comment]
@bobsummerwill are they fixed on mac now automatically, or do we have to run the python script still?

The real link would be https://github.com/ethereum/webthree-umbrella/releases, but there is no 1.3.1 yet @bobsummerwill

**Comment by luclu** [comment]
@frozeman 
> Aside - you can ditch https://github.com/ethereum/mist/blob/develop/nodes/eth/fix_darwin_paths.py too with v1.3.0.

They want to release in in the following days - but essentially it is the same as bob's `1.3.0`.
BUT we seriously should consider to adjust gulpfile.js to download those nodes as we do with geth.

**Comment by frozeman** [comment]
Sure, but i also only see 1.2.9 https://github.com/ethereum/webthree-umbrella/releases

**Comment by luclu** [comment]
> @luclu please test if you can run the binary on a mac out of the box

I get some `libcryptopp.cpp` missing error..

**Comment by bobsummerwill** [comment]
You could probably just use https://github.com/bobsummerwill/cpp-ethereum/releases/download/v1.3.0/cpp-ethereum-osx-mavericks-v1.3.0.zip as a universal binary.

Yeah, @frozeman, we're mid-transition.

- Old release location:  https://github.com/ethereum/webthree-umbrella/releases
- v1.3.0 release location:  https://github.com/bobsummerwill/cpp-ethereum/releases
- v.1.3.1+ release location:  https://github.com/ethereum/cpp-ethereum/releases

Please could you give me more infor on libcryptocpp.cpp issue, @luclu?

**Comment by luclu** [comment]
> You could probably just use https://github.com/bobsummerwill/cpp-ethereum/releases/download/v1.3.0/cpp-ethereum-osx-mavericks-v1.3.0.zip as a universal binary.

This works just fine on El Capitan!

> Please could you give me more infor on libcryptocpp.cpp issue, @luclu?

Ah this was stupid of me, I found a weird way to copy those files but mist on.. :P

I will stress test it a little more now.

**Comment by frozeman** [comment]
No, the synchronous has nothing to do with blocking.
You need to do `web3.admin.getPeers(console.log)` to make the call, a sync call is not possible, as it uses pic sockets under the hood. Geth is simulating the synchronous way in their console, as they wrote their own pic provider

**Comment by alexvandesande** [comment]
CPP node updated
