### ISSUE TITLE
OSX app consistent naming

### ISSUE THREAD

**Issue by sammy007** [ethereum/mist#881]
Could you please finally decide how to name OSX app?

![screen shot 2016-06-24 at 19 41 10](https://cloud.githubusercontent.com/assets/7374093/16340874/c4082a76-3a43-11e6-966f-305276795975.png)

**Comment by luclu** [comment]
Ah, sorry for this. The name hasn't been changed in the codebase - due to some windows specific problem and didn't make it into this release due to different releasers not being aware. 
We will push this into `0.7.7` and also switch our packaging process to leverage travisCI soon.

I will close this in favour of https://github.com/ethereum/mist/issues/833.

**Comment by sammy007** [comment]
Ah thanks, didn't notice it.

**Comment by luclu** [comment]
PR in https://github.com/ethereum/mist/pull/883
