### ISSUE TITLE
MISSING WALLET AND ETHER

### ISSUE THREAD

**Issue by bikerboy4489** [ethereum/mist#915]
Ok, so I'm seriously done with all this ether business. I feel like none of the wallets have worked for me. I haven't had access to my 34.99 Ether in months now and no one seems to help. I have downloaded the latest wallet (0.7.6) and gone through the many hours of downloading the blocks. Once this was done it shows all my other accounts that are linked to my account but the one wallet contract that actually has my Ether in it is now completely gone! - see screen shot with todays date. 
![capture 01-07-2016](https://cloud.githubusercontent.com/assets/16919164/16519651/8937037e-3f82-11e6-9968-8ef278387a96.JPG)
It used to show but didn't allow me to do anything as it shows my other account as the 'owner' when I sign in to the owner account it still doesn't do anything! How do I get access to my ether?

Whenever I tried to backup my accounts using the older versions (which did show my contract wallet) it never backed up the account so I can access all my accounts by logging in using sites such as 'myetherwallet.com' but because I don't have the .JSON file for the wallet contract I still can't access it so it's a horrible loop I'm in.

I can see my funds here https://etherchain.org/account/0x46e5ee7101b6cd1348dfe5235bb2c67faee7bffe and on the screen grabs I've taken you can clearly see that I have access to the account which mist shows as the owner so I should be able to access this wallet.

Please help! I really could do with these funds.

Thanks in advance.
![07-04-2016 screen grab](https://cloud.githubusercontent.com/assets/16919164/16519551/cfb9ec90-3f81-11e6-98b1-a15164b6d67f.JPG)
![bikerboy account](https://cloud.githubusercontent.com/assets/16919164/16519556/d896d9b8-3f81-11e6-871c-03f626d780ca.JPG)

**Comment by luclu** [comment]
I'm really sorry to hear about your odyssey @bikerboy4489.

I will try to help you. From what I read you seem to have been one of the lucky ones running in a new bug introduced in version 0.7.5, that will reset Mist's DB and remove your contract wallets from the user interface (https://github.com/ethereum/mist/issues/844).
They are **not** lost - you can easily reimport them any time by choosing to add a new contract wallet followed by a switch to "import". You will need the contract wallet's address which you can either find somewhere you have written it down as you were advised or using a blockchainexplorer (just follow the transactions of the owner accounts to get the address).

Though to interact with the contracts you will need at least a little amount of Ether in your etherbase accounts.

The following is an explanation I gave to a gitter-user some days ago. I hope this excerpt will clarify how all those pieces interact.

> Just to be clear that there is no confusion. We have two distinct types of „wallets“. Accounts and contract wallets.
 - Accounts are just public-private key pairs having this address (public key) and the keyfile (private key, you should backup) - they are the basis of the whole system from a perspective of interaction.
 - Contract Wallets are Smart Contracts (here is their code).
They are programmed so that they are controlled by a account (you need its private key) and have for example the feature of multiple owners ("multi-sig(nature)“) - so some actions like spending over the day limit need the confirmation of those other owners as well.

> Passwords are a mean to protect your accounts. And quite simple every account has its own password.

>Now there is own special case in the current system. That is the „etherbase“.
This is the first account. And the one you specified the password for during the on boarding.

>Everytime you "run" a smartcontract like instructing the wallet contract to send ether to somewhere else you have to tell the ethereum network to execute this code. This is where this gas is used for, to pay for its execution. Eventually this gas is payed from the etherbase account - its what it makes special.

**Comment by bikerboy4489** [comment]
Ok that's great. Now I have visual off my account again which is great! Now the bad news is I am unable to transfer to a new wallet or account as recommended due to the recent hack. It is saying that my password is incorrect which isn't the case at all as if I were entering the wrong password it wouldn't let me login to the ether wallet at all!

Any advice on this one?

Thanks in advance.

**Comment by luclu** [comment]
That's great!
Could you new please go to your `keystore` folder and check if any account is duplicate? Thus is the number of files the same as the number of accounts (no contract wallets) in your wallet ui?

**Comment by bikerboy4489** [comment]
I have 3 files in my keystore and 3 accounts showing, 2 are located in Geth and the third is showing in Ethereum Node Eth. I'm so close to accessing the Ether yet so far! It won't let me transfer the Ether to my other account without removing it from my original wallet that is classed as 'vunerable' yet it won't let me create a new wallet to transfer it to as it's saying my password is wrong! hmm...

Any Ideas?

Thanks

**Comment by luclu** [comment]
We just released version `0.8.1` which fixes the "wrong password" alert which was wrongly displayed for any error that could happen while communicating with the node. 
Could you please try to send again and report the error you receive?

**Comment by luclu** [comment]
@bikerboy4489 where you able to solve it? What error messages do you encounter with `0.8.1`?

**Comment by luclu** [comment]
Closed as of inactivity.

**Comment by RavashlindonX** [comment]
Hi, 

Im just having the same issue has bikerboy 

I can see my balance on block chain

https://etherchain.org/account/0xaA4e9C7C7Ebc68c852E65F52aa4FeD99323a3fe5


But after the update the wallet as a 0 balance 

![image](https://cloud.githubusercontent.com/assets/22816586/19350321/84a2ecca-9157-11e6-8717-e879c624854e.png)


Please help.....

**Comment by EagleEyedTiger** [comment]
Good afternoon,

I am having exactly the same issue as both Ravash and bikerboy. Wallet is showing no ether and when I try to update the blockchain it does not sync. I did find the following in the node log file 

**After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!**

As far as I understand this means I need to resync the entire blockchain from the start right? If so I would really appreciate it if someone could explain to me how this is done.  

I also found block sync errors occurring after just 17 seconds of downloading the blockchain

**Block synchronisation started 16:31:37**
**Synchronisation failed: block header download canceled (requested) 16:31:54**

It would be great if someone could either explain whats going on so I can fix it or point me in the right direction. 
I feel that if I could restart the entire blockchain download then I would be OK. 
I need to update my wallet contract as it is old and since I have had this warning and the hardfork nothing has worked. 
Neither 0.8.1 nor 0.8.6 work for me. 0.8.1 will show my balance but won't resync the blockchain and 0.8.6 doesn't sync with the blockchain or import my accounts. Really need help on this one. 
Thanks

**Comment by luclu** [comment]
@EagleEyedTiger those error messages are harmless.
Considering the latest Hard Fork you must use release `0.8.6`.
Please follow these [instructions](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555).

**Comment by EagleEyedTiger** [comment]
Great thanks I will let you know.

**Comment by Pathrics** [comment]
@luclu Dear Luclu, since you have been so helpful with the above problems, I was hoping to get your advice on my little issue. I have some ETH in my Ethereal wallet, when trying to send it to another wallet, the below message shows up. Can you please let me know where and how i can access the "menu" etc? Sorry, pretty new to crypto and appreciate your help! Thanks
![screen shot 2016-11-21 at 21 51 03](https://cloud.githubusercontent.com/assets/23643326/20501072/89db8274-b038-11e6-98cf-74ef4ba36570.png)

**Comment by luclu** [comment]
Hey @Pathrics, don't worry, this kind of a stupid error. Basically a keyfile (each account has one as you might know, make a backup of those!) has a duplicate in the the keystore folder. Simply go to the menu in Ethereum Wallet -> accounts -> backup -> accounts as this will open finder. Go to the keystore folder and check for duplicates. (You might want to use a texteditor and look for files with the same address value if the file name does not contain it.)

**Comment by Pathrics** [comment]
Hey Luclu, worked perfectly fine. Thanks for your quick reply and help, much appreciated! Patrick

**Comment by Pathrics** [comment]
@luclu Thank you!

**Comment by WireGhost** [comment]
Having the same issue. It's been a year. My transfer went to a contract address   0xe16171A65715841DF329a582A5DfFA17f900aC8d. Can't tell what is going on.

**Comment by sfaridi** [comment]
I have the same exact issue. The address changed and now I can't access my ether in wallet. Instead a new wallet is created with 0 balance.

**Comment by numero41** [comment]
hello, can all thes issues be related to these ones? 
https://github.com/kvhnuke/etherwallet/issues/1528
https://github.com/kvhnuke/etherwallet/issues/1539
