### ISSUE TITLE
Need info maybe help !

### ISSUE THREAD

**Issue by B4k3RZ** [ethereum/mist#96]
I have started mining Eth lastly .. I'd have already made 75 .. but I doubt this is true.. my wallet says 0 peers but my miner seems to work .. here is my consol
![console](https://cloud.githubusercontent.com/assets/15887218/12009116/0be9a9c6-ac39-11e5-8225-8e3902ee3538.jpg)

**Comment by B4k3RZ** [comment]
and this is my wallet
![wallet](https://cloud.githubusercontent.com/assets/15887218/12009128/6ddacbec-ac39-11e5-9467-7a7b34251b71.jpg)

**Comment by frozeman** [comment]
Yes thats not correct. you block is number 15. which can't be right as the current height is 700 000+

It seems that you firewall is blocking the geth node from connecting to anywhere.

**Comment by B4k3RZ** [comment]
ok let me give it a try ! but Im now with 220 ether .. where do they come from are they mine ?

**Comment by B4k3RZ** [comment]
firewall is now off... this is what its looking like now
![geth](https://cloud.githubusercontent.com/assets/15887218/12011025/586954ec-ac8c-11e5-93e9-f88ec6abfcba.jpg)

**Comment by B4k3RZ** [comment]
![wallet2](https://cloud.githubusercontent.com/assets/15887218/12011765/683f594e-aca9-11e5-8dab-61bf711cb163.png)

**Comment by frozeman** [comment]
As long s you don't have peers and are synced up your not connected to the network.

Don't mine, make sure you geth is up to date and check that your ports are open.

**Comment by frozeman** [comment]
The 220 ether are yours, but as soon as you sync up they are gone, as you mined them technically on your own private network. Once you connect to other peers, your node will see that you were on a fork and drop your mined blocks.

**Comment by h2002al** [comment]
Hello,

I am totally new with etherium. 10-12 days ago have a suggestion to my friend about this project and i find it very interesting. Even I cannot understand to many thing because I am not a programmer or developer the aims of this platform and project seems very attractive for me (I am a hobbyist of new thing generally and especially about peer to peer technology particularly) Read some things and installed the pre released 0.3.7 wallet. Bought some etherium. Know the procedure of sending ether to account and then create the wallet (is a contract) with the ether sent to the created account (which can be created for free). I need some other knowledge I were not able to find during my search in internet or the site of etherium and I will appreciate at maximum some help.

1, I want to send all my bought etherium (and the other I will buy in the future because find very interesting this project) but must be sure that they cannot be lost. At the core bitcoin wallet (similar with this wallet you are offering in this site) is the file wallet.dat which make me sure that my bitcoin cannot be lost. Exist with this wallet some file which must be stored securely somewhere in order that make me sure that my etherium send to this wallet will be lost if my desktop crashed? If not what can i do to assure my ether from a possible crash?

2. I want to mine but the command is deactivated. Even the Geth command is deactivated (even is checked). Needed ether in the wallet to mine or the having ether have nothing to do with the mining process and must be made some other thing?

3. If the mining process need ether to be realized, depends the amount of ether mined (earned) from the amount of ether which is in the wallet?

3. Read somewhere that for the moment the etherium mining is a CPU based mining but it is work in progress regarding a GPU based mining. The actual wallet is a CPU mining or is already finalized the GPO one and this wallet mine with GPU? Ask this because must use one pc in the first case and another one in the second case.

Thanks a lot for the time and effort to everyone who will clarify these points for me. i would like to go forward with etherium and the answers of the above questions would be a big help for me.

**Comment by frozeman** [comment]
@h2002al Thanks for your interest.

Here are my answers:

1. We deactivate the mining button for the main net, as CPU mining wouldn't bring you any ether, even in 10 years.

2. To mine, you can switch to a testnet, but then you get testnet ether, no real ones.

3. If you want to GPU mine, you would need to start your own command line tools.

4. Can you send a screenshot? you should see "unmanned account", at least.

Concerning backup: You can back up your nodes key store folder, which contains all your keys, generated and encrypted by your node.

- Its on Mac at `~/Library/Ethereum/keystore`
- On linux: `~/.ethereum/keystore`
- On Windows: `%APPDATA%/Ethereum` (i guess)

If you create wallet contracts, just make sure you backup the contract/wallet address, once created. So you can later import it again.

**Comment by h2002al** [comment]
@frozeman. Thanks a lot for explanations. And thanks for the clarification about mining. At least now I know that the only way to have ether is to buy it. 

1. For the GPU mining. Cannot be able to start my own command lines. So must forget it. Or maybe the next version will have a easy version to mine with GPU like the actual one which (even is in vain and I don't understand why is in the wallet when cannot be mined) will make me to mine with GPU. Another thing and congrats for this. Seems amazing to me that etherium is passsed so fast from the CPU to GPU mining. Bitcoin wanted much more time to realize such step...

2. I'm posting here two screenshot about my unnamed account. In both don't showed any kind of name. I passed from the first screenshot (visualization in wallet) to the second one clicking at the word "Etherbase". I don't know if this the right one but it is the only I found. For more I have forgotten even the name of my created account (or better have in mind one but I am not sure if is that). Anyhow can be creted more than one account so cannot be a problem I think. Correct me if not so. Here I want to make another question: What is the importance of the name of account? For what serve? Can be used to send ether at that account without using the ether address (which must be the totality of numbers and letters under the written "account" or "Etherbase" which begin with zero x)

3. About backup. The command given above for windows is not the correct one. I am giving two screenshot when I use this command and the result haven after the execute of that command. 

4. About the backup of contract/wallet address immediately after the creation of wallet contract (sorry my ignorance) what must to do? If the backup is a simple copy of something what must to copy (don't knowing the procedure and what can be because the logic of ether wallet is totally different from the ones used or seen from me) find very difficult to find and to do the needed, have fear to make errors that can reparable problems). can I find a step by step guide about this procedure.




![account 2](https://cloud.githubusercontent.com/assets/4286283/12037507/ad950a3c-ae4f-11e5-83e0-bb0cd5ee75da.png)
![name accounts](https://cloud.githubusercontent.com/assets/4286283/12037506/ad9500fa-ae4f-11e5-9760-c6d57e3db4f7.png)
![the comand](https://cloud.githubusercontent.com/assets/4286283/12037509/ad994778-ae4f-11e5-9f68-cd0e20c62329.png)
![the result](https://cloud.githubusercontent.com/assets/4286283/12037508/ad98b286-ae4f-11e5-87a9-b8b3c15d8a76.png)

**Comment by 5chdn** [comment]
@h2002al try `%APPDATA%\Ethereum`
-> note the backslash.

**Comment by h2002al** [comment]
@5chdn @frozeman 

Thanks for the help. The above command worked. But appears 4 folders and one file. Named respectively: chaindata, dapp, keystore, nodesm (folders) and nodekey (file). Frozeman write in his posts " You can back up your nodes key store folder, which contains all your keys, generated and encrypted by your node." But the node key is a file and not a folder. Which of the above must be back up-ed (must be one between keystore - the most probable if is a folder - or nodekey - which has the name given by frozeman - but is a file and not a folder.

Then please answer me if it is important the name of account. I have wallets in my desktop and in my laptop I have registered two accounts and cannot see any of those. At laptop have registered two account and have the same visualization as the above showed with my screenshot. So there are any risk if I use the address showed under the name ETHEREUM to send ether at my wallet (in this account identified with this ID) in order to  create my wallet?

Can you explain (maybe with some screenshot) what kind of data must backup when will create the wallet with a contract.

Thanks and sorry if my questions seems easy things for you. But as I told before this kind of wallet is totally a new thing for me. So have fear to make errors which can be unrecoverable.

**Comment by frozeman** [comment]
its the `keystore` folder, which contains your keys, as i wrote "...your nodes key store folder", which would be better written as "...your node's "keystore" folder".

You mainly need to back up the keystore folder, and the addresses of any contract wallet you create
